const std = @import("std");
const assert = std.debug.assert;

const conformance = @import("conformance");

const ast = conformance.ast;
const Printer = conformance.Printer;

pub fn main() !void {
    var stdout = std.io.bufferedWriter(std.io.getStdOut().writer());
    const stdout_writer = stdout.writer();
    var memory: [Printer.default_memory_size]u8 = undefined;
    var printer = Printer.init(&memory, stdout_writer.any(), .{
        .indent_width = 4,
        .start_level = 1,
    });

    const tests = try conformance.parse(printer.arena());

    try emit(&printer, tests);
    try stdout.flush();
}

fn satisfies(requirement: ast.Case.Requirement) bool {
    return switch (requirement) {
        // `UInt128` is sixteen bytes wide, so a value above the maximum cannot be constructed.
        .requires_unbounded_integers => false,
        // `Amount` is a `UInt128`, so a fractional value cannot be constructed.
        .requires_fractional_amounts => false,
        // `NativeClient.Dispose` discards the status of a second `tb_client_deinit`.
        .requires_raise_on_double_close => false,
    };
}

fn emit(printer: *Printer, tests: ast.ConformanceTests) !void {
    try printer.write(
        \\////////////////////////////////////////////////////////////
        \\// This file was auto-generated by dotnet_conformance.zig
        \\// Do not manually modify.
        \\////////////////////////////////////////////////////////////
        \\
        \\using Microsoft.VisualStudio.TestTools.UnitTesting;
        \\using System;
        \\using System.Diagnostics;
        \\using System.IO;
        \\using System.Threading;
        \\using System.Threading.Tasks;
        \\
        \\namespace TigerBeetle.Tests;
        \\
        \\[TestClass]
        \\public class ConformanceTests
        \\{
        \\    private static TBConformanceServer server = null!;
        \\    private Client client = null!;
        \\
        \\    [ClassInitialize]
        \\    public static void Initialize(TestContext _)
        \\    {
        \\        server = new TBConformanceServer();
        \\    }
        \\
        \\    [ClassCleanup]
        \\    public static void Cleanup()
        \\    {
        \\        server.Dispose();
        \\    }
        \\
        \\    [TestInitialize]
        \\    public void CreateClient()
        \\    {
        \\        client = new Client(0, new string[] { server.Address });
        \\    }
        \\
        \\    [TestCleanup]
        \\    public void CloseClient()
        \\    {
        \\        client.Dispose();
        \\    }
        \\
    );
    for (tests.suites) |suite| {
        try printer.write_empty_line();
        try printer.print_indented("// Suite: {s}", .{suite.name});
        for (suite.cases) |case| {
            const case_memory = printer.mark();
            defer printer.release(case_memory);

            try printer.write_empty_line();
            if (case.requirement) |requirement| {
                if (!satisfies(requirement)) {
                    try printer.write_omission(case);
                    continue;
                }
            }
            try printer.write_indented("[TestMethod]");
            try printer.print_indented("public void {s}{s}()", .{
                try printer.to_case_alloc(.PascalCase, suite.name),
                try printer.to_case_alloc(.PascalCase, case.description),
            });
            try printer.write_indented("{");
            printer.indent();
            for (case.steps) |step| try emit_step(printer, step);
            printer.dedent();
            try printer.write_indented("}");
        }
    }
    try emit_server(printer);
    try printer.write("}\n");
}

fn emit_step(printer: *Printer, step: ast.Step) !void {
    switch (step) {
        .binding => |binding| try emit_binding(printer, binding),
        .call => |call| try emit_call(printer, call, .{}),
        .assertion => |assertion| try emit_assertion(printer, assertion),
    }
}

fn emit_binding(printer: *Printer, binding: ast.Binding) !void {
    const name = try printer.to_case_alloc(.camelCase, binding.name);
    switch (binding.value) {
        .generate_id => try printer.print_indented("var {s} = ID.Create();", .{name}),
        .generate_ids => |count| {
            try printer.print_indented("var {s} = new UInt128[{d}];", .{ name, count });
            try printer.print_indented(
                "for (var index = 0; index < {s}.Length; index++)",
                .{name},
            );
            try printer.write_indented("{");
            printer.indent();
            try printer.print_indented("if (index % {d} == 0)", .{
                ast.ids_between_sleeps,
            });
            try printer.write_indented("{");
            printer.indent();
            try printer.write_indented("Thread.Sleep(1);");
            printer.dedent();
            try printer.write_indented("}");
            try printer.print_indented("{s}[index] = ID.Create();", .{name});
            printer.dedent();
            try printer.write_indented("}");
        },
        .index => |index| {
            const reference = try printer.to_case_alloc(.camelCase, index.reference);
            try printer.print_indented("var {s} = {s}[{d}];", .{ name, reference, index.index });
        },
        .field_access => |access| {
            try printer.print_indented("var {s} = {s};", .{
                name,
                try render_field_access(printer, access),
            });
        },
        .record => |record| switch (record.type) {
            .Account, .Transfer => {
                try printer.print_indented("var {s} = new {s}", .{ name, @tagName(record.type) });
                try emit_record_fields(printer, record);
                try printer.write(";\n");
            },
            .U128 => {
                assert(record.fields.len == 1);
                const text = record.fields[0].value.integer;
                try printer.print_indented("UInt128 {s} = {s};", .{
                    name,
                    try render_uint128(printer, text),
                });
            },
            .AccountBalance,
            .AccountFilter,
            .AccountFilterFlags,
            .AccountFlags,
            .CreateAccountResult,
            .CreateTransferResult,
            .QueryFilter,
            .QueryFilterFlags,
            .TransferFlags,
            => unreachable,
        },
        .call => |call| {
            const prefix = try printer.string_alloc("var {s} = ", .{name});
            try emit_call(printer, call, .{ .prefix = prefix });
        },
        .integer, .boolean, .enum_literal, .reference, .increment, .decrement => unreachable,
    }
}

fn emit_call(
    printer: *Printer,
    call: ast.Call,
    options: struct {
        prefix: []const u8 = "",
        suffix: []const u8 = ";",
    },
) !void {
    if (call.concurrency > 1) {
        assert(options.prefix.len == 0);
        try printer.print_indented("var tasks = new Task[{d}];", .{call.concurrency});
        try printer.write_indented("for (var index = 0; index < tasks.Length; index++)");
        try printer.write_indented("{");
        printer.indent();
        try emit_invocation(printer, call, .{
            .prefix = "tasks[index] = Task.Run(() => ",
            .suffix = ");",
        });
        printer.dedent();
        try printer.write_indented("}");
        try printer.write_indented("Task.WhenAll(tasks).Wait();");
        return;
    }
    try emit_invocation(printer, call, .{ .prefix = options.prefix, .suffix = options.suffix });
}

fn emit_invocation(
    printer: *Printer,
    call: ast.Call,
    options: struct {
        prefix: []const u8,
        suffix: []const u8,
    },
) !void {
    switch (call.name) {
        .close_client => {
            try printer.print_indented("{s}client.Close(){s}", .{ options.prefix, options.suffix });
        },
        .sleep_ms => {
            assert(options.prefix.len == 0);
            assert(call.arguments.len == 1);
            try printer.print_indented("Thread.Sleep({s}){s}", .{
                call.arguments[0].integer,
                options.suffix,
            });
        },
        .create_accounts, .create_transfers => {
            const record_type = if (call.name == .create_accounts) "Account" else "Transfer";
            try printer.write_indent();
            try printer.print("{s}client.{s}(", .{
                options.prefix,
                dotnet_operation_name(call.name),
            });
            if (call.arguments.len == 0) {
                try printer.print("Array.Empty<{s}>()){s}\n", .{ record_type, options.suffix });
                return;
            }
            try printer.print("new {s}[] {{\n", .{record_type});
            printer.indent();
            for (call.arguments) |argument| switch (argument) {
                .record => |record| {
                    try printer.write_indented("new()");
                    try emit_record_fields(printer, record);
                    try printer.write(",\n");
                },
                .reference => |reference| {
                    try printer.print_indented("{s},", .{
                        try printer.to_case_alloc(.camelCase, reference),
                    });
                },
                else => unreachable,
            };
            printer.dedent();
            try printer.print_indented("}}){s}", .{options.suffix});
        },
        .lookup_accounts, .lookup_transfers => {
            try printer.write_indent();
            try printer.print("{s}client.{s}(", .{
                options.prefix,
                dotnet_operation_name(call.name),
            });
            if (call.arguments.len == 0) {
                try printer.print("Array.Empty<UInt128>()){s}\n", .{options.suffix});
                return;
            }
            try printer.write("new UInt128[] { ");
            for (call.arguments, 0..) |argument, index| {
                if (index > 0) try printer.write(", ");
                try printer.write(try render_id(printer, argument));
            }
            try printer.print(" }}){s}\n", .{options.suffix});
        },
        .get_account_transfers, .get_account_balances, .query_accounts, .query_transfers => {
            assert(call.arguments.len == 1);
            const filter = call.arguments[0].record;
            try printer.write_indent();
            try printer.print("{s}client.{s}(new {s}", .{
                options.prefix,
                dotnet_operation_name(call.name),
                @tagName(filter.type),
            });
            if (filter.fields.len == 0) {
                try printer.print("()){s}\n", .{options.suffix});
                return;
            }
            try printer.write("\n");
            try emit_record_fields(printer, filter);
            try printer.print("){s}\n", .{options.suffix});
        },
    }
}

fn emit_record_fields(printer: *Printer, record: ast.Record) !void {
    try printer.write_indented("{");
    printer.indent();
    for (record.fields) |field| {
        try printer.print_indented("{s} = {s},", .{
            try printer.to_case_alloc(.PascalCase, field.field.name),
            try render_typed_value(printer, field.field, field.value, .{}),
        });
    }
    printer.dedent();
    try printer.write_indent();
    try printer.write("}");
}

fn emit_assertion(printer: *Printer, assertion: ast.Assertion) !void {
    switch (assertion) {
        .equal => |equal| {
            const actual = try printer.to_case_alloc(.camelCase, equal.actual);
            try printer.print_indented("Assert.AreEqual({d}, {s}.Length);", .{
                equal.expected.len,
                actual,
            });
            for (equal.expected, 0..) |record, index| {
                for (record.fields) |field| {
                    try printer.print_indented("Assert.AreEqual({s}, {s}[{d}].{s});", .{
                        try render_typed_value(printer, field.field, field.value, .{
                            .cast = true,
                        }),
                        actual,
                        index,
                        try printer.to_case_alloc(.PascalCase, field.field.name),
                    });
                }
            }
        },
        .equal_field => |comparison| {
            const expected = switch (comparison.expected) {
                .expression => |expression| try render_typed_value(
                    printer,
                    comparison.actual.field,
                    expression,
                    .{ .cast = true },
                ),
                .field_reference => |field| try render_field_access(printer, field),
            };
            try printer.print_indented("Assert.AreEqual({s}, {s});", .{
                expected,
                try render_field_access(printer, comparison.actual),
            });
        },
        .empty => |actual| {
            try printer.print_indented("Assert.AreEqual(0, {s}.Length);", .{
                try printer.to_case_alloc(.camelCase, actual),
            });
        },
        .ascending => |ids| {
            const name = try printer.to_case_alloc(.camelCase, ids);
            try printer.print_indented(
                "for (var index = 1; index < {s}.Length; index++)",
                .{name},
            );
            try printer.write_indented("{");
            printer.indent();
            try printer.print_indented("Assert.IsTrue({s}[index - 1] < {s}[index]);", .{
                name,
                name,
            });
            printer.dedent();
            try printer.write_indented("}");
        },
        .greater_than => |comparison| {
            try printer.print_indented("Assert.IsTrue({s} > {s});", .{
                try render_field_access(printer, comparison.actual),
                try render_typed_value(
                    printer,
                    comparison.actual.field,
                    comparison.expected.expression,
                    .{},
                ),
            });
        },
        .fail => |failure| {
            const client_error = failure.client_error orelse unreachable;
            const prefix = try printer.string_alloc("Assert.ThrowsException<{s}>(() => ", .{
                dotnet_exception_name(client_error),
            });
            try emit_call(printer, failure.call, .{ .prefix = prefix, .suffix = ");" });
        },
    }
}

fn dotnet_exception_name(client_error: ast.ClientError) []const u8 {
    return switch (client_error) {
        .too_much_data => "TooMuchDataException",
        .client_closed => "ClientClosedException",
    };
}

fn render_field_access(printer: *Printer, reference: ast.FieldReference) ![]const u8 {
    return printer.string_alloc("{s}.{s}", .{
        try printer.to_case_alloc(.camelCase, reference.reference),
        try printer.to_case_alloc(.PascalCase, reference.field.name),
    });
}

fn render_typed_value(
    printer: *Printer,
    field: ast.Field,
    value: ast.Expression,
    options: struct { cast: bool = false },
) ![]const u8 {
    switch (value) {
        .enum_literal => |literal| {
            return printer.string_alloc("{s}.{s}", .{
                field.type.enum_name,
                try printer.to_case_alloc(.PascalCase, literal),
            });
        },
        .record => |flags| {
            assert(ast.Record.is_flags(flags.type));
            if (flags.fields.len == 0) {
                return printer.string_alloc("{s}.None", .{@tagName(flags.type)});
            }
            var text = std.ArrayList(u8).init(printer.arena());
            for (flags.fields, 0..) |flag, index| {
                assert(flag.value == .boolean and flag.value.boolean);
                if (index > 0) try text.appendSlice(" | ");
                try text.writer().print("{s}.{s}", .{
                    @tagName(flags.type),
                    try printer.to_case_alloc(.PascalCase, flag.field.name),
                });
            }
            return text.items;
        },
        .integer => |text| {
            const bits = field.type.int;
            if (bits == 128 and !fits_ulong(text)) return render_uint128(printer, text);
            if (!options.cast) return text;
            return printer.string_alloc("({s}){s}", .{ integer_type_name(bits), text });
        },
        .generate_id => return "ID.Create()",
        .reference => |name| return printer.to_case_alloc(.camelCase, name),
        .index => |index| {
            return printer.string_alloc("{s}[{d}]", .{
                try printer.to_case_alloc(.camelCase, index.reference),
                index.index,
            });
        },
        .boolean => |boolean| return if (boolean) "true" else "false",
        .field_access => |access| return render_field_access(printer, access),
        .increment => |arithmetic| return render_arithmetic(printer, arithmetic, "+"),
        .decrement => |arithmetic| return render_arithmetic(printer, arithmetic, "-"),
        .call, .generate_ids => unreachable,
    }
}

fn render_arithmetic(
    printer: *Printer,
    arithmetic: ast.Expression.Arithmetic,
    operator: []const u8,
) ![]const u8 {
    return printer.string_alloc("{s} {s} {d}", .{
        try printer.to_case_alloc(.camelCase, arithmetic.reference),
        operator,
        arithmetic.by,
    });
}

// Ids reach the client as `UInt128`.
fn render_id(printer: *Printer, expression: ast.Expression) ![]const u8 {
    switch (expression) {
        .generate_id => return "ID.Create()",
        .reference => |name| return printer.to_case_alloc(.camelCase, name),
        .integer => |text| return render_uint128(printer, text),
        else => unreachable,
    }
}

fn render_uint128(printer: *Printer, text: []const u8) ![]const u8 {
    if (fits_ulong(text)) return text;
    const value = std.fmt.parseInt(u128, text, 10) catch unreachable;
    return printer.string_alloc("new UInt128({d}UL, {d}UL)", .{
        @as(u64, @truncate(value >> 64)),
        @as(u64, @truncate(value)),
    });
}

fn fits_ulong(text: []const u8) bool {
    const value = std.fmt.parseInt(u128, text, 10) catch unreachable;
    return value <= std.math.maxInt(u64);
}

fn integer_type_name(bits: u16) []const u8 {
    return switch (bits) {
        128 => "UInt128",
        64 => "ulong",
        32 => "uint",
        16 => "ushort",
        8 => "byte",
        else => unreachable,
    };
}

fn dotnet_operation_name(name: ast.Call.Name) []const u8 {
    return switch (name) {
        .create_accounts => "CreateAccounts",
        .create_transfers => "CreateTransfers",
        .lookup_accounts => "LookupAccounts",
        .lookup_transfers => "LookupTransfers",
        .get_account_transfers => "GetAccountTransfers",
        .get_account_balances => "GetAccountBalances",
        .query_accounts => "QueryAccounts",
        .query_transfers => "QueryTransfers",
        .close_client, .sleep_ms => unreachable,
    };
}

// A copy of `TBServer` in `IntegrationTests.cs`.
fn emit_server(printer: *Printer) !void {
    try printer.write_empty_line();
    try printer.write_indented("private class TBConformanceServer : IDisposable");
    try printer.write_indented("{");
    printer.indent();
    try printer.write_indented(
        "// Path relative from /TigerBeetle.Test/bin/<framework>/<release>/<platform> :",
    );
    try printer.write_indented("private const string PROJECT_ROOT = \"../../../../..\";");
    try printer.write_indented(
        "private const string TB_PATH = PROJECT_ROOT + \"/../../../zig-out/bin\";",
    );
    try printer.write_indented("private const string TB_EXE = \"tigerbeetle\";");
    try printer.write_indented("private const string TB_SERVER = TB_PATH + \"/\" + TB_EXE;");
    try printer.write_empty_line();
    try printer.write_indented("private readonly Process process;");
    try printer.write_indented("private readonly string dataFile;");
    try printer.write_empty_line();
    try printer.write_indented("public string Address { get; }");
    try printer.write_empty_line();
    try printer.write_indented("public TBConformanceServer()");
    try printer.write_indented("{");
    printer.indent();
    try printer.write_indented("dataFile = Path.GetRandomFileName();");
    try printer.write_empty_line();
    try printer.write_indented("{");
    printer.indent();
    try printer.write_indented("using var format = new Process();");
    try printer.write_indented("format.StartInfo.FileName = TB_SERVER;");
    try printer.write_indented("format.StartInfo.Arguments =");
    printer.indent();
    try printer.write_indented(
        "$\"format --cluster=0 --replica=0 --replica-count=1 --development ./{dataFile}\";",
    );
    printer.dedent();
    try printer.write_indented("format.StartInfo.RedirectStandardError = true;");
    try printer.write_indented("format.Start();");
    try printer.write_indented("var formatStderr = format.StandardError.ReadToEnd();");
    try printer.write_indented("format.WaitForExit();");
    try printer.write_indented("if (format.ExitCode != 0)");
    try printer.write_indented("{");
    printer.indent();
    try printer.write_indented("throw new InvalidOperationException(");
    printer.indent();
    try printer.write_indented(
        "$\"format failed, ExitCode={format.ExitCode} stderr:\\n{formatStderr}\"",
    );
    printer.dedent();
    try printer.write_indented(");");
    printer.dedent();
    try printer.write_indented("}");
    printer.dedent();
    try printer.write_indented("}");
    try printer.write_empty_line();
    try printer.write_indented("process = new Process();");
    try printer.write_indented("process.StartInfo.FileName = TB_SERVER;");
    try printer.write_indented(
        "process.StartInfo.Arguments = $\"start --addresses=0 --development ./{dataFile}\";",
    );
    try printer.write_indented("process.StartInfo.RedirectStandardInput = true;");
    try printer.write_indented("process.StartInfo.RedirectStandardOutput = true;");
    try printer.write_indented("process.Start();");
    try printer.write_empty_line();
    try printer.write_indented("Address = process.StandardOutput.ReadLine()!.Trim();");
    printer.dedent();
    try printer.write_indented("}");
    try printer.write_empty_line();
    try printer.write_indented("public void Dispose()");
    try printer.write_indented("{");
    printer.indent();
    try printer.write_indented("process.Kill();");
    try printer.write_indented("process.WaitForExit();");
    try printer.write_indented("process.Dispose();");
    try printer.write_indented("File.Delete($\"./{dataFile}\");");
    printer.dedent();
    try printer.write_indented("}");
    printer.dedent();
    try printer.write_indented("}");
}
