const std = @import("std");
const assert = std.debug.assert;

const conformance = @import("conformance");

const types = conformance.types;
const utils = conformance.utils;

const indent_width = 2;
const statement_indent_level = 1; // test > statement

pub fn main() !void {
    var arena_instance = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena_instance.deinit();
    const arena = arena_instance.allocator();

    const tests = try conformance.parse(arena);

    var buffer = std.ArrayList(u8).init(arena);
    try emit(arena, buffer.writer().any(), tests);
    try std.io.getStdOut().writeAll(buffer.items);
}

fn satisfies(requirement: types.Case.Requirement) bool {
    return switch (requirement) {
        .requires_unbounded_integers => true,
    };
}

fn emit(arena: std.mem.Allocator, writer: std.io.AnyWriter, tests: types.ConformanceTests) !void {
    try writer.writeAll(
        \\//////////////////////////////////////////////////////////
        \\// This file was auto-generated by node_conformance.zig  //
        \\//               Do not manually modify.                 //
        \\//////////////////////////////////////////////////////////
        \\
        \\import assert, { AssertionError } from 'assert'
        \\import {
        \\  Account,
        \\  AccountFilter,
        \\  AccountFilterFlags,
        \\  AccountFlags,
        \\  Client,
        \\  createClient,
        \\  CreateAccountStatus,
        \\  CreateTransferStatus,
        \\  id,
        \\  QueryFilter,
        \\  QueryFilterFlags,
        \\  Transfer,
        \\  TransferFlags,
        \\} from '.'
        \\
        \\const REPLICA_ADDRESSES = [process.env.TB_ADDRESS || '3000'];
        \\
        \\// Every field is required, so cases spread these and override only what they set.
        \\const account_default: Account = {
        \\  id: 0n,
        \\  debits_pending: 0n,
        \\  debits_posted: 0n,
        \\  credits_pending: 0n,
        \\  credits_posted: 0n,
        \\  user_data_128: 0n,
        \\  user_data_64: 0n,
        \\  user_data_32: 0,
        \\  reserved: 0,
        \\  ledger: 0,
        \\  code: 0,
        \\  flags: 0,
        \\  timestamp: 0n,
        \\}
        \\
        \\const transfer_default: Transfer = {
        \\  id: 0n,
        \\  debit_account_id: 0n,
        \\  credit_account_id: 0n,
        \\  amount: 0n,
        \\  pending_id: 0n,
        \\  user_data_128: 0n,
        \\  user_data_64: 0n,
        \\  user_data_32: 0,
        \\  timeout: 0,
        \\  ledger: 0,
        \\  code: 0,
        \\  flags: 0,
        \\  timestamp: 0n,
        \\}
        \\
        \\const account_filter_default: AccountFilter = {
        \\  account_id: 0n,
        \\  user_data_128: 0n,
        \\  user_data_64: 0n,
        \\  user_data_32: 0,
        \\  code: 0,
        \\  timestamp_min: 0n,
        \\  timestamp_max: 0n,
        \\  limit: 0,
        \\  flags: 0,
        \\}
        \\
        \\const query_filter_default: QueryFilter = {
        \\  user_data_128: 0n,
        \\  user_data_64: 0n,
        \\  user_data_32: 0,
        \\  ledger: 0,
        \\  code: 0,
        \\  timestamp_min: 0n,
        \\  timestamp_max: 0n,
        \\  limit: 0,
        \\  flags: 0,
        \\}
        \\
        \\async function sleep_ms(ms: number): Promise<void> {
        \\  await new Promise(resolve => setTimeout(resolve, ms))
        \\}
        \\
        \\const tests: Array<{ name: string, fn: (client: Client) => Promise<void> }> = []
        \\function test(name: string, fn: (client: Client) => Promise<void>) {
        \\  tests.push({ name, fn })
        \\}
        \\
    );
    for (tests.suites) |suite| {
        try writer.writeAll("\n");
        try writer.print("// Suite: {s}\n", .{suite.name});
        for (suite.cases) |case| {
            try writer.writeAll("\n");
            if (case.requirement) |requirement| assert(satisfies(requirement));
            try writer.print("test('{s}_", .{suite.name});
            try emit_test_name(writer, case.description);
            try writer.writeAll("', async (client) => {\n");
            try emit_case(arena, writer, case);
            try writer.writeAll("})\n");
        }
    }
    try writer.writeAll(
        \\
        \\async function main () {
        \\  const start = new Date().getTime()
        \\  for (let i = 0; i < tests.length; i++) {
        \\    const client = createClient({
        \\      cluster_id: 0n,
        \\      replica_addresses: REPLICA_ADDRESSES,
        \\    })
        \\    try {
        \\      await tests[i].fn(client).then(() => {
        \\        console.log(tests[i].name + ": PASSED")
        \\      }).catch(error => {
        \\        console.log(tests[i].name + ": FAILED")
        \\        throw error
        \\      })
        \\    } finally {
        \\      client.destroy()
        \\    }
        \\  }
        \\  const end = new Date().getTime()
        \\  console.log('Time taken (s):', (end - start)/1000)
        \\}
        \\
        \\main().catch((error: AssertionError) => {
        \\  console.log('operator:', error.operator)
        \\  console.log('stack:', error.stack)
        \\  process.exit(-1);
        \\})
        \\
    );
}

fn emit_case(arena: std.mem.Allocator, writer: std.io.AnyWriter, case: types.Case) !void {
    for (case.steps) |step| try emit_step(arena, writer, step);
}

// Collapses anything that isn't alphanumeric into a single underscore.
fn emit_test_name(writer: std.io.AnyWriter, description: []const u8) !void {
    var last_was_underscore = false;
    for (description) |char| {
        if (std.ascii.isAlphanumeric(char)) {
            try writer.writeByte(char);
            last_was_underscore = false;
        } else if (!last_was_underscore) {
            try writer.writeByte('_');
            last_was_underscore = true;
        }
    }
}

fn emit_step(arena: std.mem.Allocator, writer: std.io.AnyWriter, step: types.Step) !void {
    switch (step) {
        .binding => |binding| try emit_binding(arena, writer, binding),
        .call => |call| try emit_call(arena, writer, call, .{}),
        .assertion => |assertion| try emit_assertion(arena, writer, assertion),
    }
}

fn emit_binding(arena: std.mem.Allocator, writer: std.io.AnyWriter, binding: types.Binding) !void {
    switch (binding.value) {
        .generate_id, .generate_ids, .index => {
            try emit_binding_value(arena, writer, binding.name, binding.value);
        },
        .record => |record| switch (record.type) {
            .U128 => {
                try emit_binding_value(arena, writer, binding.name, binding.value);
            },
            .Account, .Transfer => {
                const prefix = try std.fmt.allocPrint(arena, "const {s}: {s} = ", .{
                    binding.name, @tagName(record.type),
                });
                try emit_record(arena, writer, record, .{
                    .indent_level = statement_indent_level,
                    .prefix = prefix,
                });
            },
            // Flags cannot be bound on their own, and result types are never written by hand.
            .AccountBalance,
            .AccountFilter,
            .AccountFilterFlags,
            .AccountFlags,
            .CreateAccountResult,
            .CreateTransferResult,
            .QueryFilter,
            .QueryFilterFlags,
            .TransferFlags,
            => unreachable,
        },
        .call => |call| {
            const prefix = try std.fmt.allocPrint(arena, "const {s} = ", .{binding.name});
            try emit_call(arena, writer, call, .{ .prefix = prefix });
        },
        .integer, .boolean, .enum_literal, .reference => unreachable,
    }
}

fn emit_binding_value(
    arena: std.mem.Allocator,
    writer: std.io.AnyWriter,
    name: []const u8,
    value: types.Expression,
) !void {
    const rendered = try render_expression(arena, value);
    try write_indent(writer, statement_indent_level);
    try writer.print("const {s} = {s}\n", .{ name, rendered });
}

fn emit_call(
    arena: std.mem.Allocator,
    writer: std.io.AnyWriter,
    call: types.Call,
    options: struct {
        prefix: []const u8 = "",
    },
) !void {
    if (call.concurrency > 1) {
        assert(options.prefix.len == 0);
        try write_indent(writer, statement_indent_level);
        try writer.print("const operations = Array.from({{ length: {d} }}, () =>\n", .{
            call.concurrency,
        });
        try emit_operation(arena, writer, call, .{
            .indent_level = statement_indent_level + 1,
            .awaited = false,
        });
        try write_indent(writer, statement_indent_level);
        try writer.writeAll(")\n");
        try write_indent(writer, statement_indent_level);
        try writer.writeAll("await Promise.all(operations)\n");
    } else {
        try emit_operation(arena, writer, call, .{
            .indent_level = statement_indent_level,
            .prefix = options.prefix,
        });
    }
}

fn emit_operation(
    arena: std.mem.Allocator,
    writer: std.io.AnyWriter,
    call: types.Call,
    options: struct {
        indent_level: u32,
        prefix: []const u8 = "",
        awaited: bool = true,
    },
) !void {
    const awaited = if (options.awaited) "await " else "";
    switch (call.name) {
        .close_client => {
            assert(options.prefix.len == 0);
            try write_indent(writer, options.indent_level);
            try writer.writeAll("client.destroy()\n");
        },
        .sleep_ms => {
            assert(options.prefix.len == 0);
            assert(call.arguments.len == 1);
            const ms = try render_expression(arena, call.arguments[0]);
            try write_indent(writer, options.indent_level);
            try writer.print("{s}sleep_ms({s})\n", .{ awaited, ms });
        },
        .create_accounts, .create_transfers => {
            try write_indent(writer, options.indent_level);
            try writer.print("{s}{s}client.{s}([\n", .{
                options.prefix, awaited, try method_name(arena, call.name),
            });
            for (call.arguments) |argument| switch (argument) {
                .record => |record| try emit_record(arena, writer, record, .{
                    .indent_level = options.indent_level + 1,
                    .suffix = ",",
                }),
                .reference => |reference| {
                    try write_indent(writer, options.indent_level + 1);
                    try writer.print("{s},\n", .{reference});
                },
                else => unreachable,
            };
            try write_indent(writer, options.indent_level);
            try writer.writeAll("])\n");
        },
        .lookup_accounts, .lookup_transfers => {
            try write_indent(writer, options.indent_level);
            try writer.print("{s}{s}client.{s}([", .{
                options.prefix, awaited, try method_name(arena, call.name),
            });
            for (call.arguments, 0..) |argument, index| {
                if (index > 0) try writer.writeAll(", ");
                try writer.writeAll(try render_id(arena, argument));
            }
            try writer.writeAll("])\n");
        },
        .get_account_transfers, .get_account_balances, .query_accounts, .query_transfers => {
            assert(call.arguments.len == 1);
            const prefix = try std.fmt.allocPrint(arena, "{s}{s}client.{s}(", .{
                options.prefix, awaited, try method_name(arena, call.name),
            });
            try emit_record(arena, writer, call.arguments[0].record, .{
                .indent_level = options.indent_level,
                .prefix = prefix,
                .suffix = ")",
            });
        },
    }
}

fn emit_record(
    arena: std.mem.Allocator,
    writer: std.io.AnyWriter,
    record: types.Record,
    options: struct {
        indent_level: u32,
        prefix: []const u8 = "",
        suffix: []const u8 = "",
    },
) !void {
    try write_indent(writer, options.indent_level);
    try writer.print("{s}{{\n", .{options.prefix});
    try write_indent(writer, options.indent_level + 1);
    try writer.print("...{s},\n", .{record_default(record.type)});
    for (record.fields) |field| {
        const value = try render_field_value(arena, field);
        try write_indent(writer, options.indent_level + 1);
        try writer.print("{s}: {s},\n", .{ field.name, value });
    }
    try write_indent(writer, options.indent_level);
    try writer.print("}}{s}\n", .{options.suffix});
}

fn emit_assertion(
    arena: std.mem.Allocator,
    writer: std.io.AnyWriter,
    assertion: types.Assertion,
) !void {
    switch (assertion) {
        .equal => |equal| {
            try write_indent(writer, statement_indent_level);
            try writer.print("assert.strictEqual({s}.length, {d})\n", .{
                equal.actual, equal.expected.len,
            });
            for (equal.expected, 0..) |record, index| {
                for (record.fields) |field| {
                    const value = try render_field_value(arena, field);
                    try write_indent(writer, statement_indent_level);
                    try writer.print("assert.strictEqual({s}[{d}].{s}, {s})\n", .{
                        equal.actual, index, field.name, value,
                    });
                }
            }
        },
        .empty => |actual| {
            try write_indent(writer, statement_indent_level);
            try writer.print("assert.strictEqual({s}.length, 0)\n", .{actual});
        },
        .unique => |ids| {
            try write_indent(writer, statement_indent_level);
            try writer.print("assert.strictEqual(new Set({s}).size, {s}.length)\n", .{ ids, ids });
        },
        .ascending => |ids| {
            try write_indent(writer, statement_indent_level);
            try writer.print("for (let i = 1; i < {s}.length; i++) {{\n", .{ids});
            try write_indent(writer, statement_indent_level + 1);
            try writer.print("assert.ok({s}[i - 1] < {s}[i])\n", .{ ids, ids });
            try write_indent(writer, statement_indent_level);
            try writer.writeAll("}\n");
        },
        .equal_field => |comparison| {
            const value = try render_field_value(arena, comparison.field);
            try write_indent(writer, statement_indent_level);
            try writer.print("assert.strictEqual({s}.{s}, {s})\n", .{
                comparison.reference, comparison.field.name, value,
            });
        },
        .greater_than => |comparison| {
            const value = try render_field_value(arena, comparison.field);
            try write_indent(writer, statement_indent_level);
            try writer.print("assert.ok({s}.{s} > {s})\n", .{
                comparison.reference, comparison.field.name, value,
            });
        },
        .fail => |call| {
            try write_indent(writer, statement_indent_level);
            try writer.writeAll("await assert.rejects(async (): Promise<void> => {\n");
            try emit_operation(arena, writer, call, .{
                .indent_level = statement_indent_level + 1,
            });
            try write_indent(writer, statement_indent_level);
            try writer.writeAll("})\n");
        },
    }
}

fn write_indent(writer: std.io.AnyWriter, indent_level: u32) !void {
    try writer.writeByteNTimes(' ', indent_level * indent_width);
}

fn method_name(arena: std.mem.Allocator, name: types.Call.Name) ![]const u8 {
    return utils.to_case(arena, .camelCase, @tagName(name));
}

fn record_default(record_type: types.Record.Type) []const u8 {
    return switch (record_type) {
        .Account => "account_default",
        .Transfer => "transfer_default",
        .AccountFilter => "account_filter_default",
        .QueryFilter => "query_filter_default",
        // Flags and result records are never written by hand.
        .AccountBalance,
        .AccountFilterFlags,
        .AccountFlags,
        .CreateAccountResult,
        .CreateTransferResult,
        .QueryFilterFlags,
        .TransferFlags,
        .U128,
        => unreachable,
    };
}

fn render_expression(
    arena: std.mem.Allocator,
    expression: types.Expression,
) std.mem.Allocator.Error![]const u8 {
    switch (expression) {
        .generate_id => return "id()",
        .generate_ids => |count| {
            return std.fmt.allocPrint(
                arena,
                "Array.from({{ length: {d} }}, () => id())",
                .{count},
            );
        },
        .call => unreachable, // Calls are emitted by emit_call/emit_operation.
        .record => |record| switch (record.type) {
            .U128 => {
                assert(record.fields.len == 1);
                return render_bigint(arena, record.fields[0].value.integer);
            },
            // Flags can't be bound on their own for now (parser-rejected), and the
            // remaining records are never written by hand.
            .Account,
            .AccountBalance,
            .AccountFilter,
            .AccountFilterFlags,
            .AccountFlags,
            .CreateAccountResult,
            .CreateTransferResult,
            .QueryFilter,
            .QueryFilterFlags,
            .Transfer,
            .TransferFlags,
            => unreachable,
        },
        .integer => |text| return text,
        .boolean => |value| return if (value) "true" else "false",
        .enum_literal => unreachable, // Only valid as a record field, rendered there.
        .reference => |name| return name,
        .index => |index| {
            return std.fmt.allocPrint(arena, "{s}[{d}]", .{ index.reference, index.index });
        },
    }
}

// Ids reach the client as `bigint`, whatever shape they take in the corpus.
fn render_id(arena: std.mem.Allocator, expression: types.Expression) ![]const u8 {
    switch (expression) {
        .generate_id => return "id()",
        .reference => |name| return name,
        .integer => |text| return render_bigint(arena, text),
        else => unreachable,
    }
}

fn render_flags(arena: std.mem.Allocator, record: types.Record) ![]const u8 {
    var text = std.ArrayList(u8).init(arena);
    for (record.fields, 0..) |field, index| {
        assert(field.value == .boolean and field.value.boolean);
        if (index > 0) try text.appendSlice(" | ");
        try text.writer().print("{s}.{s}", .{ @tagName(record.type), field.name });
    }
    return text.items;
}

fn render_field_value(arena: std.mem.Allocator, field: types.Field) ![]const u8 {
    switch (field.value) {
        .enum_literal => |literal| {
            return std.fmt.allocPrint(arena, "{s}.{s}", .{ field.type.enum_name, literal });
        },
        .record => |record| {
            assert(types.Record.is_flags(record.type));
            return render_flags(arena, record);
        },
        // The client takes `bigint` for u128 and u64 fields, and `number` for the narrower ones.
        .integer => |text| {
            if (field.type.int >= 64) return render_bigint(arena, text);
            return text;
        },
        .generate_id, .boolean, .reference, .index => {
            return render_expression(arena, field.value);
        },
        .call, .generate_ids => unreachable,
    }
}

fn render_bigint(arena: std.mem.Allocator, text: []const u8) ![]const u8 {
    return std.fmt.allocPrint(arena, "{s}n", .{text});
}
