const std = @import("std");
const assert = std.debug.assert;

const conformance = @import("conformance");

const ast = conformance.ast;
const Printer = conformance.Printer;

pub fn main() !void {
    var stdout = std.io.bufferedWriter(std.io.getStdOut().writer());
    const stdout_writer = stdout.writer();
    var memory: [Printer.default_memory_size]u8 = undefined;
    var printer = Printer.init(&memory, stdout_writer.any(), .{
        .indent_width = 2,
    });

    const tests = try conformance.parse(printer.arena());

    try emit(&printer, tests);
    try stdout.flush();
}

fn satisfies(requirement: ast.Case.Requirement) bool {
    return switch (requirement) {
        // Amounts are `bigint`s: arbitrary precision, but integral only.
        .requires_unbounded_integers => true,
        .requires_fractional_amounts => false,
    };
}

fn emit(printer: *Printer, tests: ast.ConformanceTests) !void {
    try printer.write(
        \\///////////////////////////////////////////////////////////
        \\// This file was auto-generated by node_conformance.zig  //
        \\//               Do not manually modify.                 //
        \\///////////////////////////////////////////////////////////
        \\
        \\import assert, { AssertionError } from 'assert'
        \\import {
        \\  Account,
        \\  AccountFilter,
        \\  AccountFilterFlags,
        \\  AccountFlags,
        \\  Client,
        \\  createClient,
        \\  CreateAccountStatus,
        \\  CreateTransferStatus,
        \\  id,
        \\  QueryFilter,
        \\  QueryFilterFlags,
        \\  Transfer,
        \\  TransferFlags,
        \\} from '.'
        \\
        \\const REPLICA_ADDRESSES = [process.env.TB_ADDRESS || '3000'];
        \\
        \\// Every field is required, so cases spread these and override only what they set.
        \\const account_default: Account = {
        \\  id: 0n,
        \\  debits_pending: 0n,
        \\  debits_posted: 0n,
        \\  credits_pending: 0n,
        \\  credits_posted: 0n,
        \\  user_data_128: 0n,
        \\  user_data_64: 0n,
        \\  user_data_32: 0,
        \\  reserved: 0,
        \\  ledger: 0,
        \\  code: 0,
        \\  flags: 0,
        \\  timestamp: 0n,
        \\}
        \\
        \\const transfer_default: Transfer = {
        \\  id: 0n,
        \\  debit_account_id: 0n,
        \\  credit_account_id: 0n,
        \\  amount: 0n,
        \\  pending_id: 0n,
        \\  user_data_128: 0n,
        \\  user_data_64: 0n,
        \\  user_data_32: 0,
        \\  timeout: 0,
        \\  ledger: 0,
        \\  code: 0,
        \\  flags: 0,
        \\  timestamp: 0n,
        \\}
        \\
        \\const account_filter_default: AccountFilter = {
        \\  account_id: 0n,
        \\  user_data_128: 0n,
        \\  user_data_64: 0n,
        \\  user_data_32: 0,
        \\  code: 0,
        \\  timestamp_min: 0n,
        \\  timestamp_max: 0n,
        \\  limit: 0,
        \\  flags: 0,
        \\}
        \\
        \\const query_filter_default: QueryFilter = {
        \\  user_data_128: 0n,
        \\  user_data_64: 0n,
        \\  user_data_32: 0,
        \\  ledger: 0,
        \\  code: 0,
        \\  timestamp_min: 0n,
        \\  timestamp_max: 0n,
        \\  limit: 0,
        \\  flags: 0,
        \\}
        \\
        \\async function sleep_ms(ms: number): Promise<void> {
        \\  await new Promise(resolve => setTimeout(resolve, ms))
        \\}
        \\
        \\const tests: Array<{ name: string, fn: (client: Client) => Promise<void> }> = []
        \\function test(name: string, fn: (client: Client) => Promise<void>) {
        \\  tests.push({ name, fn })
        \\}
        \\
    );
    for (tests.suites) |suite| {
        try printer.write_empty_line();
        try printer.print_indented("// Suite: {s}", .{suite.name});
        for (suite.cases) |case| {
            try printer.write_empty_line();
            if (case.requirement) |requirement| {
                if (!satisfies(requirement)) {
                    try printer.write_omission(case);
                    continue;
                }
            }
            try printer.print_indented("test('{s}_{s}', async (client) => {{", .{
                suite.name,
                try printer.to_case_alloc(.snake_case, case.description),
            });
            printer.indent();
            for (case.steps) |step| try emit_step(printer, step);
            printer.dedent();
            try printer.write_indented("})");
        }
    }
    try printer.write(
        \\
        \\async function main () {
        \\  const start = new Date().getTime()
        \\  for (let i = 0; i < tests.length; i++) {
        \\    const client = createClient({
        \\      cluster_id: 0n,
        \\      replica_addresses: REPLICA_ADDRESSES,
        \\    })
        \\    try {
        \\      await tests[i].fn(client).then(() => {
        \\        console.log(tests[i].name + ": PASSED")
        \\      }).catch(error => {
        \\        console.log(tests[i].name + ": FAILED")
        \\        throw error
        \\      })
        \\    } finally {
        \\      client.destroy()
        \\    }
        \\  }
        \\  const end = new Date().getTime()
        \\  console.log('Time taken (s):', (end - start)/1000)
        \\}
        \\
        \\main().catch((error: AssertionError) => {
        \\  console.log('operator:', error.operator)
        \\  console.log('stack:', error.stack)
        \\  process.exit(-1);
        \\})
        \\
    );
}

fn emit_step(printer: *Printer, step: ast.Step) !void {
    switch (step) {
        .binding => |binding| try emit_binding(printer, binding),
        .call => |call| try emit_call(printer, call, .{}),
        .assertion => |assertion| try emit_assertion(printer, assertion),
    }
}

fn emit_binding(printer: *Printer, binding: ast.Binding) !void {
    switch (binding.value) {
        .generate_id, .generate_ids, .index, .field_access => {
            try emit_binding_value(printer, binding.name, binding.value);
        },
        .record => |record| switch (record.type) {
            .U128 => {
                try emit_binding_value(printer, binding.name, binding.value);
            },
            .Account, .Transfer => {
                const prefix = try printer.string_alloc("const {s}: {s} = ", .{
                    binding.name, @tagName(record.type),
                });
                try emit_record(printer, record, .{ .prefix = prefix });
            },
            // Flags cannot be bound on their own, and result types are never written by hand.
            .AccountBalance,
            .AccountFilter,
            .AccountFilterFlags,
            .AccountFlags,
            .CreateAccountResult,
            .CreateTransferResult,
            .QueryFilter,
            .QueryFilterFlags,
            .TransferFlags,
            => unreachable,
        },
        .call => |call| {
            const prefix = try printer.string_alloc("const {s} = ", .{binding.name});
            try emit_call(printer, call, .{ .prefix = prefix });
        },
        .integer, .boolean, .enum_literal, .reference, .increment, .decrement => unreachable,
    }
}

fn emit_binding_value(
    printer: *Printer,
    name: []const u8,
    value: ast.Expression,
) !void {
    const rendered = try render_expression(printer, value);
    try printer.print_indented("const {s} = {s}", .{ name, rendered });
}

fn emit_call(
    printer: *Printer,
    call: ast.Call,
    options: struct {
        prefix: []const u8 = "",
    },
) !void {
    if (call.concurrency > 1) {
        assert(options.prefix.len == 0);
        try printer.print_indented(
            "const operations = Array.from({{ length: {d} }}, () =>",
            .{call.concurrency},
        );
        printer.indent();
        try emit_operation(printer, call, .{ .awaited = false });
        printer.dedent();
        try printer.write_indented(")");
        try printer.write_indented("await Promise.all(operations)");
    } else {
        try emit_operation(printer, call, .{ .prefix = options.prefix });
    }
}

fn emit_operation(
    printer: *Printer,
    call: ast.Call,
    options: struct {
        prefix: []const u8 = "",
        awaited: bool = true,
    },
) !void {
    const awaited = if (options.awaited) "await " else "";
    switch (call.name) {
        .close_client => {
            assert(options.prefix.len == 0);
            try printer.write_indented("client.destroy()");
        },
        .sleep_ms => {
            assert(options.prefix.len == 0);
            assert(call.arguments.len == 1);
            const ms = try render_expression(printer, call.arguments[0]);
            try printer.print_indented("{s}sleep_ms({s})", .{ awaited, ms });
        },
        .create_accounts, .create_transfers => {
            if (call.arguments.len == 0) {
                try printer.print_indented("{s}{s}client.{s}([])", .{
                    options.prefix, awaited, try method_name(printer, call.name),
                });
                return;
            }
            try printer.print_indented("{s}{s}client.{s}([", .{
                options.prefix, awaited, try method_name(printer, call.name),
            });
            printer.indent();
            for (call.arguments) |argument| switch (argument) {
                .record => |record| try emit_record(printer, record, .{ .suffix = "," }),
                .reference => |reference| try printer.print_indented("{s},", .{reference}),
                else => unreachable,
            };
            printer.dedent();
            try printer.write_indented("])");
        },
        .lookup_accounts, .lookup_transfers => {
            try printer.write_indent();
            try printer.print("{s}{s}client.{s}([", .{
                options.prefix, awaited, try method_name(printer, call.name),
            });
            for (call.arguments, 0..) |argument, index| {
                if (index > 0) try printer.write(", ");
                try printer.write(try render_id(printer, argument));
            }
            try printer.write("])\n");
        },
        .get_account_transfers, .get_account_balances, .query_accounts, .query_transfers => {
            assert(call.arguments.len == 1);
            const prefix = try printer.string_alloc("{s}{s}client.{s}(", .{
                options.prefix, awaited, try method_name(printer, call.name),
            });
            try emit_record(printer, call.arguments[0].record, .{
                .prefix = prefix,
                .suffix = ")",
            });
        },
    }
}

fn emit_record(
    printer: *Printer,
    record: ast.Record,
    options: struct {
        prefix: []const u8 = "",
        suffix: []const u8 = "",
    },
) !void {
    try printer.print_indented("{s}{{", .{options.prefix});
    printer.indent();
    try printer.print_indented("...{s},", .{record_default(record.type)});
    for (record.fields) |field| {
        const value = try render_typed_value(printer, field.field, field.value);
        try printer.print_indented("{s}: {s},", .{ field.field.name, value });
    }
    printer.dedent();
    try printer.print_indented("}}{s}", .{options.suffix});
}

fn emit_assertion(
    printer: *Printer,
    assertion: ast.Assertion,
) !void {
    switch (assertion) {
        .equal => |equal| {
            try printer.print_indented("assert.strictEqual({s}.length, {d})", .{
                equal.actual, equal.expected.len,
            });
            for (equal.expected, 0..) |record, index| {
                for (record.fields) |field| {
                    const value = try render_typed_value(printer, field.field, field.value);
                    try printer.print_indented("assert.strictEqual({s}[{d}].{s}, {s})", .{
                        equal.actual, index, field.field.name, value,
                    });
                }
            }
        },
        .empty => |actual| {
            try printer.print_indented("assert.strictEqual({s}.length, 0)", .{actual});
        },
        .unique => |ids| {
            try printer.print_indented("assert.strictEqual(new Set({s}).size, {s}.length)", .{
                ids, ids,
            });
        },
        .ascending => |ids| {
            try printer.print_indented("for (let i = 1; i < {s}.length; i++) {{", .{ids});
            printer.indent();
            try printer.print_indented("assert.ok({s}[i - 1] < {s}[i])", .{ ids, ids });
            printer.dedent();
            try printer.write_indented("}");
        },
        .equal_field => |comparison| {
            const value = switch (comparison.expected) {
                .expression => |expression| try render_typed_value(
                    printer,
                    comparison.actual.field,
                    expression,
                ),
                .field_reference => |field| try render_field_access(printer, field),
            };
            try printer.print_indented("assert.strictEqual({s}.{s}, {s})", .{
                comparison.actual.reference, comparison.actual.field.name, value,
            });
        },
        .greater_than => |comparison| {
            const value = try render_typed_value(
                printer,
                comparison.actual.field,
                comparison.expected.expression,
            );
            try printer.print_indented("assert.ok({s}.{s} > {s})", .{
                comparison.actual.reference, comparison.actual.field.name, value,
            });
        },
        .fail => |call| {
            try printer.write_indented("await assert.rejects(async (): Promise<void> => {");
            printer.indent();
            try emit_operation(printer, call, .{});
            printer.dedent();
            try printer.write_indented("})");
        },
    }
}

fn method_name(printer: *Printer, name: ast.Call.Name) ![]const u8 {
    return printer.to_case_alloc(.camelCase, @tagName(name));
}

fn record_default(record_type: ast.Record.Type) []const u8 {
    return switch (record_type) {
        .Account => "account_default",
        .Transfer => "transfer_default",
        .AccountFilter => "account_filter_default",
        .QueryFilter => "query_filter_default",
        // Flags and result records are never written by hand.
        .AccountBalance,
        .AccountFilterFlags,
        .AccountFlags,
        .CreateAccountResult,
        .CreateTransferResult,
        .QueryFilterFlags,
        .TransferFlags,
        .U128,
        => unreachable,
    };
}

fn render_expression(
    printer: *Printer,
    expression: ast.Expression,
) std.mem.Allocator.Error![]const u8 {
    switch (expression) {
        .generate_id => return "id()",
        .generate_ids => |count| {
            return printer.string_alloc("Array.from({{ length: {d} }}, () => id())", .{count});
        },
        .call => unreachable, // Calls are emitted by emit_call/emit_operation.
        .record => |record| switch (record.type) {
            .U128 => {
                assert(record.fields.len == 1);
                return render_bigint(printer, record.fields[0].value.integer);
            },
            // Flags can't be bound on their own for now (parser-rejected), and the
            // remaining records are never written by hand.
            .Account,
            .AccountBalance,
            .AccountFilter,
            .AccountFilterFlags,
            .AccountFlags,
            .CreateAccountResult,
            .CreateTransferResult,
            .QueryFilter,
            .QueryFilterFlags,
            .Transfer,
            .TransferFlags,
            => unreachable,
        },
        .integer => |text| return text,
        .boolean => |value| return if (value) "true" else "false",
        .enum_literal => unreachable, // Only valid as a record field, rendered there.
        .reference => |name| return name,
        .index => |index| {
            return printer.string_alloc("{s}[{d}]", .{
                index.reference,
                index.index,
            });
        },
        .field_access => |access| return render_field_access(printer, access),
        .increment => |arithmetic| return render_arithmetic(printer, arithmetic, "+"),
        .decrement => |arithmetic| return render_arithmetic(printer, arithmetic, "-"),
    }
}

// Ids reach the client as `bigint`, whatever shape they take in the corpus.
fn render_id(printer: *Printer, expression: ast.Expression) ![]const u8 {
    switch (expression) {
        .generate_id => return "id()",
        .reference => |name| return name,
        .integer => |text| return render_bigint(printer, text),
        else => unreachable,
    }
}

fn render_flags(printer: *Printer, record: ast.Record) ![]const u8 {
    var text = std.ArrayList(u8).init(printer.arena());
    for (record.fields, 0..) |field, index| {
        assert(field.value == .boolean and field.value.boolean);
        if (index > 0) try text.appendSlice(" | ");
        try text.writer().print("{s}.{s}", .{ @tagName(record.type), field.field.name });
    }
    return text.items;
}

fn render_field_access(
    printer: *Printer,
    reference: ast.FieldReference,
) ![]const u8 {
    return printer.string_alloc("{s}.{s}", .{
        reference.reference,
        reference.field.name,
    });
}

// Only works for 64-bit fields for now because it emits a `bigint`.
fn render_arithmetic(
    printer: *Printer,
    arithmetic: ast.Expression.Arithmetic,
    operator: []const u8,
) ![]const u8 {
    return printer.string_alloc("{s} {s} {d}n", .{
        arithmetic.reference,
        operator,
        arithmetic.by,
    });
}

fn render_typed_value(
    printer: *Printer,
    field: ast.Field,
    value: ast.Expression,
) ![]const u8 {
    switch (value) {
        .enum_literal => |literal| {
            return printer.string_alloc("{s}.{s}", .{
                field.type.enum_name,
                literal,
            });
        },
        .record => |record| {
            assert(ast.Record.is_flags(record.type));
            return render_flags(printer, record);
        },
        // The client takes `bigint` for u128 and u64 fields, and `number` for the narrower ones.
        .integer => |text| {
            if (field.type.int >= 64) return render_bigint(printer, text);
            return text;
        },
        .generate_id,
        .boolean,
        .reference,
        .index,
        .field_access,
        .increment,
        .decrement,
        => {
            return render_expression(printer, value);
        },
        .call, .generate_ids => unreachable,
    }
}

fn render_bigint(printer: *Printer, text: []const u8) ![]const u8 {
    return printer.string_alloc("{s}n", .{text});
}
