###########################################################
## This file was auto-generated by ruby_conformance.zig ##
##               Do not manually modify.                ##
###########################################################

require "minitest/autorun"
require "tigerbeetle"

class TestConformance < Minitest::Test
  def setup
    @tb_address = ENV.fetch("TB_ADDRESS", "3000")
    @client = TigerBeetle::Client.new(cluster_id: 0, replica_addresses: @tb_address)
  end

  def teardown
    @client.close if @client && !@client.closed?
  end

  # Suite: generate_ids

  def test_generate_ids_generates_unique_ids
    ids = Array.new(1000) { TigerBeetle.id }
    assert_equal(ids.length, ids.uniq.length)
  end

  def test_generate_ids_generates_monotonically_increasing_ids
    ids = Array.new(100) { TigerBeetle.id }
    ids.each_cons(2) { |a, b| assert_operator(a, :<, b) }
  end

  # Suite: create_accounts

  def test_create_accounts_creates_an_account
    results = @client.create_accounts(
      [
        TigerBeetle::Account.new(
          id: TigerBeetle.id,
          ledger: 1,
          code: 1
        )
      ]
    )
    assert_equal(1, results.length)
    assert_equal(TigerBeetle::CreateAccountStatus::CREATED, results[0].status)
  end

  def test_create_accounts_returns_exists_for_a_duplicate_account
    account = TigerBeetle::Account.new(
      id: TigerBeetle.id,
      ledger: 1,
      code: 1
    )
    @client.create_accounts([account])
    results = @client.create_accounts([account])
    assert_equal(1, results.length)
    assert_equal(TigerBeetle::CreateAccountStatus::EXISTS, results[0].status)
  end

  def test_create_accounts_rejects_a_zero_id
    results = @client.create_accounts(
      [
        TigerBeetle::Account.new(
          id: 0,
          ledger: 1,
          code: 1
        )
      ]
    )
    assert_equal(1, results.length)
    assert_equal(TigerBeetle::CreateAccountStatus::ID_MUST_NOT_BE_ZERO, results[0].status)
  end

  def test_create_accounts_rejects_a_zero_ledger
    results = @client.create_accounts(
      [
        TigerBeetle::Account.new(
          id: TigerBeetle.id,
          ledger: 0,
          code: 1
        )
      ]
    )
    assert_equal(1, results.length)
    assert_equal(TigerBeetle::CreateAccountStatus::LEDGER_MUST_NOT_BE_ZERO, results[0].status)
  end

  def test_create_accounts_rejects_a_zero_code
    results = @client.create_accounts(
      [
        TigerBeetle::Account.new(
          id: TigerBeetle.id,
          ledger: 1,
          code: 0
        )
      ]
    )
    assert_equal(1, results.length)
    assert_equal(TigerBeetle::CreateAccountStatus::CODE_MUST_NOT_BE_ZERO, results[0].status)
  end

  def test_create_accounts_rejects_mutually_exclusive_flags
    results = @client.create_accounts(
      [
        TigerBeetle::Account.new(
          id: TigerBeetle.id,
          ledger: 1,
          code: 1,
          flags: TigerBeetle::AccountFlags::DEBITS_MUST_NOT_EXCEED_CREDITS |
            TigerBeetle::AccountFlags::CREDITS_MUST_NOT_EXCEED_DEBITS
        )
      ]
    )
    assert_equal(1, results.length)
    assert_equal(TigerBeetle::CreateAccountStatus::FLAGS_ARE_MUTUALLY_EXCLUSIVE, results[0].status)
  end

  # Suite: lookup_accounts

  def test_lookup_accounts_returns_an_existing_account
    account_id = TigerBeetle.id
    @client.create_accounts(
      [
        TigerBeetle::Account.new(
          id: account_id,
          ledger: 1,
          code: 1
        )
      ]
    )
    accounts = @client.lookup_accounts([account_id])
    assert_equal(1, accounts.length)
    assert_equal(account_id, accounts[0].id)
    assert_equal(1, accounts[0].ledger)
    assert_equal(1, accounts[0].code)
  end

  def test_lookup_accounts_returns_no_accounts_for_a_missing_id
    accounts = @client.lookup_accounts([TigerBeetle.id])
    assert_equal(0, accounts.length)
  end

  def test_lookup_accounts_returns_multiple_existing_accounts_in_one_batch
    account_1_id = TigerBeetle.id
    account_2_id = TigerBeetle.id
    @client.create_accounts(
      [
        TigerBeetle::Account.new(
          id: account_1_id,
          ledger: 1,
          code: 1
        ),
        TigerBeetle::Account.new(
          id: account_2_id,
          ledger: 2,
          code: 2
        )
      ]
    )
    accounts = @client.lookup_accounts([account_1_id, account_2_id])
    assert_equal(2, accounts.length)
    assert_equal(account_1_id, accounts[0].id)
    assert_equal(1, accounts[0].ledger)
    assert_equal(account_2_id, accounts[1].id)
    assert_equal(2, accounts[1].ledger)
  end

  def test_lookup_accounts_returns_only_the_existing_account_for_a_partial_match
    existing_id = TigerBeetle.id
    missing_id = TigerBeetle.id
    @client.create_accounts(
      [
        TigerBeetle::Account.new(
          id: existing_id,
          ledger: 1,
          code: 1
        )
      ]
    )
    accounts = @client.lookup_accounts([existing_id, missing_id])
    assert_equal(1, accounts.length)
    assert_equal(existing_id, accounts[0].id)
  end

  def test_lookup_accounts_returns_no_accounts_for_an_empty_batch
    accounts = @client.lookup_accounts([])
    assert_equal(0, accounts.length)
  end

  def test_lookup_accounts_round_trips_all_fields
    account_id = TigerBeetle.id
    user_data_128 = TigerBeetle.id
    @client.create_accounts(
      [
        TigerBeetle::Account.new(
          id: account_id,
          ledger: 7,
          code: 42,
          user_data_128: user_data_128,
          user_data_64: 9999999999,
          user_data_32: 12345,
          flags: TigerBeetle::AccountFlags::HISTORY
        )
      ]
    )
    accounts = @client.lookup_accounts([account_id])
    assert_equal(1, accounts.length)
    assert_equal(account_id, accounts[0].id)
    assert_equal(7, accounts[0].ledger)
    assert_equal(42, accounts[0].code)
    assert_equal(user_data_128, accounts[0].user_data_128)
    assert_equal(9999999999, accounts[0].user_data_64)
    assert_equal(12345, accounts[0].user_data_32)
    assert_equal(TigerBeetle::AccountFlags::HISTORY, accounts[0].flags)
    account = accounts[0]
    assert_operator(account.timestamp, :>, 0)
  end

  # Suite: create_transfers

  def test_create_transfers_creates_a_transfer
    debit_account_id = TigerBeetle.id
    credit_account_id = TigerBeetle.id
    @client.create_accounts(
      [
        TigerBeetle::Account.new(
          id: debit_account_id,
          ledger: 1,
          code: 1
        ),
        TigerBeetle::Account.new(
          id: credit_account_id,
          ledger: 1,
          code: 1
        )
      ]
    )
    results = @client.create_transfers(
      [
        TigerBeetle::Transfer.new(
          id: TigerBeetle.id,
          debit_account_id: debit_account_id,
          credit_account_id: credit_account_id,
          amount: 100,
          ledger: 1,
          code: 1
        )
      ]
    )
    assert_equal(1, results.length)
    assert_equal(TigerBeetle::CreateTransferStatus::CREATED, results[0].status)
  end

  def test_create_transfers_returns_exists_for_a_duplicate_transfer
    debit_account_id = TigerBeetle.id
    credit_account_id = TigerBeetle.id
    @client.create_accounts(
      [
        TigerBeetle::Account.new(
          id: debit_account_id,
          ledger: 1,
          code: 1
        ),
        TigerBeetle::Account.new(
          id: credit_account_id,
          ledger: 1,
          code: 1
        )
      ]
    )
    transfer = TigerBeetle::Transfer.new(
      id: TigerBeetle.id,
      debit_account_id: debit_account_id,
      credit_account_id: credit_account_id,
      amount: 100,
      ledger: 1,
      code: 1
    )
    @client.create_transfers([transfer])
    results = @client.create_transfers([transfer])
    assert_equal(1, results.length)
    assert_equal(TigerBeetle::CreateTransferStatus::EXISTS, results[0].status)
  end

  def test_create_transfers_rejects_a_zero_id
    debit_account_id = TigerBeetle.id
    credit_account_id = TigerBeetle.id
    @client.create_accounts(
      [
        TigerBeetle::Account.new(
          id: debit_account_id,
          ledger: 1,
          code: 1
        ),
        TigerBeetle::Account.new(
          id: credit_account_id,
          ledger: 1,
          code: 1
        )
      ]
    )
    results = @client.create_transfers(
      [
        TigerBeetle::Transfer.new(
          id: 0,
          debit_account_id: debit_account_id,
          credit_account_id: credit_account_id,
          amount: 10,
          ledger: 1,
          code: 1
        )
      ]
    )
    assert_equal(1, results.length)
    assert_equal(TigerBeetle::CreateTransferStatus::ID_MUST_NOT_BE_ZERO, results[0].status)
  end

  def test_create_transfers_rejects_a_zero_debit_account_id
    credit_account_id = TigerBeetle.id
    @client.create_accounts(
      [
        TigerBeetle::Account.new(
          id: credit_account_id,
          ledger: 1,
          code: 1
        )
      ]
    )
    results = @client.create_transfers(
      [
        TigerBeetle::Transfer.new(
          id: TigerBeetle.id,
          debit_account_id: 0,
          credit_account_id: credit_account_id,
          amount: 10,
          ledger: 1,
          code: 1
        )
      ]
    )
    assert_equal(1, results.length)
    assert_equal(TigerBeetle::CreateTransferStatus::DEBIT_ACCOUNT_ID_MUST_NOT_BE_ZERO, results[0].status)
  end

  def test_create_transfers_rejects_a_zero_credit_account_id
    debit_account_id = TigerBeetle.id
    @client.create_accounts(
      [
        TigerBeetle::Account.new(
          id: debit_account_id,
          ledger: 1,
          code: 1
        )
      ]
    )
    results = @client.create_transfers(
      [
        TigerBeetle::Transfer.new(
          id: TigerBeetle.id,
          debit_account_id: debit_account_id,
          credit_account_id: 0,
          amount: 10,
          ledger: 1,
          code: 1
        )
      ]
    )
    assert_equal(1, results.length)
    assert_equal(TigerBeetle::CreateTransferStatus::CREDIT_ACCOUNT_ID_MUST_NOT_BE_ZERO, results[0].status)
  end

  def test_create_transfers_rejects_identical_debit_and_credit_accounts
    account_id = TigerBeetle.id
    @client.create_accounts(
      [
        TigerBeetle::Account.new(
          id: account_id,
          ledger: 1,
          code: 1
        )
      ]
    )
    results = @client.create_transfers(
      [
        TigerBeetle::Transfer.new(
          id: TigerBeetle.id,
          debit_account_id: account_id,
          credit_account_id: account_id,
          amount: 10,
          ledger: 1,
          code: 1
        )
      ]
    )
    assert_equal(1, results.length)
    assert_equal(TigerBeetle::CreateTransferStatus::ACCOUNTS_MUST_BE_DIFFERENT, results[0].status)
  end

  def test_create_transfers_rejects_a_zero_ledger
    debit_account_id = TigerBeetle.id
    credit_account_id = TigerBeetle.id
    @client.create_accounts(
      [
        TigerBeetle::Account.new(
          id: debit_account_id,
          ledger: 1,
          code: 1
        ),
        TigerBeetle::Account.new(
          id: credit_account_id,
          ledger: 1,
          code: 1
        )
      ]
    )
    results = @client.create_transfers(
      [
        TigerBeetle::Transfer.new(
          id: TigerBeetle.id,
          debit_account_id: debit_account_id,
          credit_account_id: credit_account_id,
          amount: 10,
          ledger: 0,
          code: 1
        )
      ]
    )
    assert_equal(1, results.length)
    assert_equal(TigerBeetle::CreateTransferStatus::LEDGER_MUST_NOT_BE_ZERO, results[0].status)
  end

  def test_create_transfers_rejects_a_zero_code
    debit_account_id = TigerBeetle.id
    credit_account_id = TigerBeetle.id
    @client.create_accounts(
      [
        TigerBeetle::Account.new(
          id: debit_account_id,
          ledger: 1,
          code: 1
        ),
        TigerBeetle::Account.new(
          id: credit_account_id,
          ledger: 1,
          code: 1
        )
      ]
    )
    results = @client.create_transfers(
      [
        TigerBeetle::Transfer.new(
          id: TigerBeetle.id,
          debit_account_id: debit_account_id,
          credit_account_id: credit_account_id,
          amount: 10,
          ledger: 1,
          code: 0
        )
      ]
    )
    assert_equal(1, results.length)
    assert_equal(TigerBeetle::CreateTransferStatus::CODE_MUST_NOT_BE_ZERO, results[0].status)
  end

  # Suite: lookup_transfers

  def test_lookup_transfers_returns_an_existing_transfer
    transfer_id = TigerBeetle.id
    debit_account_id = TigerBeetle.id
    credit_account_id = TigerBeetle.id
    @client.create_accounts(
      [
        TigerBeetle::Account.new(
          id: debit_account_id,
          ledger: 1,
          code: 1
        ),
        TigerBeetle::Account.new(
          id: credit_account_id,
          ledger: 1,
          code: 1
        )
      ]
    )
    @client.create_transfers(
      [
        TigerBeetle::Transfer.new(
          id: transfer_id,
          debit_account_id: debit_account_id,
          credit_account_id: credit_account_id,
          amount: 42,
          ledger: 1,
          code: 1
        )
      ]
    )
    transfers = @client.lookup_transfers([transfer_id])
    assert_equal(1, transfers.length)
    assert_equal(transfer_id, transfers[0].id)
    assert_equal(debit_account_id, transfers[0].debit_account_id)
    assert_equal(credit_account_id, transfers[0].credit_account_id)
    assert_equal(42, transfers[0].amount)
  end

  def test_lookup_transfers_returns_no_transfers_for_a_missing_id
    transfers = @client.lookup_transfers([TigerBeetle.id])
    assert_equal(0, transfers.length)
  end

  def test_lookup_transfers_returns_multiple_existing_transfers_in_one_batch
    transfer_1_id = TigerBeetle.id
    transfer_2_id = TigerBeetle.id
    debit_account_id = TigerBeetle.id
    credit_account_id = TigerBeetle.id
    @client.create_accounts(
      [
        TigerBeetle::Account.new(
          id: debit_account_id,
          ledger: 1,
          code: 1
        ),
        TigerBeetle::Account.new(
          id: credit_account_id,
          ledger: 1,
          code: 1
        )
      ]
    )
    @client.create_transfers(
      [
        TigerBeetle::Transfer.new(
          id: transfer_1_id,
          debit_account_id: debit_account_id,
          credit_account_id: credit_account_id,
          amount: 10,
          ledger: 1,
          code: 1
        ),
        TigerBeetle::Transfer.new(
          id: transfer_2_id,
          debit_account_id: debit_account_id,
          credit_account_id: credit_account_id,
          amount: 20,
          ledger: 1,
          code: 1
        )
      ]
    )
    transfers = @client.lookup_transfers([transfer_1_id, transfer_2_id])
    assert_equal(2, transfers.length)
    assert_equal(transfer_1_id, transfers[0].id)
    assert_equal(10, transfers[0].amount)
    assert_equal(transfer_2_id, transfers[1].id)
    assert_equal(20, transfers[1].amount)
  end

  def test_lookup_transfers_returns_only_the_existing_transfer_for_a_partial_match
    existing_id = TigerBeetle.id
    missing_id = TigerBeetle.id
    debit_account_id = TigerBeetle.id
    credit_account_id = TigerBeetle.id
    @client.create_accounts(
      [
        TigerBeetle::Account.new(
          id: debit_account_id,
          ledger: 1,
          code: 1
        ),
        TigerBeetle::Account.new(
          id: credit_account_id,
          ledger: 1,
          code: 1
        )
      ]
    )
    @client.create_transfers(
      [
        TigerBeetle::Transfer.new(
          id: existing_id,
          debit_account_id: debit_account_id,
          credit_account_id: credit_account_id,
          amount: 5,
          ledger: 1,
          code: 1
        )
      ]
    )
    transfers = @client.lookup_transfers([existing_id, missing_id])
    assert_equal(1, transfers.length)
    assert_equal(existing_id, transfers[0].id)
  end

  def test_lookup_transfers_returns_no_transfers_for_an_empty_batch
    transfers = @client.lookup_transfers([])
    assert_equal(0, transfers.length)
  end

  def test_lookup_transfers_round_trips_all_fields
    transfer_id = TigerBeetle.id
    debit_account_id = TigerBeetle.id
    credit_account_id = TigerBeetle.id
    user_data_128 = TigerBeetle.id
    @client.create_accounts(
      [
        TigerBeetle::Account.new(
          id: debit_account_id,
          ledger: 1,
          code: 1
        ),
        TigerBeetle::Account.new(
          id: credit_account_id,
          ledger: 1,
          code: 1
        )
      ]
    )
    @client.create_transfers(
      [
        TigerBeetle::Transfer.new(
          id: transfer_id,
          debit_account_id: debit_account_id,
          credit_account_id: credit_account_id,
          amount: 99,
          ledger: 1,
          code: 7,
          user_data_128: user_data_128,
          user_data_64: 8888888888,
          user_data_32: 54321
        )
      ]
    )
    transfers = @client.lookup_transfers([transfer_id])
    assert_equal(1, transfers.length)
    assert_equal(transfer_id, transfers[0].id)
    assert_equal(debit_account_id, transfers[0].debit_account_id)
    assert_equal(credit_account_id, transfers[0].credit_account_id)
    assert_equal(99, transfers[0].amount)
    assert_equal(1, transfers[0].ledger)
    assert_equal(7, transfers[0].code)
    assert_equal(user_data_128, transfers[0].user_data_128)
    assert_equal(8888888888, transfers[0].user_data_64)
    assert_equal(54321, transfers[0].user_data_32)
    transfer = transfers[0]
    assert_operator(transfer.timestamp, :>, 0)
  end

  # Suite: get_account_transfers

  def test_get_account_transfers_returns_debit_and_credit_transfers_for_an_account
    account_1_id = TigerBeetle.id
    account_2_id = TigerBeetle.id
    account_3_id = TigerBeetle.id
    debit_transfer_id = TigerBeetle.id
    credit_transfer_id = TigerBeetle.id
    @client.create_accounts(
      [
        TigerBeetle::Account.new(
          id: account_1_id,
          ledger: 1,
          code: 1
        ),
        TigerBeetle::Account.new(
          id: account_2_id,
          ledger: 1,
          code: 1
        ),
        TigerBeetle::Account.new(
          id: account_3_id,
          ledger: 1,
          code: 1
        )
      ]
    )
    @client.create_transfers(
      [
        TigerBeetle::Transfer.new(
          id: debit_transfer_id,
          debit_account_id: account_1_id,
          credit_account_id: account_2_id,
          amount: 10,
          ledger: 1,
          code: 1
        ),
        TigerBeetle::Transfer.new(
          id: credit_transfer_id,
          debit_account_id: account_3_id,
          credit_account_id: account_1_id,
          amount: 20,
          ledger: 1,
          code: 1
        )
      ]
    )
    transfers = @client.get_account_transfers(
      TigerBeetle::AccountFilter.new(
        account_id: account_1_id,
        limit: 10,
        flags: TigerBeetle::AccountFilterFlags::DEBITS |
          TigerBeetle::AccountFilterFlags::CREDITS
      )
    )
    assert_equal(2, transfers.length)
    assert_equal(debit_transfer_id, transfers[0].id)
    assert_equal(10, transfers[0].amount)
    assert_equal(credit_transfer_id, transfers[1].id)
    assert_equal(20, transfers[1].amount)
  end

  def test_get_account_transfers_returns_only_debit_transfers_with_the_debits_flag
    account_1_id = TigerBeetle.id
    account_2_id = TigerBeetle.id
    account_3_id = TigerBeetle.id
    debit_transfer_id = TigerBeetle.id
    @client.create_accounts(
      [
        TigerBeetle::Account.new(
          id: account_1_id,
          ledger: 1,
          code: 1
        ),
        TigerBeetle::Account.new(
          id: account_2_id,
          ledger: 1,
          code: 1
        ),
        TigerBeetle::Account.new(
          id: account_3_id,
          ledger: 1,
          code: 1
        )
      ]
    )
    @client.create_transfers(
      [
        TigerBeetle::Transfer.new(
          id: debit_transfer_id,
          debit_account_id: account_1_id,
          credit_account_id: account_2_id,
          amount: 10,
          ledger: 1,
          code: 1
        ),
        TigerBeetle::Transfer.new(
          id: TigerBeetle.id,
          debit_account_id: account_3_id,
          credit_account_id: account_1_id,
          amount: 20,
          ledger: 1,
          code: 1
        )
      ]
    )
    transfers = @client.get_account_transfers(
      TigerBeetle::AccountFilter.new(
        account_id: account_1_id,
        limit: 10,
        flags: TigerBeetle::AccountFilterFlags::DEBITS
      )
    )
    assert_equal(1, transfers.length)
    assert_equal(debit_transfer_id, transfers[0].id)
    assert_equal(10, transfers[0].amount)
  end

  def test_get_account_transfers_returns_only_credit_transfers_with_the_credits_flag
    account_1_id = TigerBeetle.id
    account_2_id = TigerBeetle.id
    account_3_id = TigerBeetle.id
    credit_transfer_id = TigerBeetle.id
    @client.create_accounts(
      [
        TigerBeetle::Account.new(
          id: account_1_id,
          ledger: 1,
          code: 1
        ),
        TigerBeetle::Account.new(
          id: account_2_id,
          ledger: 1,
          code: 1
        ),
        TigerBeetle::Account.new(
          id: account_3_id,
          ledger: 1,
          code: 1
        )
      ]
    )
    @client.create_transfers(
      [
        TigerBeetle::Transfer.new(
          id: TigerBeetle.id,
          debit_account_id: account_1_id,
          credit_account_id: account_2_id,
          amount: 10,
          ledger: 1,
          code: 1
        ),
        TigerBeetle::Transfer.new(
          id: credit_transfer_id,
          debit_account_id: account_3_id,
          credit_account_id: account_1_id,
          amount: 20,
          ledger: 1,
          code: 1
        )
      ]
    )
    transfers = @client.get_account_transfers(
      TigerBeetle::AccountFilter.new(
        account_id: account_1_id,
        limit: 10,
        flags: TigerBeetle::AccountFilterFlags::CREDITS
      )
    )
    assert_equal(1, transfers.length)
    assert_equal(credit_transfer_id, transfers[0].id)
    assert_equal(20, transfers[0].amount)
  end

  def test_get_account_transfers_returns_no_transfers_for_an_unused_account
    transfers = @client.get_account_transfers(
      TigerBeetle::AccountFilter.new(
        account_id: TigerBeetle.id,
        limit: 10,
        flags: TigerBeetle::AccountFilterFlags::DEBITS |
          TigerBeetle::AccountFilterFlags::CREDITS
      )
    )
    assert_equal(0, transfers.length)
  end

  # Suite: get_account_balances

  def test_get_account_balances_returns_a_balance_per_transfer_for_a_history_account
    account_1_id = TigerBeetle.id
    account_2_id = TigerBeetle.id
    @client.create_accounts(
      [
        TigerBeetle::Account.new(
          id: account_1_id,
          ledger: 1,
          code: 1,
          flags: TigerBeetle::AccountFlags::HISTORY
        ),
        TigerBeetle::Account.new(
          id: account_2_id,
          ledger: 1,
          code: 1
        )
      ]
    )
    @client.create_transfers(
      [
        TigerBeetle::Transfer.new(
          id: TigerBeetle.id,
          debit_account_id: account_1_id,
          credit_account_id: account_2_id,
          amount: 10,
          ledger: 1,
          code: 1
        ),
        TigerBeetle::Transfer.new(
          id: TigerBeetle.id,
          debit_account_id: account_2_id,
          credit_account_id: account_1_id,
          amount: 20,
          ledger: 1,
          code: 1
        )
      ]
    )
    balances = @client.get_account_balances(
      TigerBeetle::AccountFilter.new(
        account_id: account_1_id,
        limit: 10,
        flags: TigerBeetle::AccountFilterFlags::DEBITS |
          TigerBeetle::AccountFilterFlags::CREDITS
      )
    )
    assert_equal(2, balances.length)
    assert_equal(10, balances[0].debits_posted)
    assert_equal(0, balances[0].credits_posted)
    assert_equal(10, balances[1].debits_posted)
    assert_equal(20, balances[1].credits_posted)
  end

  def test_get_account_balances_returns_no_balances_without_the_history_flag
    account_1_id = TigerBeetle.id
    account_2_id = TigerBeetle.id
    @client.create_accounts(
      [
        TigerBeetle::Account.new(
          id: account_1_id,
          ledger: 1,
          code: 1
        ),
        TigerBeetle::Account.new(
          id: account_2_id,
          ledger: 1,
          code: 1
        )
      ]
    )
    @client.create_transfers(
      [
        TigerBeetle::Transfer.new(
          id: TigerBeetle.id,
          debit_account_id: account_1_id,
          credit_account_id: account_2_id,
          amount: 10,
          ledger: 1,
          code: 1
        )
      ]
    )
    balances = @client.get_account_balances(
      TigerBeetle::AccountFilter.new(
        account_id: account_1_id,
        limit: 10,
        flags: TigerBeetle::AccountFilterFlags::DEBITS |
          TigerBeetle::AccountFilterFlags::CREDITS
      )
    )
    assert_equal(0, balances.length)
  end

  # Suite: query_accounts

  def test_query_accounts_returns_accounts_matching_user_data
    account_1_id = TigerBeetle.id
    account_2_id = TigerBeetle.id
    user_data = TigerBeetle.id
    @client.create_accounts(
      [
        TigerBeetle::Account.new(
          id: account_1_id,
          user_data_128: user_data,
          ledger: 1,
          code: 1
        ),
        TigerBeetle::Account.new(
          id: account_2_id,
          user_data_128: user_data,
          ledger: 1,
          code: 1
        ),
        TigerBeetle::Account.new(
          id: TigerBeetle.id,
          user_data_128: TigerBeetle.id,
          ledger: 1,
          code: 1
        )
      ]
    )
    accounts = @client.query_accounts(
      TigerBeetle::QueryFilter.new(
        user_data_128: user_data,
        limit: 10
      )
    )
    assert_equal(2, accounts.length)
    assert_equal(account_1_id, accounts[0].id)
    assert_equal(user_data, accounts[0].user_data_128)
    assert_equal(account_2_id, accounts[1].id)
    assert_equal(user_data, accounts[1].user_data_128)
  end

  def test_query_accounts_returns_accounts_in_reverse_order_with_the_reversed_flag
    account_1_id = TigerBeetle.id
    account_2_id = TigerBeetle.id
    user_data = TigerBeetle.id
    @client.create_accounts(
      [
        TigerBeetle::Account.new(
          id: account_1_id,
          user_data_128: user_data,
          ledger: 1,
          code: 1
        ),
        TigerBeetle::Account.new(
          id: account_2_id,
          user_data_128: user_data,
          ledger: 1,
          code: 1
        )
      ]
    )
    accounts = @client.query_accounts(
      TigerBeetle::QueryFilter.new(
        user_data_128: user_data,
        limit: 10,
        flags: TigerBeetle::QueryFilterFlags::REVERSED
      )
    )
    assert_equal(2, accounts.length)
    assert_equal(account_2_id, accounts[0].id)
    assert_equal(account_1_id, accounts[1].id)
  end

  def test_query_accounts_returns_accounts_matching_ledger_and_code
    account_id = TigerBeetle.id
    user_data = TigerBeetle.id
    @client.create_accounts(
      [
        TigerBeetle::Account.new(
          id: account_id,
          user_data_128: user_data,
          ledger: 7,
          code: 42
        ),
        TigerBeetle::Account.new(
          id: TigerBeetle.id,
          user_data_128: user_data,
          ledger: 7,
          code: 43
        ),
        TigerBeetle::Account.new(
          id: TigerBeetle.id,
          user_data_128: user_data,
          ledger: 8,
          code: 42
        )
      ]
    )
    accounts = @client.query_accounts(
      TigerBeetle::QueryFilter.new(
        user_data_128: user_data,
        ledger: 7,
        code: 42,
        limit: 10
      )
    )
    assert_equal(1, accounts.length)
    assert_equal(account_id, accounts[0].id)
    assert_equal(7, accounts[0].ledger)
    assert_equal(42, accounts[0].code)
  end

  def test_query_accounts_returns_no_accounts_for_unused_user_data
    accounts = @client.query_accounts(
      TigerBeetle::QueryFilter.new(
        user_data_128: TigerBeetle.id,
        limit: 10
      )
    )
    assert_equal(0, accounts.length)
  end

  # Suite: query_transfers

  def test_query_transfers_returns_transfers_matching_user_data
    debit_account_id = TigerBeetle.id
    credit_account_id = TigerBeetle.id
    transfer_1_id = TigerBeetle.id
    transfer_2_id = TigerBeetle.id
    user_data = TigerBeetle.id
    @client.create_accounts(
      [
        TigerBeetle::Account.new(
          id: debit_account_id,
          ledger: 1,
          code: 1
        ),
        TigerBeetle::Account.new(
          id: credit_account_id,
          ledger: 1,
          code: 1
        )
      ]
    )
    @client.create_transfers(
      [
        TigerBeetle::Transfer.new(
          id: transfer_1_id,
          debit_account_id: debit_account_id,
          credit_account_id: credit_account_id,
          amount: 10,
          user_data_128: user_data,
          ledger: 1,
          code: 1
        ),
        TigerBeetle::Transfer.new(
          id: transfer_2_id,
          debit_account_id: debit_account_id,
          credit_account_id: credit_account_id,
          amount: 20,
          user_data_128: user_data,
          ledger: 1,
          code: 1
        ),
        TigerBeetle::Transfer.new(
          id: TigerBeetle.id,
          debit_account_id: debit_account_id,
          credit_account_id: credit_account_id,
          amount: 30,
          user_data_128: TigerBeetle.id,
          ledger: 1,
          code: 1
        )
      ]
    )
    transfers = @client.query_transfers(
      TigerBeetle::QueryFilter.new(
        user_data_128: user_data,
        limit: 10
      )
    )
    assert_equal(2, transfers.length)
    assert_equal(transfer_1_id, transfers[0].id)
    assert_equal(10, transfers[0].amount)
    assert_equal(user_data, transfers[0].user_data_128)
    assert_equal(transfer_2_id, transfers[1].id)
    assert_equal(20, transfers[1].amount)
    assert_equal(user_data, transfers[1].user_data_128)
  end

  def test_query_transfers_returns_transfers_in_reverse_order_with_the_reversed_flag
    debit_account_id = TigerBeetle.id
    credit_account_id = TigerBeetle.id
    transfer_1_id = TigerBeetle.id
    transfer_2_id = TigerBeetle.id
    user_data = TigerBeetle.id
    @client.create_accounts(
      [
        TigerBeetle::Account.new(
          id: debit_account_id,
          ledger: 1,
          code: 1
        ),
        TigerBeetle::Account.new(
          id: credit_account_id,
          ledger: 1,
          code: 1
        )
      ]
    )
    @client.create_transfers(
      [
        TigerBeetle::Transfer.new(
          id: transfer_1_id,
          debit_account_id: debit_account_id,
          credit_account_id: credit_account_id,
          amount: 10,
          user_data_128: user_data,
          ledger: 1,
          code: 1
        ),
        TigerBeetle::Transfer.new(
          id: transfer_2_id,
          debit_account_id: debit_account_id,
          credit_account_id: credit_account_id,
          amount: 20,
          user_data_128: user_data,
          ledger: 1,
          code: 1
        )
      ]
    )
    transfers = @client.query_transfers(
      TigerBeetle::QueryFilter.new(
        user_data_128: user_data,
        limit: 10,
        flags: TigerBeetle::QueryFilterFlags::REVERSED
      )
    )
    assert_equal(2, transfers.length)
    assert_equal(transfer_2_id, transfers[0].id)
    assert_equal(20, transfers[0].amount)
    assert_equal(transfer_1_id, transfers[1].id)
    assert_equal(10, transfers[1].amount)
  end

  def test_query_transfers_returns_transfers_matching_ledger_and_code
    transfer_id = TigerBeetle.id
    user_data = TigerBeetle.id
    ledger_7_debit_id = TigerBeetle.id
    ledger_7_credit_id = TigerBeetle.id
    ledger_8_debit_id = TigerBeetle.id
    ledger_8_credit_id = TigerBeetle.id
    @client.create_accounts(
      [
        TigerBeetle::Account.new(
          id: ledger_7_debit_id,
          ledger: 7,
          code: 1
        ),
        TigerBeetle::Account.new(
          id: ledger_7_credit_id,
          ledger: 7,
          code: 1
        ),
        TigerBeetle::Account.new(
          id: ledger_8_debit_id,
          ledger: 8,
          code: 1
        ),
        TigerBeetle::Account.new(
          id: ledger_8_credit_id,
          ledger: 8,
          code: 1
        )
      ]
    )
    @client.create_transfers(
      [
        TigerBeetle::Transfer.new(
          id: transfer_id,
          debit_account_id: ledger_7_debit_id,
          credit_account_id: ledger_7_credit_id,
          amount: 10,
          user_data_128: user_data,
          ledger: 7,
          code: 42
        ),
        TigerBeetle::Transfer.new(
          id: TigerBeetle.id,
          debit_account_id: ledger_7_debit_id,
          credit_account_id: ledger_7_credit_id,
          amount: 20,
          user_data_128: user_data,
          ledger: 7,
          code: 43
        ),
        TigerBeetle::Transfer.new(
          id: TigerBeetle.id,
          debit_account_id: ledger_8_debit_id,
          credit_account_id: ledger_8_credit_id,
          amount: 30,
          user_data_128: user_data,
          ledger: 8,
          code: 42
        )
      ]
    )
    transfers = @client.query_transfers(
      TigerBeetle::QueryFilter.new(
        user_data_128: user_data,
        ledger: 7,
        code: 42,
        limit: 10
      )
    )
    assert_equal(1, transfers.length)
    assert_equal(transfer_id, transfers[0].id)
    assert_equal(7, transfers[0].ledger)
    assert_equal(42, transfers[0].code)
  end

  def test_query_transfers_fails_when_the_limit_is_too_large
    assert_raises(StandardError) do
      @client.query_transfers(
        TigerBeetle::QueryFilter.new(
          limit: 10000
        )
      )
    end
  end

  def test_query_transfers_returns_no_transfers_for_unused_user_data
    transfers = @client.query_transfers(
      TigerBeetle::QueryFilter.new(
        user_data_128: TigerBeetle.id,
        limit: 10
      )
    )
    assert_equal(0, transfers.length)
  end

  # Suite: two_phase_transfer

  def test_two_phase_transfer_creates_posts_voids_and_expires_two_phase_transfers
    account_a_id = TigerBeetle.id
    account_b_id = TigerBeetle.id
    account_results_1 = @client.create_accounts(
      [
        TigerBeetle::Account.new(
          id: account_a_id,
          ledger: 1,
          code: 718
        )
      ]
    )
    account_result_1 = account_results_1[0]
    assert_equal(TigerBeetle::CreateAccountStatus::CREATED, account_result_1.status)
    assert_operator(account_result_1.timestamp, :>, 0)
    account_results_2 = @client.create_accounts(
      [
        TigerBeetle::Account.new(
          id: account_a_id,
          ledger: 1,
          code: 718
        ),
        TigerBeetle::Account.new(
          id: account_b_id,
          ledger: 1,
          code: 719
        )
      ]
    )
    account_result_2 = account_results_2[0]
    account_result_3 = account_results_2[1]
    assert_equal(TigerBeetle::CreateAccountStatus::EXISTS, account_result_2.status)
    assert_operator(account_result_2.timestamp, :>, 0)
    assert_equal(TigerBeetle::CreateAccountStatus::CREATED, account_result_3.status)
    assert_operator(account_result_3.timestamp, :>, 0)
    transfer_results_1 = @client.create_transfers(
      [
        TigerBeetle::Transfer.new(
          id: TigerBeetle.id,
          debit_account_id: account_b_id,
          credit_account_id: account_a_id,
          amount: 100,
          ledger: 1,
          code: 1
        )
      ]
    )
    transfer_result_1 = transfer_results_1[0]
    assert_equal(TigerBeetle::CreateTransferStatus::CREATED, transfer_result_1.status)
    assert_operator(transfer_result_1.timestamp, :>, 0)
    accounts_1 = @client.lookup_accounts([account_a_id, account_b_id])
    assert_equal(2, accounts_1.length)
    assert_equal(account_a_id, accounts_1[0].id)
    assert_equal(100, accounts_1[0].credits_posted)
    assert_equal(0, accounts_1[0].credits_pending)
    assert_equal(0, accounts_1[0].debits_posted)
    assert_equal(0, accounts_1[0].debits_pending)
    assert_equal(account_b_id, accounts_1[1].id)
    assert_equal(0, accounts_1[1].credits_posted)
    assert_equal(0, accounts_1[1].credits_pending)
    assert_equal(100, accounts_1[1].debits_posted)
    assert_equal(0, accounts_1[1].debits_pending)
    transfer_2_id = TigerBeetle.id
    transfer_results_2 = @client.create_transfers(
      [
        TigerBeetle::Transfer.new(
          id: transfer_2_id,
          debit_account_id: account_b_id,
          credit_account_id: account_a_id,
          amount: 50,
          timeout: 2_000_000_000,
          ledger: 1,
          code: 1,
          flags: TigerBeetle::TransferFlags::PENDING
        )
      ]
    )
    transfer_result_2 = transfer_results_2[0]
    assert_equal(TigerBeetle::CreateTransferStatus::CREATED, transfer_result_2.status)
    assert_operator(transfer_result_2.timestamp, :>, 0)
    accounts_2 = @client.lookup_accounts([account_a_id, account_b_id])
    assert_equal(2, accounts_2.length)
    assert_equal(account_a_id, accounts_2[0].id)
    assert_equal(100, accounts_2[0].credits_posted)
    assert_equal(50, accounts_2[0].credits_pending)
    assert_equal(0, accounts_2[0].debits_posted)
    assert_equal(0, accounts_2[0].debits_pending)
    assert_equal(account_b_id, accounts_2[1].id)
    assert_equal(0, accounts_2[1].credits_posted)
    assert_equal(0, accounts_2[1].credits_pending)
    assert_equal(100, accounts_2[1].debits_posted)
    assert_equal(50, accounts_2[1].debits_pending)
    transfers_1 = @client.lookup_transfers([transfer_2_id])
    transfer_lookup_1 = transfers_1[0]
    assert_equal(1, transfers_1.length)
    assert_equal(transfer_2_id, transfers_1[0].id)
    assert_equal(account_b_id, transfers_1[0].debit_account_id)
    assert_equal(account_a_id, transfers_1[0].credit_account_id)
    assert_equal(50, transfers_1[0].amount)
    assert_equal(0, transfers_1[0].user_data_128)
    assert_equal(0, transfers_1[0].user_data_64)
    assert_equal(0, transfers_1[0].user_data_32)
    assert_equal(1, transfers_1[0].code)
    assert_equal(TigerBeetle::TransferFlags::PENDING, transfers_1[0].flags)
    assert_operator(transfer_lookup_1.timeout, :>, 0)
    commit_results = @client.create_transfers(
      [
        TigerBeetle::Transfer.new(
          id: TigerBeetle.id,
          amount: 340282366920938463463374607431768211455,
          pending_id: transfer_2_id,
          ledger: 1,
          code: 1,
          flags: TigerBeetle::TransferFlags::POST_PENDING_TRANSFER
        )
      ]
    )
    commit_result = commit_results[0]
    assert_equal(TigerBeetle::CreateTransferStatus::CREATED, commit_result.status)
    assert_operator(commit_result.timestamp, :>, 0)
    accounts_3 = @client.lookup_accounts([account_a_id, account_b_id])
    assert_equal(2, accounts_3.length)
    assert_equal(account_a_id, accounts_3[0].id)
    assert_equal(150, accounts_3[0].credits_posted)
    assert_equal(0, accounts_3[0].credits_pending)
    assert_equal(0, accounts_3[0].debits_posted)
    assert_equal(0, accounts_3[0].debits_pending)
    assert_equal(account_b_id, accounts_3[1].id)
    assert_equal(0, accounts_3[1].credits_posted)
    assert_equal(0, accounts_3[1].credits_pending)
    assert_equal(150, accounts_3[1].debits_posted)
    assert_equal(0, accounts_3[1].debits_pending)
    transfer_3_id = TigerBeetle.id
    transfer_results_3 = @client.create_transfers(
      [
        TigerBeetle::Transfer.new(
          id: transfer_3_id,
          debit_account_id: account_b_id,
          credit_account_id: account_a_id,
          amount: 50,
          timeout: 1_000_000_000,
          ledger: 1,
          code: 1,
          flags: TigerBeetle::TransferFlags::PENDING
        )
      ]
    )
    transfer_result_3 = transfer_results_3[0]
    assert_equal(TigerBeetle::CreateTransferStatus::CREATED, transfer_result_3.status)
    assert_operator(transfer_result_3.timestamp, :>, 0)
    reject_results = @client.create_transfers(
      [
        TigerBeetle::Transfer.new(
          id: TigerBeetle.id,
          pending_id: transfer_3_id,
          ledger: 1,
          code: 1,
          flags: TigerBeetle::TransferFlags::VOID_PENDING_TRANSFER
        )
      ]
    )
    reject_result = reject_results[0]
    assert_equal(TigerBeetle::CreateTransferStatus::CREATED, reject_result.status)
    assert_operator(reject_result.timestamp, :>, 0)
    accounts_4 = @client.lookup_accounts([account_a_id, account_b_id])
    assert_equal(2, accounts_4.length)
    assert_equal(account_a_id, accounts_4[0].id)
    assert_equal(150, accounts_4[0].credits_posted)
    assert_equal(0, accounts_4[0].credits_pending)
    assert_equal(0, accounts_4[0].debits_posted)
    assert_equal(0, accounts_4[0].debits_pending)
    assert_equal(account_b_id, accounts_4[1].id)
    assert_equal(0, accounts_4[1].credits_posted)
    assert_equal(0, accounts_4[1].credits_pending)
    assert_equal(150, accounts_4[1].debits_posted)
    assert_equal(0, accounts_4[1].debits_pending)
    transfer_4_id = TigerBeetle.id
    transfer_results_4 = @client.create_transfers(
      [
        TigerBeetle::Transfer.new(
          id: transfer_4_id,
          debit_account_id: account_b_id,
          credit_account_id: account_a_id,
          amount: 50,
          timeout: 1,
          ledger: 1,
          code: 1,
          flags: TigerBeetle::TransferFlags::PENDING
        )
      ]
    )
    transfer_result_4 = transfer_results_4[0]
    assert_equal(TigerBeetle::CreateTransferStatus::CREATED, transfer_result_4.status)
    assert_operator(transfer_result_4.timestamp, :>, 0)
    accounts_5 = @client.lookup_accounts([account_a_id, account_b_id])
    assert_equal(2, accounts_5.length)
    assert_equal(account_a_id, accounts_5[0].id)
    assert_equal(150, accounts_5[0].credits_posted)
    assert_equal(50, accounts_5[0].credits_pending)
    assert_equal(0, accounts_5[0].debits_posted)
    assert_equal(0, accounts_5[0].debits_pending)
    assert_equal(account_b_id, accounts_5[1].id)
    assert_equal(0, accounts_5[1].credits_posted)
    assert_equal(0, accounts_5[1].credits_pending)
    assert_equal(150, accounts_5[1].debits_posted)
    assert_equal(50, accounts_5[1].debits_pending)
    sleep(1500 / 1000.0)
    accounts_6 = @client.lookup_accounts([account_a_id, account_b_id])
    assert_equal(2, accounts_6.length)
    assert_equal(account_a_id, accounts_6[0].id)
    assert_equal(150, accounts_6[0].credits_posted)
    assert_equal(0, accounts_6[0].credits_pending)
    assert_equal(0, accounts_6[0].debits_posted)
    assert_equal(0, accounts_6[0].debits_pending)
    assert_equal(account_b_id, accounts_6[1].id)
    assert_equal(0, accounts_6[1].credits_posted)
    assert_equal(0, accounts_6[1].credits_pending)
    assert_equal(150, accounts_6[1].debits_posted)
    assert_equal(0, accounts_6[1].debits_pending)
    expired_results = @client.create_transfers(
      [
        TigerBeetle::Transfer.new(
          id: TigerBeetle.id,
          pending_id: transfer_4_id,
          ledger: 1,
          code: 1,
          flags: TigerBeetle::TransferFlags::VOID_PENDING_TRANSFER
        )
      ]
    )
    expired_result = expired_results[0]
    assert_equal(TigerBeetle::CreateTransferStatus::PENDING_TRANSFER_EXPIRED, expired_result.status)
  end

  # Suite: uint128_range

  def test_uint128_range_accepts_the_maximum_u128
    uint128_max = 340282366920938463463374607431768211455
    accounts = @client.lookup_accounts([uint128_max])
    assert_equal(0, accounts.length)
  end

  def test_uint128_range_rejects_a_u128_above_the_maximum
    assert_raises(StandardError) do
      @client.lookup_accounts([340282366920938463463374607431768211456])
    end
  end

  def test_uint128_range_rejects_a_negative_u128
    assert_raises(StandardError) do
      @client.lookup_accounts([-1])
    end
  end

  # Suite: create_transfers_concurrent

  def test_create_transfers_concurrent_applies_transfers_submitted_concurrently
    debit_account_id = TigerBeetle.id
    credit_account_id = TigerBeetle.id
    @client.create_accounts(
      [
        TigerBeetle::Account.new(
          id: debit_account_id,
          ledger: 1,
          code: 1
        ),
        TigerBeetle::Account.new(
          id: credit_account_id,
          ledger: 1,
          code: 1
        )
      ]
    )
    threads = Array.new(100) do
      Thread.new do
        @client.create_transfers(
          [
            TigerBeetle::Transfer.new(
              id: TigerBeetle.id,
              debit_account_id: debit_account_id,
              credit_account_id: credit_account_id,
              amount: 10,
              ledger: 1,
              code: 1
            )
          ]
        )
      end
    end
    threads.each(&:join)
    accounts = @client.lookup_accounts([debit_account_id, credit_account_id])
    assert_equal(2, accounts.length)
    assert_equal(debit_account_id, accounts[0].id)
    assert_equal(1000, accounts[0].debits_posted)
    assert_equal(0, accounts[0].credits_posted)
    assert_equal(credit_account_id, accounts[1].id)
    assert_equal(0, accounts[1].debits_posted)
    assert_equal(1000, accounts[1].credits_posted)
  end

  # Suite: close_client

  def test_close_client_fails_operations_after_close
    @client.close
    assert_raises(StandardError) do
      @client.lookup_accounts([TigerBeetle.id])
    end
  end
end
