const std = @import("std");
const assert = std.debug.assert;

const conformance = @import("conformance");

const ast = conformance.ast;
const Formatter = conformance.Formatter;

pub fn main() !void {
    const formatter = Formatter.init(conformance.allocator(), .{
        .indent_width = 2,
    });

    const tests = try conformance.parse(formatter.arena);

    var stdout = std.io.bufferedWriter(std.io.getStdOut().writer());
    try emit(formatter, stdout.writer().any(), tests);
    try stdout.flush();
}

fn satisfies(requirement: ast.Case.Requirement) bool {
    return switch (requirement) {
        // Ruby's Integer is arbitrary precision.
        .requires_unbounded_integers => true,
    };
}

fn emit(formatter: Formatter, writer: std.io.AnyWriter, tests: ast.ConformanceTests) !void {
    try writer.writeAll(
        \\###########################################################
        \\## This file was auto-generated by ruby_conformance.zig ##
        \\##               Do not manually modify.                ##
        \\###########################################################
        \\
        \\require "minitest/autorun"
        \\require "tigerbeetle"
        \\
        \\class TestConformance < Minitest::Test
        \\  def setup
        \\    @tb_address = ENV.fetch("TB_ADDRESS", "3000")
        \\    @client = TigerBeetle::Client.new(cluster_id: 0, replica_addresses: @tb_address)
        \\  end
        \\
        \\  def teardown
        \\    @client.close if @client && !@client.closed?
        \\  end
        \\
    );
    for (tests.suites) |suite| {
        try writer.writeAll("\n");
        try formatter.write_indent(writer, .{});
        try writer.print("# Suite: {s}\n", .{suite.name});
        for (suite.cases) |case| {
            try writer.writeAll("\n");
            if (case.requirement) |requirement| assert(satisfies(requirement));
            try formatter.write_indent(writer, .{});
            try writer.print("def test_{s}_{s}\n", .{
                suite.name,
                try formatter.to_case(.snake_case, case.description),
            });
            for (case.steps) |step| try emit_step(formatter, writer, step);
            try formatter.write_indent(writer, .{});
            try writer.writeAll("end\n");
        }
    }
    try writer.writeAll("end\n");
}

fn emit_step(formatter: Formatter, writer: std.io.AnyWriter, step: ast.Step) !void {
    switch (step) {
        .binding => |binding| try emit_binding(formatter, writer, binding),
        .call => |call| try emit_call(formatter, writer, call, .{}),
        .assertion => |assertion| try emit_assertion(formatter, writer, assertion),
    }
}

fn emit_binding(formatter: Formatter, writer: std.io.AnyWriter, binding: ast.Binding) !void {
    switch (binding.value) {
        .generate_id, .generate_ids, .index => {
            try emit_binding_value(formatter, writer, binding.name, binding.value);
        },
        .record => |record| switch (record.type) {
            .U128, .AccountFlags, .AccountFilterFlags, .QueryFilterFlags, .TransferFlags => {
                try emit_binding_value(formatter, writer, binding.name, binding.value);
            },
            .Account,
            .AccountBalance,
            .AccountFilter,
            .CreateAccountResult,
            .CreateTransferResult,
            .QueryFilter,
            .Transfer,
            => {
                const prefix = try std.fmt.allocPrint(formatter.arena, "{s} = ", .{binding.name});
                try emit_record(formatter, writer, record, .{
                    .indent_level = formatter.statement_level,
                    .prefix = prefix,
                });
            },
        },
        .call => |call| {
            const prefix = try std.fmt.allocPrint(formatter.arena, "{s} = ", .{binding.name});
            try emit_call(formatter, writer, call, .{ .prefix = prefix });
        },
        .integer, .boolean, .enum_literal, .reference => unreachable,
    }
}

fn emit_binding_value(
    formatter: Formatter,
    writer: std.io.AnyWriter,
    name: []const u8,
    value: ast.Expression,
) !void {
    const rendered = try render_expression(formatter, value);
    try formatter.write_indent(writer, .{ .level = formatter.statement_level });
    try writer.print("{s} = {s}\n", .{ name, rendered });
}

fn emit_call(
    formatter: Formatter,
    writer: std.io.AnyWriter,
    call: ast.Call,
    options: struct {
        prefix: []const u8 = "",
    },
) !void {
    if (call.concurrency > 1) {
        assert(options.prefix.len == 0);
        try formatter.write_indent(writer, .{ .level = formatter.statement_level });
        try writer.print("threads = Array.new({d}) do\n", .{call.concurrency});
        try formatter.write_indent(writer, .{ .level = 3 });
        try writer.writeAll("Thread.new do\n");
        try emit_operation(formatter, writer, call, .{ .indent_level = 4 });
        try formatter.write_indent(writer, .{ .level = 3 });
        try writer.writeAll("end\n");
        try formatter.write_indent(writer, .{ .level = formatter.statement_level });
        try writer.writeAll("end\n");
        try formatter.write_indent(writer, .{ .level = formatter.statement_level });
        try writer.writeAll("threads.each(&:join)\n");
    } else {
        try emit_operation(formatter, writer, call, .{
            .indent_level = formatter.statement_level,
            .prefix = options.prefix,
        });
    }
}

fn emit_operation(
    formatter: Formatter,
    writer: std.io.AnyWriter,
    call: ast.Call,
    options: struct {
        indent_level: u32,
        prefix: []const u8 = "",
    },
) !void {
    switch (call.name) {
        .close_client => {
            assert(options.prefix.len == 0);
            try formatter.write_indent(writer, .{ .level = options.indent_level });
            try writer.print("{s}@client.close\n", .{options.prefix});
        },
        .sleep_ms => {
            assert(options.prefix.len == 0);
            assert(call.arguments.len == 1);
            const ms = try render_expression(formatter, call.arguments[0]);
            try formatter.write_indent(writer, .{ .level = options.indent_level });
            try writer.print("{s}sleep({s} / 1000.0)\n", .{ options.prefix, ms });
        },
        .create_accounts, .create_transfers, .lookup_accounts, .lookup_transfers => {
            if (!arguments_contain_record(call)) {
                const inline_call = try render_call(formatter, call);
                try formatter.write_indent(writer, .{ .level = options.indent_level });
                try writer.print("{s}{s}\n", .{ options.prefix, inline_call });
                return;
            }
            try formatter.write_indent(writer, .{ .level = options.indent_level });
            try writer.print("{s}@client.{s}(\n", .{ options.prefix, @tagName(call.name) });
            try formatter.write_indent(writer, .{ .level = options.indent_level + 1 });
            try writer.writeAll("[\n");
            for (call.arguments, 0..) |argument, index| {
                const suffix = if (index < call.arguments.len - 1) "," else "";
                switch (argument) {
                    .record => |record| {
                        try emit_record(formatter, writer, record, .{
                            .indent_level = options.indent_level + 2,
                            .suffix = suffix,
                        });
                    },
                    else => {
                        const text = try render_expression(formatter, argument);
                        try formatter.write_indent(writer, .{ .level = options.indent_level + 2 });
                        try writer.print("{s}{s}\n", .{ text, suffix });
                    },
                }
            }
            try formatter.write_indent(writer, .{ .level = options.indent_level + 1 });
            try writer.writeAll("]\n");
            try formatter.write_indent(writer, .{ .level = options.indent_level });
            try writer.writeAll(")\n");
        },
        .get_account_transfers, .get_account_balances, .query_accounts, .query_transfers => {
            assert(call.arguments.len == 1);
            try formatter.write_indent(writer, .{ .level = options.indent_level });
            try writer.print("{s}@client.{s}(\n", .{ options.prefix, @tagName(call.name) });
            try emit_record(formatter, writer, call.arguments[0].record, .{
                .indent_level = options.indent_level + 1,
            });
            try formatter.write_indent(writer, .{ .level = options.indent_level });
            try writer.writeAll(")\n");
        },
    }
}

fn emit_record(
    formatter: Formatter,
    writer: std.io.AnyWriter,
    record: ast.Record,
    options: struct {
        indent_level: u32,
        prefix: []const u8 = "",
        suffix: []const u8 = "",
    },
) !void {
    try formatter.write_indent(writer, .{ .level = options.indent_level });
    try writer.print("{s}TigerBeetle::{s}.new(\n", .{ options.prefix, @tagName(record.type) });
    for (record.fields, 0..) |field, index| {
        const value = try render_field_value(formatter, field, options.indent_level + 2);
        try formatter.write_indent(writer, .{ .level = options.indent_level + 1 });
        try writer.print("{s}: {s}", .{ field.name, value });
        if (index < record.fields.len - 1) try writer.writeAll(",");
        try writer.writeAll("\n");
    }
    try formatter.write_indent(writer, .{ .level = options.indent_level });
    try writer.print("){s}\n", .{options.suffix});
}

fn emit_assertion(
    formatter: Formatter,
    writer: std.io.AnyWriter,
    assertion: ast.Assertion,
) !void {
    switch (assertion) {
        .equal => |equal| {
            try formatter.write_indent(writer, .{ .level = formatter.statement_level });
            try writer.print("assert_equal({d}, {s}.length)\n", .{
                equal.expected.len, equal.actual,
            });
            for (equal.expected, 0..) |record, index| {
                for (record.fields) |field| {
                    const value = try render_field_value(
                        formatter,
                        field,
                        formatter.statement_level + 1,
                    );
                    try formatter.write_indent(writer, .{ .level = formatter.statement_level });
                    try writer.print("assert_equal({s}, {s}[{d}].{s})\n", .{
                        value, equal.actual, index, field.name,
                    });
                }
            }
        },
        .empty => |actual| {
            try formatter.write_indent(writer, .{ .level = formatter.statement_level });
            try writer.print("assert_equal(0, {s}.length)\n", .{actual});
        },
        .unique => |ids| {
            try formatter.write_indent(writer, .{ .level = formatter.statement_level });
            try writer.print("assert_equal({s}.length, {s}.uniq.length)\n", .{ ids, ids });
        },
        .ascending => |ids| {
            try formatter.write_indent(writer, .{ .level = formatter.statement_level });
            try writer.print("{s}.each_cons(2) {{ |a, b| assert_operator(a, :<, b) }}\n", .{ids});
        },
        .equal_field => |comparison| {
            const actual = try render_field_reference(formatter, comparison);
            const value = try render_field_value(
                formatter,
                comparison.field,
                formatter.statement_level + 1,
            );
            try formatter.write_indent(writer, .{ .level = formatter.statement_level });
            try writer.print("assert_equal({s}, {s})\n", .{ value, actual });
        },
        .greater_than => |comparison| {
            const actual = try render_field_reference(formatter, comparison);
            const value = try render_expression(formatter, comparison.field.value);
            try formatter.write_indent(writer, .{ .level = formatter.statement_level });
            try writer.print("assert_operator({s}, :>, {s})\n", .{ actual, value });
        },
        .fail => |call| {
            try formatter.write_indent(writer, .{ .level = formatter.statement_level });
            try writer.writeAll("assert_raises(StandardError) do\n");
            try emit_operation(formatter, writer, call, .{
                .indent_level = formatter.statement_level + 1,
            });
            try formatter.write_indent(writer, .{ .level = formatter.statement_level });
            try writer.writeAll("end\n");
        },
    }
}

fn render_field_reference(
    formatter: Formatter,
    comparison: ast.Assertion.FieldComparison,
) ![]const u8 {
    return std.fmt.allocPrint(formatter.arena, "{s}.{s}", .{
        comparison.reference, comparison.field.name,
    });
}

fn arguments_contain_record(call: ast.Call) bool {
    for (call.arguments) |argument| {
        if (argument == .record) return true;
    }
    return false;
}

fn render_call(formatter: Formatter, call: ast.Call) ![]const u8 {
    assert(!arguments_contain_record(call));
    switch (call.name) {
        .create_accounts, .create_transfers, .lookup_accounts, .lookup_transfers => {
            var text = std.ArrayList(u8).init(formatter.arena);
            try text.writer().print("@client.{s}([", .{@tagName(call.name)});
            for (call.arguments, 0..) |argument, index| {
                if (index > 0) try text.appendSlice(", ");
                try text.appendSlice(try render_expression(formatter, argument));
            }
            try text.appendSlice("])");
            return text.items;
        },
        // emit_operation handles the rest of Call.Name directly: close_client and sleep_ms have
        // their own single-line forms, filter operations always take a record literal emitted
        // multiline. None of them ever reach this compact batch-op form.
        .close_client,
        .sleep_ms,
        .get_account_transfers,
        .get_account_balances,
        .query_accounts,
        .query_transfers,
        => unreachable,
    }
}

fn render_expression(
    formatter: Formatter,
    expression: ast.Expression,
) std.mem.Allocator.Error![]const u8 {
    switch (expression) {
        .generate_id => return "TigerBeetle.id",
        .generate_ids => |count| {
            return std.fmt.allocPrint(
                formatter.arena,
                "Array.new({d}) {{ TigerBeetle.id }}",
                .{count},
            );
        },
        .call => unreachable, // Calls are emitted by emit_call/emit_operation.
        .record => |record| switch (record.type) {
            .U128 => {
                assert(record.fields.len == 1);
                return render_expression(formatter, record.fields[0].value);
            },
            // Flags can't be bound on their own for now (parser-rejected).
            else => unreachable,
        },
        .integer => |text| return text,
        .boolean => |value| return if (value) "true" else "false",
        .enum_literal => unreachable, // Only valid as a record field, rendered there.
        .reference => |name| return name,
        .index => |index| {
            return std.fmt.allocPrint(formatter.arena, "{s}[{d}]", .{
                index.reference,
                index.index,
            });
        },
    }
}

fn render_flags(
    formatter: Formatter,
    record: ast.Record,
    continuation_indent_level: u32,
) ![]const u8 {
    var text = std.ArrayList(u8).init(formatter.arena);
    for (record.fields, 0..) |field, index| {
        assert(field.value == .boolean and field.value.boolean);
        if (index > 0) {
            try text.appendSlice(" |\n");
            try text.writer().writeByteNTimes(' ', continuation_indent_level * formatter.indent_width);
        }
        try text.writer().print("TigerBeetle::{s}::{s}", .{
            @tagName(record.type), try formatter.to_case(.UPPER_CASE, field.name),
        });
    }
    return text.items;
}

fn render_field_value(
    formatter: Formatter,
    field: ast.Field,
    continuation_indent_level: u32,
) ![]const u8 {
    switch (field.value) {
        .enum_literal => |literal| {
            return std.fmt.allocPrint(formatter.arena, "TigerBeetle::{s}::{s}", .{
                field.type.enum_name,
                try formatter.to_case(.UPPER_CASE, literal),
            });
        },
        .record => |record| if (ast.Record.is_flags(record.type)) {
            return render_flags(formatter, record, continuation_indent_level);
        } else {
            return render_expression(formatter, field.value);
        },
        else => return render_expression(formatter, field.value),
    }
}
