const std = @import("std");
const assert = std.debug.assert;

const conformance = @import("conformance");

const ast = conformance.ast;
const Printer = conformance.Printer;

pub fn main() !void {
    var stdout = std.io.bufferedWriter(std.io.getStdOut().writer());
    const stdout_writer = stdout.writer();
    var memory: [Printer.default_memory_size]u8 = undefined;
    var printer = Printer.init(&memory, stdout_writer.any(), .{
        .indent_width = 2,
        .start_level = 1,
    });

    const tests = try conformance.parse(printer.arena());

    try emit(&printer, tests);
    try stdout.flush();
}

fn satisfies(requirement: ast.Case.Requirement) bool {
    return switch (requirement) {
        // Ruby's Integer is arbitrary precision, and Float is accepted where Integer is expected.
        .requires_unbounded_integers => true,
        .requires_fractional_amounts => true,
    };
}

fn emit(printer: *Printer, tests: ast.ConformanceTests) !void {
    try printer.write(
        \\##########################################################
        \\## This file was auto-generated by ruby_conformance.zig ##
        \\##               Do not manually modify.                ##
        \\##########################################################
        \\
        \\require "minitest/autorun"
        \\require "tigerbeetle"
        \\
        \\class TestConformance < Minitest::Test
        \\  def setup
        \\    @tb_address = ENV.fetch("TB_ADDRESS", "3000")
        \\    @client = TigerBeetle::Client.new(cluster_id: 0, replica_addresses: @tb_address)
        \\  end
        \\
        \\  def teardown
        \\    @client.close if @client && !@client.closed?
        \\  end
        \\
    );
    for (tests.suites) |suite| {
        try printer.write_empty_line();
        try printer.print_indented("# Suite: {s}", .{suite.name});
        for (suite.cases) |case| {
            try printer.write_empty_line();
            if (case.requirement) |requirement| assert(satisfies(requirement));
            try printer.print_indented("def test_{s}_{s}", .{
                suite.name,
                try printer.to_case_alloc(.snake_case, case.description),
            });
            printer.indent();
            for (case.steps) |step| try emit_step(printer, step);
            printer.dedent();
            try printer.write_indented("end");
        }
    }
    try printer.write("end\n");
}

fn emit_step(printer: *Printer, step: ast.Step) !void {
    switch (step) {
        .binding => |binding| try emit_binding(printer, binding),
        .call => |call| try emit_call(printer, call, .{}),
        .assertion => |assertion| try emit_assertion(printer, assertion),
    }
}

fn emit_binding(printer: *Printer, binding: ast.Binding) !void {
    switch (binding.value) {
        .generate_id, .generate_ids, .index, .field_access => {
            try emit_binding_value(printer, binding.name, binding.value);
        },
        .record => |record| switch (record.type) {
            .U128 => try emit_binding_value(printer, binding.name, binding.value),
            .Account, .Transfer => {
                const prefix = try printer.string_alloc("{s} = ", .{binding.name});
                try emit_record(printer, record, .{ .prefix = prefix });
            },
            // Flags cannot be bound on their own, and result types are never written by hand.
            .AccountBalance,
            .AccountFilter,
            .AccountFilterFlags,
            .AccountFlags,
            .CreateAccountResult,
            .CreateTransferResult,
            .QueryFilter,
            .QueryFilterFlags,
            .TransferFlags,
            => unreachable,
        },
        .call => |call| {
            const prefix = try printer.string_alloc("{s} = ", .{binding.name});
            try emit_call(printer, call, .{ .prefix = prefix });
        },
        .integer, .boolean, .enum_literal, .reference, .increment, .decrement => unreachable,
    }
}

fn emit_binding_value(
    printer: *Printer,
    name: []const u8,
    value: ast.Expression,
) !void {
    const rendered = try render_expression(printer, value);
    try printer.print_indented("{s} = {s}", .{ name, rendered });
}

fn emit_call(
    printer: *Printer,
    call: ast.Call,
    options: struct {
        prefix: []const u8 = "",
    },
) !void {
    if (call.concurrency > 1) {
        assert(options.prefix.len == 0);
        try printer.print_indented("threads = Array.new({d}) do", .{call.concurrency});
        printer.indent();
        try printer.write_indented("Thread.new do");
        printer.indent();
        try emit_operation(printer, call, .{});
        printer.dedent();
        try printer.write_indented("end");
        printer.dedent();
        try printer.write_indented("end");
        try printer.write_indented("threads.each(&:join)");
    } else {
        try emit_operation(printer, call, .{ .prefix = options.prefix });
    }
}

fn emit_operation(
    printer: *Printer,
    call: ast.Call,
    options: struct {
        prefix: []const u8 = "",
    },
) !void {
    switch (call.name) {
        .close_client => {
            assert(options.prefix.len == 0);
            try printer.write_indented("@client.close");
        },
        .sleep_ms => {
            assert(options.prefix.len == 0);
            assert(call.arguments.len == 1);
            const ms = try render_expression(printer, call.arguments[0]);
            try printer.print_indented("sleep({s} / 1000.0)", .{ms});
        },
        .create_accounts, .create_transfers, .lookup_accounts, .lookup_transfers => {
            if (!arguments_contain_record(call)) {
                const inline_call = try render_call(printer, call);
                try printer.print_indented("{s}{s}", .{ options.prefix, inline_call });
                return;
            }
            try printer.print_indented("{s}@client.{s}(", .{ options.prefix, @tagName(call.name) });
            printer.indent();
            try printer.write_indented("[");
            printer.indent();
            for (call.arguments, 0..) |argument, index| {
                const suffix = if (index < call.arguments.len - 1) "," else "";
                switch (argument) {
                    .record => |record| {
                        try emit_record(printer, record, .{ .suffix = suffix });
                    },
                    else => {
                        const text = try render_expression(printer, argument);
                        try printer.print_indented("{s}{s}", .{ text, suffix });
                    },
                }
            }
            printer.dedent();
            try printer.write_indented("]");
            printer.dedent();
            try printer.write_indented(")");
        },
        .get_account_transfers, .get_account_balances, .query_accounts, .query_transfers => {
            assert(call.arguments.len == 1);
            try printer.print_indented("{s}@client.{s}(", .{ options.prefix, @tagName(call.name) });
            printer.indent();
            try emit_record(printer, call.arguments[0].record, .{});
            printer.dedent();
            try printer.write_indented(")");
        },
    }
}

fn emit_record(
    printer: *Printer,
    record: ast.Record,
    options: struct {
        prefix: []const u8 = "",
        suffix: []const u8 = "",
    },
) !void {
    try printer.print_indented("{s}TigerBeetle::{s}.new(", .{
        options.prefix, @tagName(record.type),
    });
    printer.indent();
    for (record.fields, 0..) |field, index| {
        const value = try render_typed_value(
            printer,
            field.field,
            field.value,
            printer.level + 1,
        );
        const suffix = if (index < record.fields.len - 1) "," else "";
        try printer.print_indented("{s}: {s}{s}", .{ field.field.name, value, suffix });
    }
    printer.dedent();
    try printer.print_indented("){s}", .{options.suffix});
}

fn emit_assertion(
    printer: *Printer,
    assertion: ast.Assertion,
) !void {
    switch (assertion) {
        .equal => |equal| {
            try printer.print_indented("assert_equal({d}, {s}.length)", .{
                equal.expected.len, equal.actual,
            });
            for (equal.expected, 0..) |record, index| {
                for (record.fields) |field| {
                    const value = try render_typed_value(
                        printer,
                        field.field,
                        field.value,
                        printer.level + 1,
                    );
                    try printer.print_indented("assert_equal({s}, {s}[{d}].{s})", .{
                        value, equal.actual, index, field.field.name,
                    });
                }
            }
        },
        .empty => |actual| {
            try printer.print_indented("assert_equal(0, {s}.length)", .{actual});
        },
        .unique => |ids| {
            try printer.print_indented("assert_equal({s}.length, {s}.uniq.length)", .{ ids, ids });
        },
        .ascending => |ids| {
            try printer.print_indented(
                "{s}.each_cons(2) {{ |a, b| assert_operator(a, :<, b) }}",
                .{ids},
            );
        },
        .equal_field => |comparison| {
            const actual = try render_field_access(printer, comparison.actual);
            const value = switch (comparison.expected) {
                .expression => |expression| try render_typed_value(
                    printer,
                    comparison.actual.field,
                    expression,
                    printer.level + 1,
                ),
                .field_reference => |field| try render_field_access(printer, field),
            };
            try printer.print_indented("assert_equal({s}, {s})", .{ value, actual });
        },
        .greater_than => |comparison| {
            const actual = try render_field_access(printer, comparison.actual);
            const value = try render_expression(printer, comparison.expected.expression);
            try printer.print_indented("assert_operator({s}, :>, {s})", .{ actual, value });
        },
        .fail => |call| {
            try printer.write_indented("assert_raises(StandardError) do");
            printer.indent();
            try emit_operation(printer, call, .{});
            printer.dedent();
            try printer.write_indented("end");
        },
    }
}

fn render_field_access(
    printer: *Printer,
    reference: ast.FieldReference,
) ![]const u8 {
    return printer.string_alloc("{s}.{s}", .{
        reference.reference,
        reference.field.name,
    });
}

fn arguments_contain_record(call: ast.Call) bool {
    for (call.arguments) |argument| {
        if (argument == .record) return true;
    }
    return false;
}

fn render_call(printer: *Printer, call: ast.Call) ![]const u8 {
    assert(!arguments_contain_record(call));
    switch (call.name) {
        .create_accounts, .create_transfers, .lookup_accounts, .lookup_transfers => {
            var text = std.ArrayList(u8).init(printer.arena());
            try text.writer().print("@client.{s}([", .{@tagName(call.name)});
            for (call.arguments, 0..) |argument, index| {
                if (index > 0) try text.appendSlice(", ");
                try text.appendSlice(try render_expression(printer, argument));
            }
            try text.appendSlice("])");
            return text.items;
        },
        // emit_operation handles the rest of Call.Name directly: close_client and sleep_ms have
        // their own single-line forms, filter operations always take a record literal emitted
        // multiline. None of them ever reach this compact batch-op form.
        .close_client,
        .sleep_ms,
        .get_account_transfers,
        .get_account_balances,
        .query_accounts,
        .query_transfers,
        => unreachable,
    }
}

fn render_expression(
    printer: *Printer,
    expression: ast.Expression,
) std.mem.Allocator.Error![]const u8 {
    switch (expression) {
        .generate_id => return "TigerBeetle.id",
        .generate_ids => |count| {
            return printer.string_alloc("Array.new({d}) {{ TigerBeetle.id }}", .{count});
        },
        .call => unreachable, // Calls are emitted by emit_call/emit_operation.
        .record => |record| switch (record.type) {
            .U128 => {
                assert(record.fields.len == 1);
                return render_expression(printer, record.fields[0].value);
            },
            // Flags can't be bound on their own for now (parser-rejected).
            else => unreachable,
        },
        .integer => |text| return text,
        .boolean => |value| return if (value) "true" else "false",
        .enum_literal => unreachable, // Only valid as a record field, rendered there.
        .reference => |name| return name,
        .index => |index| {
            return printer.string_alloc("{s}[{d}]", .{
                index.reference,
                index.index,
            });
        },
        .field_access => |access| return render_field_access(printer, access),
        .increment => |arithmetic| return render_arithmetic(printer, arithmetic, "+"),
        .decrement => |arithmetic| return render_arithmetic(printer, arithmetic, "-"),
    }
}

fn render_arithmetic(
    printer: *Printer,
    arithmetic: ast.Expression.Arithmetic,
    operator: []const u8,
) ![]const u8 {
    return printer.string_alloc("{s} {s} {d}", .{
        arithmetic.reference,
        operator,
        arithmetic.by,
    });
}

fn render_flags(
    printer: *Printer,
    record: ast.Record,
    continuation_indent_level: u32,
) ![]const u8 {
    var text = std.ArrayList(u8).init(printer.arena());
    for (record.fields, 0..) |field, index| {
        assert(field.value == .boolean and field.value.boolean);
        if (index > 0) {
            const width = continuation_indent_level * printer.indent_width;
            try text.appendSlice(" |\n");
            try text.writer().writeByteNTimes(' ', width);
        }
        try text.writer().print("TigerBeetle::{s}::{s}", .{
            @tagName(record.type), try printer.to_case_alloc(.UPPER_CASE, field.field.name),
        });
    }
    return text.items;
}

fn render_typed_value(
    printer: *Printer,
    field: ast.Field,
    value: ast.Expression,
    continuation_indent_level: u32,
) ![]const u8 {
    switch (value) {
        .enum_literal => |literal| {
            return printer.string_alloc("TigerBeetle::{s}::{s}", .{
                field.type.enum_name,
                try printer.to_case_alloc(.UPPER_CASE, literal),
            });
        },
        .record => |record| if (ast.Record.is_flags(record.type)) {
            return render_flags(printer, record, continuation_indent_level);
        } else {
            return render_expression(printer, value);
        },
        else => return render_expression(printer, value),
    }
}
