const std = @import("std");
const assert = std.debug.assert;

const conformance = @import("conformance");

const ast = conformance.ast;
const Printer = conformance.Printer;

const line_width_max = 100;

// Mirrors `big_integer.fields` in `java_bindings.zig` — fields here become
// `BigInteger`, others `byte[]`. Maybe enforce at comptime later
const big_integer_fields = [_][]const u8{
    "credits_posted",
    "credits_pending",
    "debits_posted",
    "debits_pending",
    "amount",
};

pub fn main() !void {
    var stdout = std.io.bufferedWriter(std.io.getStdOut().writer());
    const stdout_writer = stdout.writer();
    var memory: [Printer.default_memory_size]u8 = undefined;
    var printer = Printer.init(&memory, stdout_writer.any(), .{
        .indent_width = 4,
        .start_level = 1,
    });

    const tests = try conformance.parse(printer.arena());

    try emit(&printer, tests);
    try stdout.flush();
}

fn satisfies(requirement: ast.Case.Requirement) bool {
    return switch (requirement) {
        // Amounts are passed as a pair of `long`s, so neither a value above the
        // maximum nor a fractional one can be constructed.
        .requires_unbounded_integers => false,
        .requires_fractional_amounts => false,
    };
}

fn emit(printer: *Printer, tests: ast.ConformanceTests) !void {
    try printer.write(
        \\//////////////////////////////////////////////////////////
        \\// This file was auto-generated by java_conformance.zig
        \\// Do not manually modify.
        \\//////////////////////////////////////////////////////////
        \\
        \\package com.tigerbeetle;
        \\
        \\import java.io.BufferedReader;
        \\import java.io.File;
        \\import java.io.InputStreamReader;
        \\import java.lang.ProcessBuilder.Redirect;
        \\import java.math.BigInteger;
        \\import java.time.Duration;
        \\import java.util.HashSet;
        \\import java.util.stream.Collectors;
        \\
        \\import org.junit.After;
        \\import org.junit.AfterClass;
        \\import org.junit.Before;
        \\import org.junit.BeforeClass;
        \\import org.junit.Test;
        \\import static org.junit.Assert.assertArrayEquals;
        \\import static org.junit.Assert.assertEquals;
        \\import static org.junit.Assert.assertThrows;
        \\import static org.junit.Assert.assertTrue;
        \\
        \\public class ConformanceTest {
        \\    private static final byte[] clusterId = new byte[16];
        \\
        \\    private static Server server;
        \\
        \\    private Client client;
        \\
        \\    @BeforeClass
        \\    public static void initialize() throws Exception {
        \\        server = new Server("conformance");
        \\    }
        \\
        \\    @AfterClass
        \\    public static void cleanup() throws Exception {
        \\        server.close();
        \\    }
        \\
        \\    @Before
        \\    public void createClient() throws Exception {
        \\        client = new Client(clusterId, new String[] {server.getAddress()});
        \\    }
        \\
        \\    @After
        \\    public void closeClient() throws Exception {
        \\        client.close();
        \\    }
        \\
    );
    for (tests.suites) |suite| {
        try printer.write_empty_line();
        try printer.print_indented("// Suite: {s}", .{suite.name});
        for (suite.cases) |case| {
            try printer.write_empty_line();
            if (case.requirement) |requirement| {
                if (!satisfies(requirement)) {
                    try printer.write_omission(case);
                    continue;
                }
            }
            try printer.write_indented("@Test");
            const name = try printer.string_alloc("public void test{s}{s}()", .{
                try printer.to_case_alloc(.PascalCase, suite.name),
                try printer.to_case_alloc(.PascalCase, case.description),
            });
            // A signature that overflows the line width breaks before `throws`.
            if (printer.level * printer.indent_width + name.len +
                " throws Exception {".len > line_width_max)
            {
                try printer.print_indented("{s}", .{name});
                printer.indent();
                printer.indent();
                try printer.write_indented("throws Exception {");
                printer.dedent();
                printer.dedent();
            } else {
                try printer.print_indented("{s} throws Exception {{", .{name});
            }
            printer.indent();
            try emit_case(printer, case);
            printer.dedent();
            try printer.write_indented("}");
        }
    }
    try emit_server(printer);
    try printer.write("}\n");
}

fn emit_case(
    printer: *Printer,
    case: ast.Case,
) !void {
    var scope = Scope.init(printer);
    var emitted = false;
    const consumed = try printer.arena().alloc(bool, case.steps.len);
    @memset(consumed, false);
    for (case.steps, 0..) |step, index| {
        if (consumed[index]) continue;
        if (emitted and starts_operation(step)) try printer.write("\n");
        if (step == .binding and step.binding.value == .index and
            !scope.id_arrays.contains(step.binding.value.index.reference))
        {
            try emit_row_group(&scope, case.steps, index, consumed);
        } else {
            try emit_step(&scope, step);
        }
        emitted = true;
    }
}

// Each request and the statements that build and check it form a paragraph, the way the
// hand-written integration tests are laid out.
fn starts_operation(step: ast.Step) bool {
    return switch (step) {
        .call => true,
        .binding => |binding| binding.value == .call,
        .assertion => |assertion| assertion == .fail,
    };
}

// Java has no row type: a result batch is its own cursor. So an indexed binding never becomes a
// local. The rows a case names are walked with `next()`, each row's assertions grouped behind its
// own advance, the way `IntegrationTest` reads a batch.
fn emit_row_group(
    scope: *Scope,
    steps: []const ast.Step,
    start: usize,
    consumed: []bool,
) !void {
    const printer = scope.printer;
    const origin = steps[start].binding.value.index;
    const batch = try printer.to_case_alloc(.camelCase, origin.reference);

    const Row = struct { name: []const u8, index: u32 };
    var rows = std.ArrayList(Row).init(printer.arena());
    for (steps[start..], start..) |step, index| {
        if (step != .binding or step.binding.value != .index) continue;
        if (!std.mem.eql(u8, step.binding.value.index.reference, origin.reference)) continue;
        // The cursor only moves forward, so a case names the rows of a batch in order.
        if (rows.getLastOrNull()) |last| assert(step.binding.value.index.index > last.index);
        try rows.append(.{
            .name = step.binding.name,
            .index = step.binding.value.index.index,
        });
        consumed[index] = true;
    }

    try scope.walk(batch);
    var position: u32 = 0;
    for (rows.items) |entry| {
        const row = entry.name;
        while (position <= entry.index) : (position += 1) {
            try printer.print_indented("assertTrue({s}.next());", .{batch});
        }
        try emit_row_captures(printer, steps, row, batch, consumed);
        for (steps, 0..) |step, index| {
            if (step != .assertion) continue;
            var comparison: ast.Assertion.FieldComparison = undefined;
            var greater_than = false;
            switch (step.assertion) {
                .equal_field => |value| comparison = value,
                .greater_than => |value| {
                    comparison = value;
                    greater_than = true;
                },
                else => continue,
            }
            if (comparison.expected == .field_reference) {
                try emit_row_equal_field(printer, steps, .{
                    .comparison = comparison,
                    .row = row,
                    .batch = batch,
                    .consumed = &consumed[index],
                });
                continue;
            }
            if (!std.mem.eql(u8, comparison.actual.reference, row)) continue;
            consumed[index] = true;

            const property = try printer.to_case_alloc(.PascalCase, comparison.actual.field.name);
            const value = try render_typed_value(
                printer,
                comparison.actual.field,
                comparison.expected.expression,
            );
            try printer.write_indent();
            if (greater_than) {
                try printer.print("assertTrue({s}.get{s}() > {s});\n", .{ batch, property, value });
            } else {
                try printer.print("{s}({s}, {s}.get{s}());\n", .{
                    assert_function(comparison.actual.field),
                    value,
                    batch,
                    property,
                });
            }
        }
    }
}

// There is no row local, so a field bound off a row is captured while the cursor is on it.
fn emit_row_captures(
    printer: *Printer,
    steps: []const ast.Step,
    row: []const u8,
    batch: []const u8,
    consumed: []bool,
) !void {
    for (steps, 0..) |step, index| {
        if (step != .binding or step.binding.value != .field_access) continue;
        const access = step.binding.value.field_access;
        if (!std.mem.eql(u8, access.reference, row)) continue;
        consumed[index] = true;
        try printer.print_indented("final var {s} = {s}.get{s}();", .{
            try printer.to_case_alloc(.camelCase, step.binding.name),
            batch,
            try printer.to_case_alloc(.PascalCase, access.field.name),
        });
    }
}

// Two rows are never in scope at once, so the row walked first captures its field in a local.
fn emit_row_equal_field(
    printer: *Printer,
    steps: []const ast.Step,
    options: struct {
        comparison: ast.Assertion.FieldComparison,
        row: []const u8,
        batch: []const u8,
        consumed: *bool,
    },
) !void {
    const actual = options.comparison.actual;
    const expected = options.comparison.expected.field_reference;
    const walks_actual = std.mem.eql(u8, actual.reference, options.row);
    const walks_expected = std.mem.eql(u8, expected.reference, options.row);
    if (!walks_actual and !walks_expected) return;

    const assertion = assert_function(actual.field);
    if (walks_actual and walks_expected) {
        options.consumed.* = true;
        try printer.print_indented("{s}({s}.get{s}(), {s}.get{s}());", .{
            assertion,
            options.batch,
            try printer.to_case_alloc(.PascalCase, expected.field.name),
            options.batch,
            try printer.to_case_alloc(.PascalCase, actual.field.name),
        });
        return;
    }

    const here = if (walks_actual) actual else expected;
    const there = if (walks_actual) expected else actual;
    const property = try printer.to_case_alloc(.PascalCase, here.field.name);
    if (walks_before(steps, options.row, there.reference)) {
        try printer.print_indented("final var {s} = {s}.get{s}();", .{
            try capture_name(printer, here),
            options.batch,
            property,
        });
        return;
    }

    options.consumed.* = true;
    const captured = try capture_name(printer, there);
    const walked = try printer.string_alloc("{s}.get{s}()", .{
        options.batch,
        property,
    });
    try printer.print_indented("{s}({s}, {s});", .{
        assertion,
        if (walks_actual) captured else walked,
        if (walks_actual) walked else captured,
    });
}

fn capture_name(printer: *Printer, reference: ast.FieldReference) ![]const u8 {
    return printer.string_alloc("{s}{s}", .{
        try printer.to_case_alloc(.camelCase, reference.reference),
        try printer.to_case_alloc(.PascalCase, reference.field.name),
    });
}

fn walks_before(steps: []const ast.Step, row: []const u8, other: []const u8) bool {
    const first = row_position(steps, row);
    const second = row_position(steps, other);
    if (first.batch != second.batch) return first.batch < second.batch;
    return first.row < second.row;
}

fn row_position(steps: []const ast.Step, row: []const u8) struct { batch: usize, row: usize } {
    for (steps, 0..) |step, index| {
        if (step != .binding or step.binding.value != .index) continue;
        if (!std.mem.eql(u8, step.binding.name, row)) continue;
        const reference = step.binding.value.index.reference;
        for (steps, 0..) |batch_step, batch_index| {
            if (batch_step != .binding or batch_step.binding.value != .index) continue;
            if (std.mem.eql(u8, batch_step.binding.value.index.reference, reference)) {
                return .{ .batch = batch_index, .row = index };
            }
        }
        unreachable;
    }
    unreachable;
}

// Bound record literals are inlined at each use, since Java has no standalone event type: a
// record only exists as a row of a batch. Generated ids are hoisted to locals first, so a record
// reused across two calls carries the same id both times.
const Scope = struct {
    printer: *Printer,
    records: std.StringHashMap(ast.Record),
    id_arrays: std.StringHashMap(void),
    walked: std.StringHashMap(void),

    fn init(printer: *Printer) Scope {
        return .{
            .printer = printer,
            .records = std.StringHashMap(ast.Record).init(printer.arena()),
            .id_arrays = std.StringHashMap(void).init(printer.arena()),
            .walked = std.StringHashMap(void).init(printer.arena()),
        };
    }

    // A batch is a cursor, so a second pass over one has to rewind first.
    fn walk(scope: *Scope, batch: []const u8) !void {
        const entry = try scope.walked.getOrPut(batch);
        if (!entry.found_existing) return;
        const printer = scope.printer;
        try printer.print_indented("{s}.beforeFirst();", .{batch});
    }
};

fn emit_step(scope: *Scope, step: ast.Step) !void {
    switch (step) {
        .binding => |binding| try emit_binding(scope, binding),
        .call => |call| try emit_call(scope, call, .{}),
        .assertion => |assertion| try emit_assertion(scope, assertion),
    }
}

fn emit_binding(scope: *Scope, binding: ast.Binding) !void {
    const printer = scope.printer;
    const name = try printer.to_case_alloc(.camelCase, binding.name);
    switch (binding.value) {
        .generate_id => {
            try printer.print_indented("final var {s} = UInt128.id();", .{name});
        },
        .generate_ids => |count| {
            try scope.id_arrays.put(binding.name, {});
            try printer.print_indented("final var {s} = new byte[{d}][];", .{ name, count });
            try printer.print_indented("for (int index = 0; index < {d}; index++) {{", .{count});
            printer.indent();
            try printer.print_indented("{s}[index] = UInt128.id();", .{name});
            printer.dedent();
            try printer.write_indented("}");
        },
        .index => |index| {
            const reference = try printer.to_case_alloc(.camelCase, index.reference);
            try printer.print_indented("final var {s} = {s}[{d}];", .{
                name, reference, index.index,
            });
        },
        .record => |record| switch (record.type) {
            .U128 => {
                assert(record.fields.len == 1);
                const value = try render_uint128(printer, record.fields[0].value.integer);
                try emit_assignment(printer, name, value);
            },
            .Account, .Transfer => {
                try scope.records.put(binding.name, try hoist_record(scope, name, record));
            },
            // Flags cannot be bound on their own, and result types are never written by hand.
            .AccountBalance,
            .AccountFilter,
            .AccountFilterFlags,
            .AccountFlags,
            .CreateAccountResult,
            .CreateTransferResult,
            .QueryFilter,
            .QueryFilterFlags,
            .TransferFlags,
            => unreachable,
        },
        .call => |call| try emit_call(scope, call, .{ .binding = name }),
        .integer,
        .boolean,
        .enum_literal,
        .reference,
        .field_access,
        .increment,
        .decrement,
        => unreachable,
    }
}

// Emits a local for every generated id in the record, returning the record with those fields
// rewritten to reference the local.
fn hoist_record(
    scope: *Scope,
    name: []const u8,
    record: ast.Record,
) !ast.Record {
    const printer = scope.printer;
    const fields = try printer.arena().alloc(ast.FieldValue, record.fields.len);
    for (record.fields, 0..) |field, index| {
        if (field.value != .generate_id) {
            fields[index] = field;
            continue;
        }
        const local = try printer.string_alloc("{s}{s}", .{
            name,
            try printer.to_case_alloc(.PascalCase, field.field.name),
        });
        try printer.print_indented("final var {s} = UInt128.id();", .{local});
        fields[index] = .{ .field = field.field, .value = .{ .reference = local } };
    }
    return .{ .type = record.type, .fields = fields };
}

fn emit_call(
    scope: *Scope,
    call: ast.Call,
    options: struct {
        binding: ?[]const u8 = null,
        expect_error: bool = false,
    },
) !void {
    const printer = scope.printer;
    if (call.concurrency > 1) {
        assert(options.binding == null);
        // A `RuntimeException` thrown from `Thread.run()` is delivered to the uncaught
        // handler and dropped, so each thread captures into `exceptions` for a post-join
        // rethrow — the same shape as `IntegrationTest.TransferTask` storing `.exception`.
        try printer.print_indented("final var threads = new Thread[{d}];", .{call.concurrency});
        try printer.print_indented("final var exceptions = new Exception[{d}];", .{
            call.concurrency,
        });
        try printer.print_indented("for (int index = 0; index < {d}; index++) {{", .{
            call.concurrency,
        });
        printer.indent();
        try printer.write_indented("final var threadIndex = index;");
        try printer.write_indented("threads[index] = new Thread(() -> {");
        printer.indent();
        try printer.write_indented("try {");

        printer.indent();
        var thread_scope = Scope.init(printer);
        try emit_operation(&thread_scope, call, .{});
        printer.dedent();

        try printer.write_indented("} catch (Exception exception) {");
        printer.indent();
        try printer.write_indented("exceptions[threadIndex] = exception;");
        printer.dedent();
        try printer.write_indented("}");
        printer.dedent();
        try printer.write_indented("});");
        try printer.write_indented("threads[index].start();");
        printer.dedent();
        try printer.write_indented("}");
        try printer.write_indented("for (final var thread : threads) {");
        printer.indent();
        try printer.write_indented("thread.join(Duration.ofSeconds(60).toMillis());");
        try printer.write_indented(
            "assertTrue(\"Worker did not terminate within 60 seconds\", !thread.isAlive());",
        );
        printer.dedent();
        try printer.write_indented("}");
        try printer.write_indented("for (final var exception : exceptions) {");
        printer.indent();
        try printer.write_indented("if (exception != null)");
        printer.indent();
        try printer.write_indented("throw exception;");
        printer.dedent();
        printer.dedent();
        try printer.write_indented("}");
        return;
    }

    try emit_operation(scope, call, .{
        .binding = options.binding,
        .expect_error = options.expect_error,
    });
}

fn emit_operation(
    scope: *Scope,
    call: ast.Call,
    options: struct {
        binding: ?[]const u8 = null,
        expect_error: bool = false,
    },
) !void {
    const printer = scope.printer;
    switch (call.name) {
        .close_client => {
            assert(options.binding == null);
            try printer.write_indented("client.close();");
            return;
        },
        .sleep_ms => {
            assert(options.binding == null);
            assert(call.arguments.len == 1);
            try printer.print_indented("Thread.sleep({s});", .{call.arguments[0].integer});
            return;
        },
        else => {},
    }

    // A call whose result the corpus binds names its input after that binding; one whose result
    // is discarded gets a block, so the plain name is free to repeat.
    const scoped = options.binding == null;
    if (scoped) {
        try printer.write_indented("{");
        printer.indent();
    }

    // The argument is built into a local first, so that `assertThrows` can capture it: a lambda
    // may only close over effectively final locals.
    const argument = try emit_argument(scope, call, options.binding);

    try printer.write_indent();
    if (options.expect_error) {
        try printer.print("assertThrows(Exception.class, () -> client.{s}({s}));\n", .{
            java_operation_name(call.name),
            argument,
        });
    } else {
        if (options.binding) |binding| try printer.print("final var {s} = ", .{binding});
        try printer.print("client.{s}({s});\n", .{ java_operation_name(call.name), argument });
    }

    if (scoped) {
        printer.dedent();
        try printer.write_indented("}");
    }
}

fn local_name(
    printer: *Printer,
    binding: ?[]const u8,
    suffix: []const u8,
    unbound: []const u8,
) ![]const u8 {
    const name = binding orelse return unbound;
    return printer.string_alloc("{s}{s}", .{ name, suffix });
}

fn emit_argument(
    scope: *Scope,
    call: ast.Call,
    binding: ?[]const u8,
) ![]const u8 {
    const printer = scope.printer;
    switch (call.name) {
        .create_accounts, .create_transfers => {
            const accounts = call.name == .create_accounts;
            const batch_type = if (accounts) "AccountBatch" else "TransferBatch";
            const name = try local_name(
                printer,
                binding,
                "Batch",
                if (accounts) "accountsBatch" else "transfersBatch",
            );
            try printer.print_indented("final var {s} = new {s}({d});", .{
                name,
                batch_type,
                call.arguments.len,
            });
            for (call.arguments) |argument| {
                const record = switch (argument) {
                    .record => |record| record,
                    .reference => |reference| scope.records.get(reference).?,
                    else => unreachable,
                };
                try emit_record_into(printer, record, name);
            }
            return name;
        },
        .lookup_accounts, .lookup_transfers => {
            const name = try local_name(printer, binding, "Batch", "idsBatch");
            try printer.print_indented("final var {s} = new IdBatch({d});", .{
                name, call.arguments.len,
            });
            for (call.arguments) |argument| {
                try printer.print_indented("{s}.add({s});", .{
                    name, try render_id(printer, argument),
                });
            }
            return name;
        },
        .get_account_transfers, .get_account_balances, .query_accounts, .query_transfers => {
            assert(call.arguments.len == 1);
            const filter = call.arguments[0].record;
            const name = try local_name(printer, binding, "Filter", "filter");
            try printer.print_indented("final var {s} = new {s}();", .{
                name, @tagName(filter.type),
            });
            for (filter.fields) |field| {
                try emit_filter_field(printer, field, name);
            }
            return name;
        },
        .close_client, .sleep_ms => unreachable,
    }
}

fn emit_record_into(printer: *Printer, record: ast.Record, batch: []const u8) !void {
    try printer.print_indented("{s}.add();", .{batch});
    for (record.fields) |field| {
        try emit_setter(
            printer,
            batch,
            try printer.to_case_alloc(.PascalCase, field.field.name),
            try render_typed_value(printer, field.field, field.value),
        );
    }
}

// Filters expose their flags as boolean setters (`setDebits(true)`) rather than a flags word.
fn emit_filter_field(
    printer: *Printer,
    field: ast.FieldValue,
    name: []const u8,
) !void {
    if (field.value == .record and ast.Record.is_flags(field.value.record.type)) {
        for (field.value.record.fields) |flag| {
            assert(flag.value == .boolean and flag.value.boolean);
            try printer.print_indented("{s}.set{s}(true);", .{
                name,
                try printer.to_case_alloc(.PascalCase, flag.field.name),
            });
        }
        return;
    }
    try emit_setter(
        printer,
        name,
        try printer.to_case_alloc(.PascalCase, field.field.name),
        try render_typed_value(printer, field.field, field.value),
    );
}

// An over-long statement breaks onto a continuation line indented two levels further.
fn emit_assignment(printer: *Printer, name: []const u8, value: []const u8) !void {
    const width = printer.level * printer.indent_width + "final var ".len + name.len +
        " = ".len + value.len + ";".len;
    try printer.write_indent();
    if (width <= line_width_max) {
        try printer.print("final var {s} = {s};\n", .{ name, value });
        return;
    }
    try printer.print("final var {s} =\n", .{name});
    printer.indent();
    printer.indent();
    try printer.print_indented("{s};", .{value});
    printer.dedent();
    printer.dedent();
}

fn emit_setter(
    printer: *Printer,
    target: []const u8,
    property: []const u8,
    value: []const u8,
) !void {
    const width = printer.level * printer.indent_width + target.len + ".set".len + property.len +
        "(".len + value.len + ");".len;
    try printer.write_indent();
    if (width <= line_width_max) {
        try printer.print("{s}.set{s}({s});\n", .{ target, property, value });
        return;
    }

    // A flags word is the only setter argument that overflows; the break goes before each `|`.
    var count: usize = 1;
    var counter = std.mem.splitSequence(u8, value, " | ");
    _ = counter.first();
    while (counter.next()) |_| count += 1;

    var operands = std.mem.splitSequence(u8, value, " | ");
    try printer.print("{s}.set{s}({s}\n", .{ target, property, operands.first() });
    printer.indent();
    printer.indent();
    var index: usize = 1;
    while (operands.next()) |operand| : (index += 1) {
        try printer.print_indented("| {s}{s}", .{ operand, if (index + 1 == count) ");" else "" });
    }
    printer.dedent();
    printer.dedent();
}

fn emit_assertion(scope: *Scope, assertion: ast.Assertion) !void {
    const printer = scope.printer;
    switch (assertion) {
        .equal => |equal| {
            const actual = try printer.to_case_alloc(.camelCase, equal.actual);
            try printer.print_indented("assertEquals({d}, {s}.getLength());", .{
                equal.expected.len,
                actual,
            });
            try scope.walk(actual);
            for (equal.expected) |record| {
                try printer.print_indented("assertTrue({s}.next());", .{actual});
                for (record.fields) |field| {
                    try emit_field_equal(printer, field, actual);
                }
            }
        },
        .empty => |actual| {
            try printer.print_indented("assertEquals(0, {s}.getLength());", .{
                try printer.to_case_alloc(.camelCase, actual),
            });
        },
        .unique => |ids| {
            const name = try printer.to_case_alloc(.camelCase, ids);
            try printer.write_indented("final var seen = new HashSet<BigInteger>();");
            try printer.print_indented("for (final var id : {s}) {{", .{name});
            printer.indent();
            try printer.write_indented("assertTrue(seen.add(UInt128.asBigInteger(id)));");
            printer.dedent();
            try printer.write_indented("}");
        },
        .ascending => |ids| {
            const name = try printer.to_case_alloc(.camelCase, ids);
            try printer.print_indented("for (int index = 1; index < {s}.length; index++) {{", .{
                name,
            });
            printer.indent();
            try printer.print_indented("assertTrue(UInt128.asBigInteger({s}[index - 1])", .{name});
            printer.indent();
            printer.indent();
            try printer.print_indented(".compareTo(UInt128.asBigInteger({s}[index])) < 0);", .{
                name,
            });
            printer.dedent();
            printer.dedent();
            printer.dedent();
            try printer.write_indented("}");
        },
        .equal_field => |comparison| {
            const expected = switch (comparison.expected) {
                .expression => |expression| try render_typed_value(
                    printer,
                    comparison.actual.field,
                    expression,
                ),
                .field_reference => |field| try render_field_access(printer, field),
            };
            try printer.print_indented("{s}({s}, {s});", .{
                assert_function(comparison.actual.field),
                expected,
                try render_field_access(printer, comparison.actual),
            });
        },
        .greater_than => |comparison| {
            try printer.print_indented("assertTrue({s} > {s});", .{
                try render_field_access(printer, comparison.actual),
                try render_typed_value(
                    printer,
                    comparison.actual.field,
                    comparison.expected.expression,
                ),
            });
        },
        .fail => |call| try emit_call(scope, call, .{ .expect_error = true }),
    }
}

fn emit_field_equal(
    printer: *Printer,
    field: ast.FieldValue,
    actual: []const u8,
) !void {
    try printer.print_indented("{s}({s}, {s}.get{s}());", .{
        assert_function(field.field),
        try render_typed_value(printer, field.field, field.value),
        actual,
        try printer.to_case_alloc(.PascalCase, field.field.name),
    });
}

fn assert_function(field: ast.Field) []const u8 {
    if (is_byte_array(field)) return "assertArrayEquals";
    return "assertEquals";
}

fn is_byte_array(field: ast.Field) bool {
    if (field.type != .int or field.type.int != 128) return false;
    return !is_big_integer(field.name);
}

fn is_big_integer(field_name: []const u8) bool {
    for (big_integer_fields) |name| {
        if (std.mem.eql(u8, name, field_name)) return true;
    }
    return false;
}

fn render_field_access(
    printer: *Printer,
    reference: ast.FieldReference,
) ![]const u8 {
    return printer.string_alloc("{s}.get{s}()", .{
        try printer.to_case_alloc(.camelCase, reference.reference),
        try printer.to_case_alloc(.PascalCase, reference.field.name),
    });
}

fn render_arithmetic(
    printer: *Printer,
    arithmetic: ast.Expression.Arithmetic,
    operator: []const u8,
) ![]const u8 {
    return printer.string_alloc("{s} {s} {d}L", .{
        try printer.to_case_alloc(.camelCase, arithmetic.reference),
        operator,
        arithmetic.by,
    });
}

fn render_typed_value(
    printer: *Printer,
    field: ast.Field,
    value: ast.Expression,
) ![]const u8 {
    switch (value) {
        .enum_literal => |literal| {
            return printer.string_alloc("{s}.{s}", .{
                field.type.enum_name,
                try printer.to_case_alloc(.PascalCase, literal),
            });
        },
        .record => |flags| {
            assert(ast.Record.is_flags(flags.type));
            var text = std.ArrayList(u8).init(printer.arena());
            for (flags.fields, 0..) |flag, index| {
                assert(flag.value == .boolean and flag.value.boolean);
                if (index > 0) try text.appendSlice(" | ");
                try text.writer().print("{s}.{s}", .{
                    @tagName(flags.type),
                    try printer.to_case_alloc(.UPPER_CASE, flag.field.name),
                });
            }
            return text.items;
        },
        .integer => |text| {
            const bits = field.type.int;
            if (bits == 128) {
                if (is_big_integer(field.name)) return render_big_integer(printer, text);
                return render_uint128(printer, text);
            }
            // A 64-bit literal overflows Java's `int` without the suffix.
            if (bits == 64) return printer.string_alloc("{s}L", .{text});
            return text;
        },
        .generate_id => return "UInt128.id()",
        .reference => |name| return printer.to_case_alloc(.camelCase, name),
        .index => |index| {
            return printer.string_alloc("{s}[{d}]", .{
                try printer.to_case_alloc(.camelCase, index.reference),
                index.index,
            });
        },
        .boolean => |boolean| return if (boolean) "true" else "false",
        .field_access => |access| return render_field_access(printer, access),
        .increment => |arithmetic| return render_arithmetic(printer, arithmetic, "+"),
        .decrement => |arithmetic| return render_arithmetic(printer, arithmetic, "-"),
        .call, .generate_ids => unreachable,
    }
}

// Ids reach the client as `byte[]`, whatever shape they take in the corpus.
fn render_id(printer: *Printer, expression: ast.Expression) ![]const u8 {
    switch (expression) {
        .generate_id => return "UInt128.id()",
        .reference => |name| return printer.to_case_alloc(.camelCase, name),
        .integer => |text| return render_uint128(printer, text),
        .index => |index| {
            return printer.string_alloc("{s}[{d}]", .{
                try printer.to_case_alloc(.camelCase, index.reference),
                index.index,
            });
        },
        .call,
        .generate_ids,
        .record,
        .boolean,
        .enum_literal,
        .field_access,
        .increment,
        .decrement,
        => unreachable,
    }
}

fn render_uint128(printer: *Printer, text: []const u8) ![]const u8 {
    const value = std.fmt.parseInt(u128, text, 10) catch unreachable;
    if (value <= std.math.maxInt(u64)) {
        return printer.string_alloc("UInt128.asBytes({d}L)", .{value});
    }
    return printer.string_alloc("UInt128.asBytes(new BigInteger(\"{d}\"))", .{value});
}

fn render_big_integer(printer: *Printer, text: []const u8) ![]const u8 {
    const value = std.fmt.parseInt(u128, text, 10) catch unreachable;
    if (value <= std.math.maxInt(u64)) {
        return printer.string_alloc("BigInteger.valueOf({d}L)", .{value});
    }
    return printer.string_alloc("new BigInteger(\"{d}\")", .{value});
}

fn java_operation_name(name: ast.Call.Name) []const u8 {
    return switch (name) {
        .create_accounts => "createAccounts",
        .create_transfers => "createTransfers",
        .lookup_accounts => "lookupAccounts",
        .lookup_transfers => "lookupTransfers",
        .get_account_transfers => "getAccountTransfers",
        .get_account_balances => "getAccountBalances",
        .query_accounts => "queryAccounts",
        .query_transfers => "queryTransfers",
        .close_client, .sleep_ms => unreachable,
    };
}

// A copy of `IntegrationTest`'s server harness
fn emit_server(printer: *Printer) !void {
    try printer.write_empty_line();
    try printer.write_indented("private static class Server implements AutoCloseable {");
    printer.indent();
    try printer.write_indented(
        "public static final String TB_SERVER = \"../../../zig-out/bin/tigerbeetle\";",
    );
    try printer.write_empty_line();
    try printer.write_indented("public final String tb_file;");
    try printer.write_indented("private final Process process;");
    try printer.write_indented("private String address;");
    try printer.write_empty_line();
    try printer.write_indented("public Server(final String label) throws Exception {");
    printer.indent();
    try printer.write_indented("this.tb_file = \"./0_0.tigerbeetle.\" + label;");
    try printer.write_empty_line();
    try printer.write_indented("cleanUp();");
    try printer.write_empty_line();
    try printer.write_indented("String exe;");
    try printer.write_indented("switch (JNILoader.OS.getOS()) {");
    printer.indent();
    try printer.write_indented("case windows:");
    printer.indent();
    try printer.write_indented("exe = TB_SERVER + \".exe\";");
    try printer.write_indented("break;");
    printer.dedent();
    try printer.write_indented("default:");
    printer.indent();
    try printer.write_indented("exe = TB_SERVER;");
    try printer.write_indented("break;");
    printer.dedent();
    printer.dedent();
    try printer.write_indented("}");
    try printer.write_empty_line();
    try printer.write_indented(
        "final var format = Runtime.getRuntime().exec(new String[] {exe, \"format\", " ++
            "\"--cluster=0\",",
    );
    printer.indent();
    printer.indent();
    try printer.write_indented(
        "\"--replica=0\", \"--replica-count=1\", \"--development\", tb_file});",
    );
    printer.dedent();
    printer.dedent();
    try printer.write_indented("if (format.waitFor() != 0) {");
    printer.indent();
    try printer.write_indented("final var reader =");
    printer.indent();
    printer.indent();
    try printer.write_indented(
        "new BufferedReader(new InputStreamReader(format.getErrorStream()));",
    );
    printer.dedent();
    printer.dedent();
    try printer.write_indented(
        "final var error = reader.lines().collect(Collectors.joining(\". \"));",
    );
    try printer.write_indented("throw new Exception(\"Format failed. \" + error);");
    printer.dedent();
    try printer.write_indented("}");
    try printer.write_empty_line();
    try printer.write_indented("this.process = new ProcessBuilder()");
    printer.indent();
    printer.indent();
    try printer.write_indented(
        ".command(new String[] {exe, \"start\", \"--addresses=0\", \"--development\", tb_file})",
    );
    try printer.write_indented(
        ".redirectOutput(Redirect.PIPE).redirectError(Redirect.INHERIT).start();",
    );
    printer.dedent();
    printer.dedent();
    try printer.write_empty_line();
    try printer.write_indented("final var stdout = process.getInputStream();");
    try printer.write_indented(
        "try (final var reader = new BufferedReader(new InputStreamReader(stdout))) {",
    );
    printer.indent();
    try printer.write_indented("this.address = reader.readLine().trim();");
    printer.dedent();
    try printer.write_indented("}");
    printer.dedent();
    try printer.write_indented("}");
    try printer.write_empty_line();
    try printer.write_indented("public String getAddress() {");
    printer.indent();
    try printer.write_indented("return address;");
    printer.dedent();
    try printer.write_indented("}");
    try printer.write_empty_line();
    try printer.write_indented("@Override");
    try printer.write_indented("public void close() throws Exception {");
    printer.indent();
    try printer.write_indented("cleanUp();");
    printer.dedent();
    try printer.write_indented("}");
    try printer.write_empty_line();
    try printer.write_indented("private void cleanUp() throws Exception {");
    printer.indent();
    try printer.write_indented("try {");
    printer.indent();
    try printer.write_indented("if (process != null && process.isAlive()) {");
    printer.indent();
    try printer.write_indented("process.destroy();");
    printer.dedent();
    try printer.write_indented("}");
    try printer.write_empty_line();
    try printer.write_indented("final var file = new File(\"./\" + tb_file);");
    try printer.write_indented("file.delete();");
    printer.dedent();
    try printer.write_indented("} catch (Throwable any) {");
    printer.indent();
    try printer.write_indented("throw new Exception(\"Cleanup has failed\");");
    printer.dedent();
    try printer.write_indented("}");
    printer.dedent();
    try printer.write_indented("}");
    printer.dedent();
    try printer.write_indented("}");
}
