const std = @import("std");
const assert = std.debug.assert;

const conformance = @import("conformance");

const types = conformance.types;
const utils = conformance.utils;

const indent_width = 4;
const member_indent_level = 1; // class > member
const statement_indent_level = 2; // class > method > statement
const line_width_max = 100;

// Mirrors `big_integer.fields` in `java_bindings.zig` — fields here become
// `BigInteger`, others `byte[]`. Maybe enforce at comptime later
const big_integer_fields = [_][]const u8{
    "credits_posted",
    "credits_pending",
    "debits_posted",
    "debits_pending",
    "amount",
};

pub fn main() !void {
    var arena_instance = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena_instance.deinit();
    const arena = arena_instance.allocator();

    const tests = try conformance.parse(arena);

    var buffer = std.ArrayList(u8).init(arena);
    try emit(arena, buffer.writer().any(), tests);
    try std.io.getStdOut().writeAll(buffer.items);
}

fn satisfies(requirement: types.Case.Requirement) bool {
    return switch (requirement) {
        .requires_unbounded_integers => false,
    };
}

fn emit(arena: std.mem.Allocator, writer: std.io.AnyWriter, tests: types.ConformanceTests) !void {
    try writer.writeAll(
        \\// This file was auto-generated by java_conformance.zig.
        \\// Do not manually modify.
        \\
        \\package com.tigerbeetle;
        \\
        \\import java.io.BufferedReader;
        \\import java.io.File;
        \\import java.io.InputStreamReader;
        \\import java.lang.ProcessBuilder.Redirect;
        \\import java.math.BigInteger;
        \\import java.time.Duration;
        \\import java.util.HashSet;
        \\import java.util.stream.Collectors;
        \\
        \\import org.junit.After;
        \\import org.junit.AfterClass;
        \\import org.junit.Before;
        \\import org.junit.BeforeClass;
        \\import org.junit.Test;
        \\import static org.junit.Assert.assertArrayEquals;
        \\import static org.junit.Assert.assertEquals;
        \\import static org.junit.Assert.assertThrows;
        \\import static org.junit.Assert.assertTrue;
        \\
        \\public class ConformanceTest {
        \\    private static final byte[] clusterId = new byte[16];
        \\
        \\    private static Server server;
        \\
        \\    private Client client;
        \\
        \\    @BeforeClass
        \\    public static void initialize() throws Exception {
        \\        server = new Server("conformance");
        \\    }
        \\
        \\    @AfterClass
        \\    public static void cleanup() throws Exception {
        \\        server.close();
        \\    }
        \\
        \\    @Before
        \\    public void createClient() throws Exception {
        \\        client = new Client(clusterId, new String[] {server.getAddress()});
        \\    }
        \\
        \\    @After
        \\    public void closeClient() throws Exception {
        \\        client.close();
        \\    }
        \\
    );
    for (tests.suites) |suite| {
        try writer.writeAll("\n");
        try write_indent(writer, member_indent_level);
        try writer.print("// Suite: {s}\n", .{suite.name});
        for (suite.cases) |case| {
            try writer.writeAll("\n");
            if (case.requirement) |requirement| {
                if (!satisfies(requirement)) {
                    try emit_omission(writer, suite, case, requirement);
                    continue;
                }
            }
            try write_indent(writer, member_indent_level);
            try writer.writeAll("@Test\n");
            try write_indent(writer, member_indent_level);
            var name = std.ArrayList(u8).init(arena);
            try name.appendSlice("public void test");
            try emit_method_name(name.writer().any(), suite.name);
            try emit_method_name(name.writer().any(), case.description);
            try name.appendSlice("()");
            // Eclipse breaks a signature that overflows before `throws`.
            if (member_indent_level * indent_width + name.items.len +
                " throws Exception {".len > line_width_max)
            {
                try writer.print("{s}\n", .{name.items});
                try write_indent(writer, member_indent_level + 2);
                try writer.writeAll("throws Exception {\n");
            } else {
                try writer.print("{s} throws Exception {{\n", .{name.items});
            }
            try emit_case(arena, writer, case);
            try write_indent(writer, member_indent_level);
            try writer.writeAll("}\n");
        }
    }
    try emit_server(writer);
    try writer.writeAll("}\n");
}

fn emit_case(
    arena: std.mem.Allocator,
    writer: std.io.AnyWriter,
    case: types.Case,
) !void {
    var scope = Scope.init(arena);
    var emitted = false;
    const consumed = try arena.alloc(bool, case.steps.len);
    @memset(consumed, false);
    for (case.steps, 0..) |step, index| {
        if (consumed[index]) continue;
        if (emitted and starts_operation(step)) try writer.writeAll("\n");
        if (step == .binding and step.binding.value == .index and
            !scope.id_arrays.contains(step.binding.value.index.reference))
        {
            try emit_row_group(writer, &scope, case.steps, index, consumed);
        } else {
            try emit_step(writer, &scope, step);
        }
        emitted = true;
    }
}

// Each request and the statements that build and check it form a paragraph, the way the
// hand-written integration tests are laid out.
fn starts_operation(step: types.Step) bool {
    return switch (step) {
        .call => true,
        .binding => |binding| binding.value == .call,
        .assertion => |assertion| assertion == .fail,
    };
}

// Java has no row type: a result batch is its own cursor. So an indexed binding never becomes a
// local. The rows a case names are walked with `next()`, each row's assertions grouped behind its
// own advance, the way `IntegrationTest` reads a batch.
fn emit_row_group(
    writer: std.io.AnyWriter,
    scope: *Scope,
    steps: []const types.Step,
    start: usize,
    consumed: []bool,
) !void {
    const arena = scope.arena;
    const origin = steps[start].binding.value.index;
    const batch = try utils.to_case(arena, .camelCase, origin.reference);

    var rows = std.ArrayList([]const u8).init(arena);
    for (steps[start..], start..) |step, index| {
        if (step != .binding or step.binding.value != .index) continue;
        if (!std.mem.eql(u8, step.binding.value.index.reference, origin.reference)) continue;
        assert(step.binding.value.index.index == rows.items.len);
        try rows.append(step.binding.name);
        consumed[index] = true;
    }

    try scope.walk(writer, batch);
    for (rows.items) |row| {
        try write_indent(writer, statement_indent_level);
        try writer.print("assertTrue({s}.next());\n", .{batch});
        for (steps, 0..) |step, index| {
            if (step != .assertion) continue;
            var comparison: types.Assertion.FieldComparison = undefined;
            var greater_than = false;
            switch (step.assertion) {
                .equal_field => |value| comparison = value,
                .greater_than => |value| {
                    comparison = value;
                    greater_than = true;
                },
                else => continue,
            }
            if (!std.mem.eql(u8, comparison.reference, row)) continue;
            consumed[index] = true;

            const property = try utils.to_case(arena, .PascalCase, comparison.field.name);
            const value = try render_field_value(arena, comparison.field);
            try write_indent(writer, statement_indent_level);
            if (greater_than) {
                try writer.print("assertTrue({s}.get{s}() > {s});\n", .{ batch, property, value });
            } else {
                try writer.print("{s}({s}, {s}.get{s}());\n", .{
                    assert_function(comparison.field),
                    value,
                    batch,
                    property,
                });
            }
        }
    }
}

// Bound record literals are inlined at each use, since Java has no standalone event type: a
// record only exists as a row of a batch. Generated ids are hoisted to locals first, so a record
// reused across two calls carries the same id both times.
const Scope = struct {
    arena: std.mem.Allocator,
    records: std.StringHashMap(types.Record),
    id_arrays: std.StringHashMap(void),
    walked: std.StringHashMap(void),

    fn init(arena: std.mem.Allocator) Scope {
        return .{
            .arena = arena,
            .records = std.StringHashMap(types.Record).init(arena),
            .id_arrays = std.StringHashMap(void).init(arena),
            .walked = std.StringHashMap(void).init(arena),
        };
    }

    // A batch is a cursor, so a second pass over one has to rewind first.
    fn walk(scope: *Scope, writer: std.io.AnyWriter, batch: []const u8) !void {
        const entry = try scope.walked.getOrPut(batch);
        if (!entry.found_existing) return;
        try write_indent(writer, statement_indent_level);
        try writer.print("{s}.beforeFirst();\n", .{batch});
    }
};

fn emit_step(writer: std.io.AnyWriter, scope: *Scope, step: types.Step) !void {
    switch (step) {
        .binding => |binding| try emit_binding(writer, scope, binding),
        .call => |call| try emit_call(writer, scope, call, .{}),
        .assertion => |assertion| try emit_assertion(writer, scope, assertion),
    }
}

fn emit_binding(writer: std.io.AnyWriter, scope: *Scope, binding: types.Binding) !void {
    const arena = scope.arena;
    const name = try utils.to_case(arena, .camelCase, binding.name);
    switch (binding.value) {
        .generate_id => {
            try write_indent(writer, statement_indent_level);
            try writer.print("final var {s} = UInt128.id();\n", .{name});
        },
        .generate_ids => |count| {
            try scope.id_arrays.put(binding.name, {});
            try write_indent(writer, statement_indent_level);
            try writer.print("final var {s} = new byte[{d}][];\n", .{ name, count });
            try write_indent(writer, statement_indent_level);
            try writer.print("for (int index = 0; index < {d}; index++) {{\n", .{count});
            try write_indent(writer, statement_indent_level + 1);
            try writer.print("{s}[index] = UInt128.id();\n", .{name});
            try write_indent(writer, statement_indent_level);
            try writer.writeAll("}\n");
        },
        .index => |index| {
            const reference = try utils.to_case(arena, .camelCase, index.reference);
            try write_indent(writer, statement_indent_level);
            try writer.print("final var {s} = {s}[{d}];\n", .{ name, reference, index.index });
        },
        .record => |record| switch (record.type) {
            .U128 => {
                assert(record.fields.len == 1);
                const value = try render_uint128(arena, record.fields[0].value.integer);
                try emit_assignment(writer, statement_indent_level, name, value);
            },
            .Account, .Transfer => {
                try scope.records.put(binding.name, try hoist_record(writer, scope, name, record));
            },
            // Flags cannot be bound on their own, and result types are never written by hand.
            .AccountBalance,
            .AccountFilter,
            .AccountFilterFlags,
            .AccountFlags,
            .CreateAccountResult,
            .CreateTransferResult,
            .QueryFilter,
            .QueryFilterFlags,
            .TransferFlags,
            => unreachable,
        },
        .call => |call| try emit_call(writer, scope, call, .{ .binding = name }),
        .integer, .boolean, .enum_literal, .reference => unreachable,
    }
}

// Emits a local for every generated id in the record, returning the record with those fields
// rewritten to reference the local.
fn hoist_record(
    writer: std.io.AnyWriter,
    scope: *Scope,
    name: []const u8,
    record: types.Record,
) !types.Record {
    const arena = scope.arena;
    const fields = try arena.alloc(types.Field, record.fields.len);
    for (record.fields, 0..) |field, index| {
        if (field.value != .generate_id) {
            fields[index] = field;
            continue;
        }
        const local = try std.fmt.allocPrint(arena, "{s}{s}", .{
            name,
            try utils.to_case(arena, .PascalCase, field.name),
        });
        try write_indent(writer, statement_indent_level);
        try writer.print("final var {s} = UInt128.id();\n", .{local});
        fields[index] = .{ .name = field.name, .value = .{ .reference = local }, .type = field.type };
    }
    return .{ .type = record.type, .fields = fields };
}

fn emit_call(
    writer: std.io.AnyWriter,
    scope: *Scope,
    call: types.Call,
    options: struct {
        binding: ?[]const u8 = null,
        expect_error: bool = false,
    },
) !void {
    if (call.concurrency > 1) {
        assert(options.binding == null);
        // A `RuntimeException` thrown from `Thread.run()` is delivered to the uncaught
        // handler and dropped, so each thread captures into `exceptions` for a post-join
        // rethrow — the same shape as `IntegrationTest.TransferTask` storing `.exception`.
        try write_indent(writer, statement_indent_level);
        try writer.print("final var threads = new Thread[{d}];\n", .{call.concurrency});
        try write_indent(writer, statement_indent_level);
        try writer.print("final var exceptions = new Exception[{d}];\n", .{call.concurrency});
        try write_indent(writer, statement_indent_level);
        try writer.print(
            "for (int index = 0; index < {d}; index++) {{\n",
            .{call.concurrency},
        );
        try write_indent(writer, statement_indent_level + 1);
        try writer.writeAll("final var threadIndex = index;\n");
        try write_indent(writer, statement_indent_level + 1);
        try writer.writeAll("threads[index] = new Thread(() -> {\n");
        try write_indent(writer, statement_indent_level + 2);
        try writer.writeAll("try {\n");

        var thread_scope = Scope.init(scope.arena);
        try emit_operation(writer, &thread_scope, call, .{
            .indent_level = statement_indent_level + 3,
            .error_action = .rethrow,
        });

        try write_indent(writer, statement_indent_level + 2);
        try writer.writeAll("} catch (Exception exception) {\n");
        try write_indent(writer, statement_indent_level + 3);
        try writer.writeAll("exceptions[threadIndex] = exception;\n");
        try write_indent(writer, statement_indent_level + 2);
        try writer.writeAll("}\n");
        try write_indent(writer, statement_indent_level + 1);
        try writer.writeAll("});\n");
        try write_indent(writer, statement_indent_level + 1);
        try writer.writeAll("threads[index].start();\n");
        try write_indent(writer, statement_indent_level);
        try writer.writeAll("}\n");
        try write_indent(writer, statement_indent_level);
        try writer.writeAll("for (final var thread : threads) {\n");
        try write_indent(writer, statement_indent_level + 1);
        try writer.writeAll("thread.join(Duration.ofSeconds(60).toMillis());\n");
        try write_indent(writer, statement_indent_level + 1);
        try writer.writeAll(
            "assertTrue(\"Worker did not terminate within 60 seconds\", !thread.isAlive());\n",
        );
        try write_indent(writer, statement_indent_level);
        try writer.writeAll("}\n");
        try write_indent(writer, statement_indent_level);
        try writer.writeAll("for (final var exception : exceptions) {\n");
        try write_indent(writer, statement_indent_level + 1);
        try writer.writeAll("if (exception != null)\n");
        try write_indent(writer, statement_indent_level + 2);
        try writer.writeAll("throw exception;\n");
        try write_indent(writer, statement_indent_level);
        try writer.writeAll("}\n");
        return;
    }

    try emit_operation(writer, scope, call, .{
        .indent_level = statement_indent_level,
        .binding = options.binding,
        .error_action = if (options.expect_error) .expected else .propagate,
    });
}

const ErrorAction = enum { propagate, rethrow, expected };

fn emit_operation(
    writer: std.io.AnyWriter,
    scope: *Scope,
    call: types.Call,
    options: struct {
        indent_level: u32,
        binding: ?[]const u8 = null,
        error_action: ErrorAction,
    },
) !void {
    switch (call.name) {
        .close_client => {
            assert(options.binding == null);
            try write_indent(writer, options.indent_level);
            try writer.writeAll("client.close();\n");
            return;
        },
        .sleep_ms => {
            assert(options.binding == null);
            assert(call.arguments.len == 1);
            try write_indent(writer, options.indent_level);
            try writer.print("Thread.sleep({s});\n", .{call.arguments[0].integer});
            return;
        },
        else => {},
    }

    // A call whose result the corpus binds names its input after that binding; one whose result
    // is discarded gets a block, so the plain name is free to repeat.
    const scoped = options.binding == null;
    const indent_level = options.indent_level + @intFromBool(scoped);
    if (scoped) {
        try write_indent(writer, options.indent_level);
        try writer.writeAll("{\n");
    }

    // The argument is built into a local first, so that `assertThrows` can capture it: a lambda
    // may only close over effectively final locals.
    const argument = try emit_argument(writer, scope, call, indent_level, options.binding);

    try write_indent(writer, indent_level);
    if (options.error_action == .expected) {
        try writer.print("assertThrows(Exception.class, () -> client.{s}({s}));\n", .{
            java_operation_name(call.name),
            argument,
        });
    } else {
        if (options.binding) |binding| try writer.print("final var {s} = ", .{binding});
        try writer.print("client.{s}({s});\n", .{ java_operation_name(call.name), argument });
    }

    if (scoped) {
        try write_indent(writer, options.indent_level);
        try writer.writeAll("}\n");
    }
}

fn local_name(
    arena: std.mem.Allocator,
    binding: ?[]const u8,
    suffix: []const u8,
    unbound: []const u8,
) ![]const u8 {
    const name = binding orelse return unbound;
    return std.fmt.allocPrint(arena, "{s}{s}", .{ name, suffix });
}

fn emit_argument(
    writer: std.io.AnyWriter,
    scope: *Scope,
    call: types.Call,
    indent_level: u32,
    binding: ?[]const u8,
) ![]const u8 {
    const arena = scope.arena;
    switch (call.name) {
        .create_accounts, .create_transfers => {
            const accounts = call.name == .create_accounts;
            const batch_type = if (accounts) "AccountBatch" else "TransferBatch";
            const name = try local_name(
                arena,
                binding,
                "Batch",
                if (accounts) "accountsBatch" else "transfersBatch",
            );
            try write_indent(writer, indent_level);
            try writer.print("final var {s} = new {s}({d});\n", .{
                name,
                batch_type,
                call.arguments.len,
            });
            for (call.arguments) |argument| {
                const record = switch (argument) {
                    .record => |record| record,
                    .reference => |reference| scope.records.get(reference).?,
                    else => unreachable,
                };
                try emit_record_into(writer, arena, record, name, indent_level);
            }
            return name;
        },
        .lookup_accounts, .lookup_transfers => {
            const name = try local_name(arena, binding, "Batch", "idsBatch");
            try write_indent(writer, indent_level);
            try writer.print("final var {s} = new IdBatch({d});\n", .{ name, call.arguments.len });
            for (call.arguments) |argument| {
                try write_indent(writer, indent_level);
                try writer.print("{s}.add({s});\n", .{ name, try render_id(arena, argument) });
            }
            return name;
        },
        .get_account_transfers, .get_account_balances, .query_accounts, .query_transfers => {
            assert(call.arguments.len == 1);
            const filter = call.arguments[0].record;
            const name = try local_name(arena, binding, "Filter", "filter");
            try write_indent(writer, indent_level);
            try writer.print("final var {s} = new {s}();\n", .{ name, @tagName(filter.type) });
            for (filter.fields) |field| {
                try emit_filter_field(writer, arena, field, name, indent_level);
            }
            return name;
        },
        .close_client, .sleep_ms => unreachable,
    }
}

fn emit_record_into(
    writer: std.io.AnyWriter,
    arena: std.mem.Allocator,
    record: types.Record,
    batch: []const u8,
    indent_level: u32,
) !void {
    try write_indent(writer, indent_level);
    try writer.print("{s}.add();\n", .{batch});
    for (record.fields) |field| {
        try emit_setter(
            writer,
            indent_level,
            batch,
            try utils.to_case(arena, .PascalCase, field.name),
            try render_field_value(arena, field),
        );
    }
}

// Filters expose their flags as boolean setters (`setDebits(true)`) rather than a flags word.
fn emit_filter_field(
    writer: std.io.AnyWriter,
    arena: std.mem.Allocator,
    field: types.Field,
    name: []const u8,
    indent_level: u32,
) !void {
    if (field.value == .record and types.Record.is_flags(field.value.record.type)) {
        for (field.value.record.fields) |flag| {
            assert(flag.value == .boolean and flag.value.boolean);
            try write_indent(writer, indent_level);
            try writer.print("{s}.set{s}(true);\n", .{
                name,
                try utils.to_case(arena, .PascalCase, flag.name),
            });
        }
        return;
    }
    try emit_setter(
        writer,
        indent_level,
        name,
        try utils.to_case(arena, .PascalCase, field.name),
        try render_field_value(arena, field),
    );
}

// Eclipse breaks an over-long statement onto a continuation line indented two levels further.
fn emit_assignment(
    writer: std.io.AnyWriter,
    indent_level: u32,
    name: []const u8,
    value: []const u8,
) !void {
    const width = indent_level * indent_width + "final var ".len + name.len +
        " = ".len + value.len + ";".len;
    try write_indent(writer, indent_level);
    if (width <= line_width_max) {
        try writer.print("final var {s} = {s};\n", .{ name, value });
        return;
    }
    try writer.print("final var {s} =\n", .{name});
    try write_indent(writer, indent_level + 2);
    try writer.print("{s};\n", .{value});
}

fn emit_setter(
    writer: std.io.AnyWriter,
    indent_level: u32,
    target: []const u8,
    property: []const u8,
    value: []const u8,
) !void {
    const width = indent_level * indent_width + target.len + ".set".len + property.len +
        "(".len + value.len + ");".len;
    try write_indent(writer, indent_level);
    if (width <= line_width_max) {
        try writer.print("{s}.set{s}({s});\n", .{ target, property, value });
        return;
    }

    // A flags word is the only setter argument that overflows; Eclipse breaks before each `|`.
    var count: usize = 1;
    var counter = std.mem.splitSequence(u8, value, " | ");
    _ = counter.first();
    while (counter.next()) |_| count += 1;

    var operands = std.mem.splitSequence(u8, value, " | ");
    try writer.print("{s}.set{s}({s}\n", .{ target, property, operands.first() });
    var index: usize = 1;
    while (operands.next()) |operand| : (index += 1) {
        try write_indent(writer, indent_level + 2);
        try writer.print("| {s}{s}\n", .{ operand, if (index + 1 == count) ");" else "" });
    }
}

fn emit_assertion(writer: std.io.AnyWriter, scope: *Scope, assertion: types.Assertion) !void {
    const arena = scope.arena;
    switch (assertion) {
        .equal => |equal| {
            const actual = try utils.to_case(arena, .camelCase, equal.actual);
            try write_indent(writer, statement_indent_level);
            try writer.print("assertEquals({d}, {s}.getLength());\n", .{
                equal.expected.len,
                actual,
            });
            try scope.walk(writer, actual);
            for (equal.expected) |record| {
                try write_indent(writer, statement_indent_level);
                try writer.print("assertTrue({s}.next());\n", .{actual});
                for (record.fields) |field| {
                    try emit_field_equal(writer, arena, field, actual);
                }
            }
        },
        .empty => |actual| {
            try write_indent(writer, statement_indent_level);
            try writer.print("assertEquals(0, {s}.getLength());\n", .{
                try utils.to_case(arena, .camelCase, actual),
            });
        },
        .unique => |ids| {
            const name = try utils.to_case(arena, .camelCase, ids);
            try write_indent(writer, statement_indent_level);
            try writer.writeAll("final var seen = new HashSet<BigInteger>();\n");
            try write_indent(writer, statement_indent_level);
            try writer.print("for (final var id : {s}) {{\n", .{name});
            try write_indent(writer, statement_indent_level + 1);
            try writer.writeAll("assertTrue(seen.add(UInt128.asBigInteger(id)));\n");
            try write_indent(writer, statement_indent_level);
            try writer.writeAll("}\n");
        },
        .ascending => |ids| {
            const name = try utils.to_case(arena, .camelCase, ids);
            try write_indent(writer, statement_indent_level);
            try writer.print("for (int index = 1; index < {s}.length; index++) {{\n", .{name});
            try write_indent(writer, statement_indent_level + 1);
            try writer.print(
                "assertTrue(UInt128.asBigInteger({s}[index - 1])\n",
                .{name},
            );
            try write_indent(writer, statement_indent_level + 3);
            try writer.print(".compareTo(UInt128.asBigInteger({s}[index])) < 0);\n", .{name});
            try write_indent(writer, statement_indent_level);
            try writer.writeAll("}\n");
        },
        .equal_field => |comparison| {
            const expected = try render_field_value(arena, comparison.field);
            try write_indent(writer, statement_indent_level);
            try writer.print("{s}({s}, {s});\n", .{
                assert_function(comparison.field),
                expected,
                try render_field_reference(arena, comparison),
            });
        },
        .greater_than => |comparison| {
            try write_indent(writer, statement_indent_level);
            try writer.print("assertTrue({s} > {s});\n", .{
                try render_field_reference(arena, comparison),
                try render_field_value(arena, comparison.field),
            });
        },
        .fail => |call| try emit_call(writer, scope, call, .{ .expect_error = true }),
    }
}

fn emit_field_equal(
    writer: std.io.AnyWriter,
    arena: std.mem.Allocator,
    field: types.Field,
    actual: []const u8,
) !void {
    try write_indent(writer, statement_indent_level);
    try writer.print("{s}({s}, {s}.get{s}());\n", .{
        assert_function(field),
        try render_field_value(arena, field),
        actual,
        try utils.to_case(arena, .PascalCase, field.name),
    });
}

fn assert_function(field: types.Field) []const u8 {
    if (is_byte_array(field)) return "assertArrayEquals";
    return "assertEquals";
}

fn is_byte_array(field: types.Field) bool {
    if (field.type != .int or field.type.int != 128) return false;
    return !is_big_integer(field.name);
}

fn is_big_integer(field_name: []const u8) bool {
    for (big_integer_fields) |name| {
        if (std.mem.eql(u8, name, field_name)) return true;
    }
    return false;
}

fn render_field_reference(
    arena: std.mem.Allocator,
    comparison: types.Assertion.FieldComparison,
) ![]const u8 {
    return std.fmt.allocPrint(arena, "{s}.get{s}()", .{
        try utils.to_case(arena, .camelCase, comparison.reference),
        try utils.to_case(arena, .PascalCase, comparison.field.name),
    });
}

fn render_field_value(arena: std.mem.Allocator, field: types.Field) ![]const u8 {
    switch (field.value) {
        .enum_literal => |literal| {
            return std.fmt.allocPrint(arena, "{s}.{s}", .{
                field.type.enum_name,
                try utils.to_case(arena, .PascalCase, literal),
            });
        },
        .record => |flags| {
            assert(types.Record.is_flags(flags.type));
            var text = std.ArrayList(u8).init(arena);
            for (flags.fields, 0..) |flag, index| {
                assert(flag.value == .boolean and flag.value.boolean);
                if (index > 0) try text.appendSlice(" | ");
                try text.writer().print("{s}.{s}", .{
                    @tagName(flags.type),
                    try utils.to_case(arena, .UPPER_CASE, flag.name),
                });
            }
            return text.items;
        },
        .integer => |text| {
            const bits = field.type.int;
            if (bits == 128) {
                if (is_big_integer(field.name)) return render_big_integer(arena, text);
                return render_uint128(arena, text);
            }
            // A 64-bit literal overflows Java's `int` without the suffix.
            if (bits == 64) return std.fmt.allocPrint(arena, "{s}L", .{text});
            return text;
        },
        .generate_id => return "UInt128.id()",
        .reference => |name| return utils.to_case(arena, .camelCase, name),
        .index => |index| {
            return std.fmt.allocPrint(arena, "{s}[{d}]", .{
                try utils.to_case(arena, .camelCase, index.reference),
                index.index,
            });
        },
        .boolean => |value| return if (value) "true" else "false",
        .call, .generate_ids => unreachable,
    }
}

// Ids reach the client as `byte[]`, whatever shape they take in the corpus.
fn render_id(arena: std.mem.Allocator, expression: types.Expression) ![]const u8 {
    switch (expression) {
        .generate_id => return "UInt128.id()",
        .reference => |name| return utils.to_case(arena, .camelCase, name),
        .integer => |text| return render_uint128(arena, text),
        .index => |index| {
            return std.fmt.allocPrint(arena, "{s}[{d}]", .{
                try utils.to_case(arena, .camelCase, index.reference),
                index.index,
            });
        },
        .call, .generate_ids, .record, .boolean, .enum_literal => unreachable,
    }
}

fn render_uint128(arena: std.mem.Allocator, text: []const u8) ![]const u8 {
    const value = std.fmt.parseInt(u128, text, 10) catch unreachable;
    if (value <= std.math.maxInt(u64)) {
        return std.fmt.allocPrint(arena, "UInt128.asBytes({d}L)", .{value});
    }
    return std.fmt.allocPrint(arena, "UInt128.asBytes(new BigInteger(\"{d}\"))", .{value});
}

fn render_big_integer(arena: std.mem.Allocator, text: []const u8) ![]const u8 {
    const value = std.fmt.parseInt(u128, text, 10) catch unreachable;
    if (value <= std.math.maxInt(u64)) {
        return std.fmt.allocPrint(arena, "BigInteger.valueOf({d}L)", .{value});
    }
    return std.fmt.allocPrint(arena, "new BigInteger(\"{d}\")", .{value});
}

fn java_operation_name(name: types.Call.Name) []const u8 {
    return switch (name) {
        .create_accounts => "createAccounts",
        .create_transfers => "createTransfers",
        .lookup_accounts => "lookupAccounts",
        .lookup_transfers => "lookupTransfers",
        .get_account_transfers => "getAccountTransfers",
        .get_account_balances => "getAccountBalances",
        .query_accounts => "queryAccounts",
        .query_transfers => "queryTransfers",
        .close_client, .sleep_ms => unreachable,
    };
}

fn emit_omission(
    writer: std.io.AnyWriter,
    suite: types.Suite,
    case: types.Case,
    requirement: types.Case.Requirement,
) !void {
    try write_indent(writer, member_indent_level);
    try writer.print("// Omitted: {s}_", .{suite.name});
    try emit_test_name(writer, case.description);
    try writer.writeAll("\n");
    try write_indent(writer, member_indent_level);
    try writer.writeAll("// Reason: ");
    for (@tagName(requirement)) |char| {
        try writer.writeByte(if (char == '_') ' ' else char);
    }
    try writer.writeAll("\n");
}

// Collapses anything that isn't alphanumeric into a single underscore.
fn emit_test_name(writer: std.io.AnyWriter, description: []const u8) !void {
    var last_was_underscore = false;
    for (description) |char| {
        if (std.ascii.isAlphanumeric(char)) {
            try writer.writeByte(char);
            last_was_underscore = false;
        } else if (!last_was_underscore) {
            try writer.writeByte('_');
            last_was_underscore = true;
        }
    }
}

// Java method names are camelCase, so each word of the description is capitalised in place.
fn emit_method_name(writer: std.io.AnyWriter, text: []const u8) !void {
    var capitalize = true;
    for (text) |char| {
        if (!std.ascii.isAlphanumeric(char)) {
            capitalize = true;
            continue;
        }
        if (capitalize) {
            try writer.writeByte(std.ascii.toUpper(char));
            capitalize = false;
        } else {
            try writer.writeByte(char);
        }
    }
}

fn write_indent(writer: std.io.AnyWriter, indent_level: u32) !void {
    try writer.writeByteNTimes(' ', indent_level * indent_width);
}

// A copy of `IntegrationTest`'s server harness
fn emit_server(writer: std.io.AnyWriter) !void {
    try writer.writeAll(
        \\
        \\    private static class Server implements AutoCloseable {
        \\        public static final String TB_SERVER = "../../../zig-out/bin/tigerbeetle";
        \\
        \\        public final String tb_file;
        \\        private final Process process;
        \\        private String address;
        \\
        \\        public Server(final String label) throws Exception {
        \\            this.tb_file = "./0_0.tigerbeetle." + label;
        \\
        \\            cleanUp();
        \\
        \\            String exe;
        \\            switch (JNILoader.OS.getOS()) {
        \\                case windows:
        \\                    exe = TB_SERVER + ".exe";
        \\                    break;
        \\                default:
        \\                    exe = TB_SERVER;
        \\                    break;
        \\            }
        \\
        \\            final var format = Runtime.getRuntime().exec(new String[] {exe, "format", "--cluster=0",
        \\                    "--replica=0", "--replica-count=1", "--development", tb_file});
        \\            if (format.waitFor() != 0) {
        \\                final var reader =
        \\                        new BufferedReader(new InputStreamReader(format.getErrorStream()));
        \\                final var error = reader.lines().collect(Collectors.joining(". "));
        \\                throw new Exception("Format failed. " + error);
        \\            }
        \\
        \\            this.process = new ProcessBuilder()
        \\                    .command(new String[] {exe, "start", "--addresses=0", "--development", tb_file})
        \\                    .redirectOutput(Redirect.PIPE).redirectError(Redirect.INHERIT).start();
        \\
        \\            final var stdout = process.getInputStream();
        \\            try (final var reader = new BufferedReader(new InputStreamReader(stdout))) {
        \\                this.address = reader.readLine().trim();
        \\            }
        \\        }
        \\
        \\        public String getAddress() {
        \\            return address;
        \\        }
        \\
        \\        @Override
        \\        public void close() throws Exception {
        \\            cleanUp();
        \\        }
        \\
        \\        private void cleanUp() throws Exception {
        \\            try {
        \\                if (process != null && process.isAlive()) {
        \\                    process.destroy();
        \\                }
        \\
        \\                final var file = new File("./" + tb_file);
        \\                file.delete();
        \\            } catch (Throwable any) {
        \\                throw new Exception("Cleanup has failed");
        \\            }
        \\        }
        \\    }
        \\
    );
}
