const std = @import("std");
const assert = std.debug.assert;

const conformance = @import("conformance");

const ast = conformance.ast;
const Printer = conformance.Printer;

pub fn main() !void {
    var stdout = std.io.bufferedWriter(std.io.getStdOut().writer());
    const stdout_writer = stdout.writer();
    var memory: [Printer.default_memory_size]u8 = undefined;
    var printer = Printer.init(&memory, stdout_writer.any(), .{
        .indent_width = 4,
        .comment_marker = "#",
    });

    const tests = try conformance.parse(printer.arena());

    try emit(&printer, tests);
    try stdout.flush();
}

fn satisfies(requirement: ast.Case.Requirement) bool {
    return switch (requirement) {
        // Python's int is arbitrary precision, and float is accepted where int is expected.
        .requires_unbounded_integers => true,
        .requires_fractional_amounts => true,
    };
}

const ClientVariant = enum { synchronous, asynchronous };

fn emit(printer: *Printer, tests: ast.ConformanceTests) !void {
    try printer.write(
        \\############################################################
        \\## This file was auto-generated by python_conformance.zig ##
        \\##               Do not manually modify.                  ##
        \\############################################################
        \\
        \\import asyncio
        \\import functools
        \\import inspect
        \\import os
        \\import sys
        \\import threading
        \\import time
        \\
        \\import pytest
        \\
        \\import tigerbeetle as tb
        \\
        \\replica_addresses = os.getenv("TB_ADDRESS")
        \\if not replica_addresses:
        \\    print("error: missing TB_ADDRESS environment variable")
        \\    sys.exit(1)
        \\
    );
    for (std.enums.values(ClientVariant)) |variant| {
        try printer.write_empty_line();
        try printer.write(switch (variant) {
            .synchronous =>
            \\#################
            \\## Sync client ##
            \\#################
            \\
            \\@pytest.fixture
            \\def client():
            \\    client = tb.ClientSync(cluster_id=0, replica_addresses=replica_addresses)
            \\    yield client
            \\    # Workaround until #3943 has been merged.
            \\    if client._client_key in tb.ClientSync._clients:
            \\        client.close()
            \\
            ,
            .asynchronous =>
            \\##################
            \\## Async client ##
            \\##################
            \\
            \\def async_test(case):
            \\    @functools.wraps(case)
            \\    def test():
            \\        async def run():
            \\            client = tb.ClientAsync(cluster_id=0, replica_addresses=replica_addresses)
            \\            try:
            \\                await case(client)
            \\            finally:
            \\                # Workaround until #3943 has been merged.
            \\                if client._client_key in tb.ClientAsync._clients:
            \\                    await client.close()
            \\        asyncio.run(run())
            \\    # PEP 362: Stop pytest from treating the test's `client` parameter as a fixture.
            \\    test.__signature__ = inspect.Signature()
            \\    return test
            \\
            ,
        });
        for (tests.suites) |suite| {
            try printer.write_empty_line();
            try printer.print_indented("# Suite: {s}", .{suite.name});
            for (suite.cases) |case| {
                const case_memory = printer.mark();
                defer printer.release(case_memory);

                try printer.write_empty_line();
                if (case.requirement) |requirement| {
                    if (!satisfies(requirement)) {
                        try printer.write_omission(case);
                        continue;
                    }
                }
                const case_name = try printer.to_case_alloc(.snake_case, case.description);
                switch (variant) {
                    .synchronous => try printer.print_indented("def test_{s}_{s}(client):", .{
                        suite.name, case_name,
                    }),
                    .asynchronous => {
                        try printer.write_indented("@async_test");
                        try printer.print_indented("async def test_{s}_{s}_async(client):", .{
                            suite.name, case_name,
                        });
                    },
                }
                printer.indent();
                for (case.steps) |step| try emit_step(printer, step, variant);
                printer.dedent();
            }
        }
    }
}

fn emit_step(printer: *Printer, step: ast.Step, variant: ClientVariant) !void {
    switch (step) {
        .binding => |binding| try emit_binding(printer, binding, variant),
        .call => |call| try emit_call(printer, call, variant, .{}),
        .assertion => |assertion| try emit_assertion(printer, assertion, variant),
    }
}

fn emit_binding(printer: *Printer, binding: ast.Binding, variant: ClientVariant) !void {
    switch (binding.value) {
        .generate_id, .index, .field_access => {
            const rendered = try render_expression(printer, binding.value);
            try printer.print_indented("{s} = {s}", .{ binding.name, rendered });
        },
        .generate_ids => |count| {
            try printer.print_indented("{s} = []", .{binding.name});
            try printer.print_indented("for index in range({d}):", .{count});
            printer.indent();
            try printer.print_indented("if index % {d} == 0:", .{ast.ids_between_sleeps});
            printer.indent();
            try printer.write_indented(switch (variant) {
                .synchronous => "time.sleep(0.001)",
                .asynchronous => "await asyncio.sleep(0.001)",
            });
            printer.dedent();
            try printer.print_indented("{s}.append(tb.id())", .{binding.name});
            printer.dedent();
        },
        .record => |record| switch (record.type) {
            .U128 => {
                const rendered = try render_expression(printer, binding.value);
                try printer.print_indented("{s} = {s}", .{ binding.name, rendered });
            },
            .Account, .Transfer => {
                const prefix = try printer.string_alloc("{s} = ", .{binding.name});
                try emit_record(printer, record, .{ .prefix = prefix });
            },
            .AccountBalance,
            .AccountFilter,
            .AccountFilterFlags,
            .AccountFlags,
            .CreateAccountResult,
            .CreateTransferResult,
            .QueryFilter,
            .QueryFilterFlags,
            .TransferFlags,
            => unreachable,
        },
        .call => |call| {
            const prefix = try printer.string_alloc("{s} = ", .{binding.name});
            try emit_call(printer, call, variant, .{ .prefix = prefix });
        },
        .integer, .boolean, .enum_literal, .reference, .increment, .decrement => unreachable,
    }
}

fn emit_call(
    printer: *Printer,
    call: ast.Call,
    variant: ClientVariant,
    options: struct {
        prefix: []const u8 = "",
    },
) !void {
    if (call.concurrency > 1) {
        assert(options.prefix.len == 0);
        try printer.write_indented(switch (variant) {
            .synchronous => "def operation():",
            .asynchronous => "async def operation():",
        });
        printer.indent();
        try emit_invocation(printer, call, variant, .{});
        printer.dedent();
        try printer.write_empty_line();
        switch (variant) {
            .synchronous => {
                try printer.print_indented(
                    "threads = [threading.Thread(target=operation) for _ in range({d})]",
                    .{call.concurrency},
                );
                try printer.write_indented("for thread in threads:");
                printer.indent();
                try printer.write_indented("thread.start()");
                printer.dedent();
                try printer.write_indented("for thread in threads:");
                printer.indent();
                try printer.write_indented("thread.join()");
                printer.dedent();
            },
            .asynchronous => try printer.print_indented(
                "await asyncio.gather(*(operation() for _ in range({d})))",
                .{call.concurrency},
            ),
        }
    } else {
        try emit_invocation(printer, call, variant, .{ .prefix = options.prefix });
    }
}

fn emit_invocation(
    printer: *Printer,
    call: ast.Call,
    variant: ClientVariant,
    options: struct {
        prefix: []const u8 = "",
    },
) !void {
    const await_keyword = switch (variant) {
        .synchronous => "",
        .asynchronous => "await ",
    };
    switch (call.name) {
        .close_client => {
            assert(options.prefix.len == 0);
            try printer.print_indented("{s}client.close()", .{await_keyword});
        },
        .sleep_ms => {
            assert(options.prefix.len == 0);
            assert(call.arguments.len == 1);
            const ms = try render_expression(printer, call.arguments[0]);
            switch (variant) {
                .synchronous => try printer.print_indented("time.sleep({s} / 1000)", .{ms}),
                .asynchronous => try printer.print_indented(
                    "await asyncio.sleep({s} / 1000)",
                    .{ms},
                ),
            }
        },
        .create_accounts, .create_transfers => {
            if (call.arguments.len == 0) {
                try printer.print_indented("{s}{s}client.{s}([])", .{
                    options.prefix, await_keyword, @tagName(call.name),
                });
                return;
            }
            try printer.print_indented("{s}{s}client.{s}(", .{
                options.prefix, await_keyword, @tagName(call.name),
            });
            printer.indent();
            try printer.write_indented("[");
            printer.indent();
            for (call.arguments) |argument| switch (argument) {
                .record => |record| try emit_record(printer, record, .{ .suffix = "," }),
                .reference => |reference| try printer.print_indented("{s},", .{reference}),
                else => unreachable,
            };
            printer.dedent();
            try printer.write_indented("]");
            printer.dedent();
            try printer.write_indented(")");
        },
        .lookup_accounts, .lookup_transfers => {
            try printer.write_indent();
            try printer.print("{s}{s}client.{s}([", .{
                options.prefix, await_keyword, @tagName(call.name),
            });
            for (call.arguments, 0..) |argument, index| {
                if (index > 0) try printer.write(", ");
                try printer.print("{s}", .{try render_expression(printer, argument)});
            }
            try printer.write("])\n");
        },
        .get_account_transfers, .get_account_balances, .query_accounts, .query_transfers => {
            assert(call.arguments.len == 1);
            try printer.print_indented("{s}{s}client.{s}(", .{
                options.prefix, await_keyword, @tagName(call.name),
            });
            printer.indent();
            try emit_record(printer, call.arguments[0].record, .{});
            printer.dedent();
            try printer.write_indented(")");
        },
    }
}

// `Account` and `Transfer` default every field, so only the fields a case names are written.
// `AccountFilter` and `QueryFilter` default none, so every field is written, unnamed ones as
// zero -- the same shape the hand-written tests use (`tests/test_basic.py:540`).
fn emit_record(
    printer: *Printer,
    record: ast.Record,
    options: struct {
        prefix: []const u8 = "",
        suffix: []const u8 = "",
    },
) !void {
    try printer.print_indented("{s}tb.{s}(", .{ options.prefix, @tagName(record.type) });
    printer.indent();
    switch (record.type) {
        .AccountFilter, .QueryFilter => {
            for (filter_fields(record.type)) |field_name| {
                const value = if (find_field(record, field_name)) |field|
                    try render_typed_value(printer, field.field, field.value)
                else if (std.mem.eql(u8, field_name, "flags"))
                    try printer.string_alloc("tb.{s}.NONE", .{
                        @tagName(flags_type(record.type)),
                    })
                else
                    "0";
                try printer.print_indented("{s}={s},", .{ field_name, value });
            }
        },
        else => {
            for (record.fields) |field| {
                const value = try render_typed_value(printer, field.field, field.value);
                try printer.print_indented("{s}={s},", .{ field.field.name, value });
            }
        },
    }
    printer.dedent();
    try printer.print_indented("){s}", .{options.suffix});
}

fn emit_assertion(
    printer: *Printer,
    assertion: ast.Assertion,
    variant: ClientVariant,
) !void {
    switch (assertion) {
        .equal => |equal| {
            try printer.print_indented("assert len({s}) == {d}", .{
                equal.actual, equal.expected.len,
            });
            for (equal.expected, 0..) |record, index| {
                for (record.fields) |field| {
                    const value = try render_typed_value(printer, field.field, field.value);
                    try printer.print_indented("assert {s}[{d}].{s} == {s}", .{
                        equal.actual, index, field.field.name, value,
                    });
                }
            }
        },
        .empty => |actual| {
            try printer.print_indented("assert {s} == []", .{actual});
        },
        .ascending => |ids| {
            try printer.print_indented(
                "assert all({s}[i - 1] < {s}[i] for i in range(1, len({s})))",
                .{ ids, ids, ids },
            );
        },
        .equal_field => |comparison| {
            const value = switch (comparison.expected) {
                .expression => |expression| try render_typed_value(
                    printer,
                    comparison.actual.field,
                    expression,
                ),
                .field_reference => |field| try render_field_access(printer, field),
            };
            try printer.print_indented("assert {s}.{s} == {s}", .{
                comparison.actual.reference, comparison.actual.field.name, value,
            });
        },
        .greater_than => |comparison| {
            const value = try render_typed_value(
                printer,
                comparison.actual.field,
                comparison.expected.expression,
            );
            try printer.print_indented("assert {s}.{s} > {s}", .{
                comparison.actual.reference, comparison.actual.field.name, value,
            });
        },
        .fail => |failure| {
            if (failure.client_error) |client_error| {
                try printer.print_indented("with pytest.raises(tb.{s}):", .{
                    python_error_name(client_error),
                });
            } else {
                try printer.write_indented("with pytest.raises(Exception):");
            }
            printer.indent();
            try emit_invocation(printer, failure.call, variant, .{});
            printer.dedent();
        },
    }
}

// Filters emit every field, so the full lists are reflected from the API structs. Only the
// `reserved` fields are skipped, which the Python dataclasses omit.
fn filter_fields(record_type: ast.Record.Type) []const []const u8 {
    switch (record_type) {
        inline .AccountFilter, .QueryFilter => |comptime_type| {
            return comptime field_names(comptime_type);
        },
        else => unreachable,
    }
}

fn field_names(comptime record_type: ast.Record.Type) []const []const u8 {
    var names: []const []const u8 = &.{};
    for (std.meta.fields(ast.Record.Struct(record_type))) |field| {
        if (std.mem.eql(u8, field.name, "reserved")) continue;
        names = names ++ &[_][]const u8{field.name};
    }
    return names;
}

fn flags_type(record_type: ast.Record.Type) ast.Record.Type {
    return switch (record_type) {
        .AccountFilter => .AccountFilterFlags,
        .QueryFilter => .QueryFilterFlags,
        else => unreachable,
    };
}

fn find_field(record: ast.Record, field_name: []const u8) ?ast.FieldValue {
    for (record.fields) |field| {
        if (std.mem.eql(u8, field.field.name, field_name)) return field;
    }
    return null;
}

fn render_expression(
    printer: *Printer,
    expression: ast.Expression,
) std.mem.Allocator.Error![]const u8 {
    switch (expression) {
        .generate_id => return "tb.id()",
        .call, .generate_ids => unreachable,
        .record => |record| switch (record.type) {
            .U128 => {
                assert(record.fields.len == 1);
                return record.fields[0].value.integer;
            },
            .Account,
            .AccountBalance,
            .AccountFilter,
            .AccountFilterFlags,
            .AccountFlags,
            .CreateAccountResult,
            .CreateTransferResult,
            .QueryFilter,
            .QueryFilterFlags,
            .Transfer,
            .TransferFlags,
            => unreachable,
        },
        .integer => |text| return text,
        .boolean => |value| return if (value) "True" else "False",
        .enum_literal => unreachable,
        .reference => |name| return name,
        .index => |index| {
            return printer.string_alloc("{s}[{d}]", .{
                index.reference,
                index.index,
            });
        },
        .field_access => |access| return render_field_access(printer, access),
        .increment => |arithmetic| return render_arithmetic(printer, arithmetic, "+"),
        .decrement => |arithmetic| return render_arithmetic(printer, arithmetic, "-"),
    }
}

fn python_error_name(client_error: ast.ClientError) []const u8 {
    return switch (client_error) {
        .too_much_data => "TooMuchDataError",
        .client_closed => "ClientClosedError",
    };
}

fn render_flags(printer: *Printer, record: ast.Record) ![]const u8 {
    if (record.fields.len == 0) {
        return printer.string_alloc("tb.{s}.NONE", .{@tagName(record.type)});
    }
    var text = std.ArrayList(u8).init(printer.arena());
    for (record.fields, 0..) |field, index| {
        assert(field.value == .boolean and field.value.boolean);
        if (index > 0) try text.appendSlice(" | ");
        try text.writer().print("tb.{s}.{s}", .{
            @tagName(record.type),
            try printer.to_case_alloc(.UPPER_CASE, field.field.name),
        });
    }
    return text.items;
}

fn render_field_access(
    printer: *Printer,
    reference: ast.FieldReference,
) ![]const u8 {
    return printer.string_alloc("{s}.{s}", .{
        reference.reference,
        reference.field.name,
    });
}

fn render_arithmetic(
    printer: *Printer,
    arithmetic: ast.Expression.Arithmetic,
    operator: []const u8,
) ![]const u8 {
    return printer.string_alloc("{s} {s} {d}", .{
        arithmetic.reference,
        operator,
        arithmetic.by,
    });
}

fn render_typed_value(
    printer: *Printer,
    field: ast.Field,
    value: ast.Expression,
) ![]const u8 {
    switch (value) {
        .enum_literal => |literal| {
            return printer.string_alloc("tb.{s}.{s}", .{
                field.type.enum_name,
                try printer.to_case_alloc(.UPPER_CASE, literal),
            });
        },
        .record => |record| {
            assert(ast.Record.is_flags(record.type));
            return render_flags(printer, record);
        },
        // Python's int is arbitrary precision, so every integer width renders as decimal text.
        .integer,
        .generate_id,
        .boolean,
        .reference,
        .index,
        .field_access,
        .increment,
        .decrement,
        => {
            return render_expression(printer, value);
        },
        .call, .generate_ids => unreachable,
    }
}
