const std = @import("std");
const assert = std.debug.assert;

const conformance = @import("conformance");

const ast = conformance.ast;
const Printer = conformance.Printer;

pub fn main() !void {
    var stdout = std.io.bufferedWriter(std.io.getStdOut().writer());
    const stdout_writer = stdout.writer();
    var memory: [Printer.default_memory_size]u8 = undefined;
    var printer = Printer.init(&memory, stdout_writer.any(), .{
        .indent_width = 4,
        .comment_marker = "#",
    });

    const tests = try conformance.parse(printer.arena());

    try emit(&printer, tests);
    try stdout.flush();
}

// TODO: This produces failing tests until the following PR gets merged:
// https://github.com/tigerbeetle/tigerbeetle/pull/3917
fn satisfies(requirement: ast.Case.Requirement) bool {
    return switch (requirement) {
        // Python's int is arbitrary precision, and float is accepted where int is expected.
        .requires_unbounded_integers => true,
        .requires_fractional_amounts => true,
    };
}

fn emit(printer: *Printer, tests: ast.ConformanceTests) !void {
    try printer.write(
        \\############################################################
        \\## This file was auto-generated by python_conformance.zig ##
        \\##               Do not manually modify.                  ##
        \\############################################################
        \\
        \\import os
        \\import sys
        \\import threading
        \\import time
        \\
        \\import pytest
        \\
        \\import tigerbeetle as tb
        \\
        \\replica_addresses = os.getenv("TB_ADDRESS")
        \\if not replica_addresses:
        \\    print("error: missing TB_ADDRESS environment variable")
        \\    sys.exit(1)
        \\
        \\
        \\@pytest.fixture
        \\def client():
        \\    client = tb.ClientSync(cluster_id=0, replica_addresses=replica_addresses)
        \\    yield client
        \\    # Cases that close the client leave nothing for the teardown to close.
        \\    if client._client_key in tb.ClientSync._clients:
        \\        client.close()
        \\
    );
    for (tests.suites) |suite| {
        try printer.write_empty_line();
        try printer.print_indented("# Suite: {s}", .{suite.name});
        for (suite.cases) |case| {
            try printer.write_empty_line();
            if (case.requirement) |requirement| {
                if (!satisfies(requirement)) {
                    try printer.write_omission(case);
                    continue;
                }
            }
            try printer.print_indented("def test_{s}_{s}(client):", .{
                suite.name,
                try printer.to_case_alloc(.snake_case, case.description),
            });
            printer.indent();
            for (case.steps) |step| try emit_step(printer, step);
            printer.dedent();
        }
    }
}

fn emit_step(printer: *Printer, step: ast.Step) !void {
    switch (step) {
        .binding => |binding| try emit_binding(printer, binding),
        .call => |call| try emit_call(printer, call, .{}),
        .assertion => |assertion| try emit_assertion(printer, assertion),
    }
}

fn emit_binding(printer: *Printer, binding: ast.Binding) !void {
    switch (binding.value) {
        .generate_id, .generate_ids, .index, .field_access => {
            const rendered = try render_expression(printer, binding.value);
            try printer.print_indented("{s} = {s}", .{ binding.name, rendered });
        },
        .record => |record| switch (record.type) {
            .U128 => {
                const rendered = try render_expression(printer, binding.value);
                try printer.print_indented("{s} = {s}", .{ binding.name, rendered });
            },
            .Account, .Transfer => {
                const prefix = try printer.string_alloc("{s} = ", .{binding.name});
                try emit_record(printer, record, .{ .prefix = prefix });
            },
            // Flags cannot be bound on their own, and result types are never written by hand.
            .AccountBalance,
            .AccountFilter,
            .AccountFilterFlags,
            .AccountFlags,
            .CreateAccountResult,
            .CreateTransferResult,
            .QueryFilter,
            .QueryFilterFlags,
            .TransferFlags,
            => unreachable,
        },
        .call => |call| {
            const prefix = try printer.string_alloc("{s} = ", .{binding.name});
            try emit_call(printer, call, .{ .prefix = prefix });
        },
        .integer, .boolean, .enum_literal, .reference, .increment, .decrement => unreachable,
    }
}

fn emit_call(
    printer: *Printer,
    call: ast.Call,
    options: struct {
        prefix: []const u8 = "",
    },
) !void {
    if (call.concurrency > 1) {
        assert(options.prefix.len == 0);
        try printer.write_indented("def operation():");
        printer.indent();
        try emit_operation(printer, call, .{});
        printer.dedent();
        try printer.write_empty_line();
        try printer.print_indented(
            "threads = [threading.Thread(target=operation) for _ in range({d})]",
            .{call.concurrency},
        );
        try printer.write_indented("for thread in threads:");
        printer.indent();
        try printer.write_indented("thread.start()");
        printer.dedent();
        try printer.write_indented("for thread in threads:");
        printer.indent();
        try printer.write_indented("thread.join()");
        printer.dedent();
    } else {
        try emit_operation(printer, call, .{ .prefix = options.prefix });
    }
}

fn emit_operation(
    printer: *Printer,
    call: ast.Call,
    options: struct {
        prefix: []const u8 = "",
    },
) !void {
    switch (call.name) {
        .close_client => {
            assert(options.prefix.len == 0);
            try printer.write_indented("client.close()");
        },
        .sleep_ms => {
            assert(options.prefix.len == 0);
            assert(call.arguments.len == 1);
            const ms = try render_expression(printer, call.arguments[0]);
            try printer.print_indented("time.sleep({s} / 1000)", .{ms});
        },
        .create_accounts, .create_transfers => {
            if (call.arguments.len == 0) {
                try printer.print_indented("{s}client.{s}([])", .{
                    options.prefix, @tagName(call.name),
                });
                return;
            }
            try printer.print_indented("{s}client.{s}(", .{ options.prefix, @tagName(call.name) });
            printer.indent();
            try printer.write_indented("[");
            printer.indent();
            for (call.arguments) |argument| switch (argument) {
                .record => |record| try emit_record(printer, record, .{ .suffix = "," }),
                .reference => |reference| try printer.print_indented("{s},", .{reference}),
                else => unreachable,
            };
            printer.dedent();
            try printer.write_indented("]");
            printer.dedent();
            try printer.write_indented(")");
        },
        .lookup_accounts, .lookup_transfers => {
            try printer.write_indent();
            try printer.print("{s}client.{s}([", .{ options.prefix, @tagName(call.name) });
            for (call.arguments, 0..) |argument, index| {
                if (index > 0) try printer.write(", ");
                try printer.print("{s}", .{try render_expression(printer, argument)});
            }
            try printer.write("])\n");
        },
        .get_account_transfers, .get_account_balances, .query_accounts, .query_transfers => {
            assert(call.arguments.len == 1);
            try printer.print_indented("{s}client.{s}(", .{ options.prefix, @tagName(call.name) });
            printer.indent();
            try emit_record(printer, call.arguments[0].record, .{});
            printer.dedent();
            try printer.write_indented(")");
        },
    }
}

// `Account` and `Transfer` default every field, so only the fields a case names are written.
// `AccountFilter` and `QueryFilter` default none, so every field is written, unnamed ones as
// zero -- the same shape the hand-written tests use (`tests/test_basic.py:540`).
fn emit_record(
    printer: *Printer,
    record: ast.Record,
    options: struct {
        prefix: []const u8 = "",
        suffix: []const u8 = "",
    },
) !void {
    try printer.print_indented("{s}tb.{s}(", .{ options.prefix, @tagName(record.type) });
    printer.indent();
    switch (record.type) {
        .AccountFilter, .QueryFilter => {
            for (filter_fields(record.type)) |field_name| {
                const value = if (find_field(record, field_name)) |field|
                    try render_typed_value(printer, field.field, field.value)
                else if (std.mem.eql(u8, field_name, "flags"))
                    try printer.string_alloc("tb.{s}.NONE", .{
                        @tagName(flags_type(record.type)),
                    })
                else
                    "0";
                try printer.print_indented("{s}={s},", .{ field_name, value });
            }
        },
        else => {
            for (record.fields) |field| {
                const value = try render_typed_value(printer, field.field, field.value);
                try printer.print_indented("{s}={s},", .{ field.field.name, value });
            }
        },
    }
    printer.dedent();
    try printer.print_indented("){s}", .{options.suffix});
}

fn emit_assertion(
    printer: *Printer,
    assertion: ast.Assertion,
) !void {
    switch (assertion) {
        .equal => |equal| {
            try printer.print_indented("assert len({s}) == {d}", .{
                equal.actual, equal.expected.len,
            });
            for (equal.expected, 0..) |record, index| {
                for (record.fields) |field| {
                    const value = try render_typed_value(printer, field.field, field.value);
                    try printer.print_indented("assert {s}[{d}].{s} == {s}", .{
                        equal.actual, index, field.field.name, value,
                    });
                }
            }
        },
        .empty => |actual| {
            try printer.print_indented("assert {s} == []", .{actual});
        },
        .unique => |ids| {
            try printer.print_indented("assert len(set({s})) == len({s})", .{ ids, ids });
        },
        .ascending => |ids| {
            try printer.print_indented(
                "assert all({s}[i - 1] < {s}[i] for i in range(1, len({s})))",
                .{ ids, ids, ids },
            );
        },
        .equal_field => |comparison| {
            const value = switch (comparison.expected) {
                .expression => |expression| try render_typed_value(
                    printer,
                    comparison.actual.field,
                    expression,
                ),
                .field_reference => |field| try render_field_access(printer, field),
            };
            try printer.print_indented("assert {s}.{s} == {s}", .{
                comparison.actual.reference, comparison.actual.field.name, value,
            });
        },
        .greater_than => |comparison| {
            const value = try render_typed_value(
                printer,
                comparison.actual.field,
                comparison.expected.expression,
            );
            try printer.print_indented("assert {s}.{s} > {s}", .{
                comparison.actual.reference, comparison.actual.field.name, value,
            });
        },
        // The DSL carries no exception type, matching Ruby's `assert_raises(StandardError)`.
        .fail => |call| {
            try printer.write_indented("with pytest.raises(Exception):");
            printer.indent();
            try emit_operation(printer, call, .{});
            printer.dedent();
        },
    }
}

// Filters emit every field, so the full lists are reflected from the API structs. Only the
// `reserved` fields are skipped, which the Python dataclasses omit.
fn filter_fields(record_type: ast.Record.Type) []const []const u8 {
    switch (record_type) {
        inline .AccountFilter, .QueryFilter => |comptime_type| {
            return comptime field_names(comptime_type);
        },
        else => unreachable,
    }
}

fn field_names(comptime record_type: ast.Record.Type) []const []const u8 {
    var names: []const []const u8 = &.{};
    for (std.meta.fields(ast.Record.Struct(record_type))) |field| {
        if (std.mem.eql(u8, field.name, "reserved")) continue;
        names = names ++ &[_][]const u8{field.name};
    }
    return names;
}

fn flags_type(record_type: ast.Record.Type) ast.Record.Type {
    return switch (record_type) {
        .AccountFilter => .AccountFilterFlags,
        .QueryFilter => .QueryFilterFlags,
        else => unreachable,
    };
}

fn find_field(record: ast.Record, field_name: []const u8) ?ast.FieldValue {
    for (record.fields) |field| {
        if (std.mem.eql(u8, field.field.name, field_name)) return field;
    }
    return null;
}

fn render_expression(
    printer: *Printer,
    expression: ast.Expression,
) std.mem.Allocator.Error![]const u8 {
    switch (expression) {
        .generate_id => return "tb.id()",
        .generate_ids => |count| {
            return printer.string_alloc("[tb.id() for _ in range({d})]", .{count});
        },
        .call => unreachable, // Calls are emitted by emit_call/emit_operation.
        .record => |record| switch (record.type) {
            .U128 => {
                assert(record.fields.len == 1);
                return record.fields[0].value.integer;
            },
            // Flags can't be bound on their own (parser-rejected), and the remaining records
            // are never written by hand.
            .Account,
            .AccountBalance,
            .AccountFilter,
            .AccountFilterFlags,
            .AccountFlags,
            .CreateAccountResult,
            .CreateTransferResult,
            .QueryFilter,
            .QueryFilterFlags,
            .Transfer,
            .TransferFlags,
            => unreachable,
        },
        .integer => |text| return text,
        .boolean => |value| return if (value) "True" else "False",
        .enum_literal => unreachable, // Only valid as a record field, rendered there.
        .reference => |name| return name,
        .index => |index| {
            return printer.string_alloc("{s}[{d}]", .{
                index.reference,
                index.index,
            });
        },
        .field_access => |access| return render_field_access(printer, access),
        .increment => |arithmetic| return render_arithmetic(printer, arithmetic, "+"),
        .decrement => |arithmetic| return render_arithmetic(printer, arithmetic, "-"),
    }
}

fn render_flags(printer: *Printer, record: ast.Record) ![]const u8 {
    var text = std.ArrayList(u8).init(printer.arena());
    for (record.fields, 0..) |field, index| {
        assert(field.value == .boolean and field.value.boolean);
        if (index > 0) try text.appendSlice(" | ");
        try text.writer().print("tb.{s}.{s}", .{
            @tagName(record.type),
            try printer.to_case_alloc(.UPPER_CASE, field.field.name),
        });
    }
    return text.items;
}

fn render_field_access(
    printer: *Printer,
    reference: ast.FieldReference,
) ![]const u8 {
    return printer.string_alloc("{s}.{s}", .{
        reference.reference,
        reference.field.name,
    });
}

fn render_arithmetic(
    printer: *Printer,
    arithmetic: ast.Expression.Arithmetic,
    operator: []const u8,
) ![]const u8 {
    return printer.string_alloc("{s} {s} {d}", .{
        arithmetic.reference,
        operator,
        arithmetic.by,
    });
}

fn render_typed_value(
    printer: *Printer,
    field: ast.Field,
    value: ast.Expression,
) ![]const u8 {
    switch (value) {
        .enum_literal => |literal| {
            return printer.string_alloc("tb.{s}.{s}", .{
                field.type.enum_name,
                try printer.to_case_alloc(.UPPER_CASE, literal),
            });
        },
        .record => |record| {
            assert(ast.Record.is_flags(record.type));
            return render_flags(printer, record);
        },
        // Python's int is arbitrary precision, so every integer width renders as decimal text.
        .integer,
        .generate_id,
        .boolean,
        .reference,
        .index,
        .field_access,
        .increment,
        .decrement,
        => {
            return render_expression(printer, value);
        },
        .call, .generate_ids => unreachable,
    }
}
