const std = @import("std");
const assert = std.debug.assert;

const conformance = @import("conformance");

const ast = conformance.ast;
const Formatter = conformance.Formatter;

pub fn main() !void {
    const formatter = Formatter.init(conformance.allocator(), .{
        .indent_width = 4,
        .start_level = 0,
        .comment_marker = "#",
    });

    const tests = try conformance.parse(formatter.arena);

    var stdout = std.io.bufferedWriter(std.io.getStdOut().writer());
    try emit(formatter, stdout.writer().any(), tests);
    try stdout.flush();
}

// TODO: This produces failing tests until the following PR gets merged:
// https://github.com/tigerbeetle/tigerbeetle/pull/3917
fn satisfies(requirement: ast.Case.Requirement) bool {
    return switch (requirement) {
        .requires_unbounded_integers => true,
    };
}

fn emit(formatter: Formatter, writer: std.io.AnyWriter, tests: ast.ConformanceTests) !void {
    try writer.writeAll(
        \\############################################################
        \\## This file was auto-generated by python_conformance.zig ##
        \\##               Do not manually modify.                  ##
        \\############################################################
        \\
        \\import os
        \\import sys
        \\import threading
        \\import time
        \\
        \\import pytest
        \\
        \\import tigerbeetle as tb
        \\
        \\replica_addresses = os.getenv("TB_ADDRESS")
        \\if not replica_addresses:
        \\    print("error: missing TB_ADDRESS environment variable")
        \\    sys.exit(1)
        \\
        \\
        \\@pytest.fixture
        \\def client():
        \\    client = tb.ClientSync(cluster_id=0, replica_addresses=replica_addresses)
        \\    yield client
        \\    # Cases that close the client leave nothing for the teardown to close.
        \\    if client._client_key in tb.ClientSync._clients:
        \\        client.close()
        \\
    );
    for (tests.suites) |suite| {
        try writer.writeAll("\n");
        try writer.print("# Suite: {s}\n", .{suite.name});
        for (suite.cases) |case| {
            try writer.writeAll("\n");
            if (case.requirement) |requirement| {
                if (!satisfies(requirement)) {
                    const text = try formatter.generate_omission(case);
                    try writer.writeAll(text);
                    continue;
                }
            }
            try writer.print("def test_{s}_{s}(client):\n", .{
                suite.name,
                try formatter.to_case(.snake_case, case.description),
            });
            for (case.steps) |step| try emit_step(formatter, writer, step);
        }
    }
}

fn emit_step(formatter: Formatter, writer: std.io.AnyWriter, step: ast.Step) !void {
    switch (step) {
        .binding => |binding| try emit_binding(formatter, writer, binding),
        .call => |call| try emit_call(formatter, writer, call, .{}),
        .assertion => |assertion| try emit_assertion(formatter, writer, assertion),
    }
}

fn emit_binding(formatter: Formatter, writer: std.io.AnyWriter, binding: ast.Binding) !void {
    switch (binding.value) {
        .generate_id, .generate_ids, .index => {
            const rendered = try render_expression(formatter, binding.value);
            try formatter.write_indent(writer, .{ .level = formatter.statement_level });
            try writer.print("{s} = {s}\n", .{ binding.name, rendered });
        },
        .record => |record| switch (record.type) {
            .U128 => {
                const rendered = try render_expression(formatter, binding.value);
                try formatter.write_indent(writer, .{ .level = formatter.statement_level });
                try writer.print("{s} = {s}\n", .{ binding.name, rendered });
            },
            .Account, .Transfer => {
                const prefix = try std.fmt.allocPrint(formatter.arena, "{s} = ", .{binding.name});
                try emit_record(formatter, writer, record, .{
                    .indent_level = formatter.statement_level,
                    .prefix = prefix,
                });
            },
            // Flags cannot be bound on their own, and result types are never written by hand.
            .AccountBalance,
            .AccountFilter,
            .AccountFilterFlags,
            .AccountFlags,
            .CreateAccountResult,
            .CreateTransferResult,
            .QueryFilter,
            .QueryFilterFlags,
            .TransferFlags,
            => unreachable,
        },
        .call => |call| {
            const prefix = try std.fmt.allocPrint(formatter.arena, "{s} = ", .{binding.name});
            try emit_call(formatter, writer, call, .{ .prefix = prefix });
        },
        .integer, .boolean, .enum_literal, .reference => unreachable,
    }
}

fn emit_call(
    formatter: Formatter,
    writer: std.io.AnyWriter,
    call: ast.Call,
    options: struct {
        prefix: []const u8 = "",
    },
) !void {
    if (call.concurrency > 1) {
        assert(options.prefix.len == 0);
        try formatter.write_indent(writer, .{ .level = formatter.statement_level });
        try writer.writeAll("def operation():\n");
        try emit_operation(formatter, writer, call, .{
            .indent_level = formatter.statement_level + 1,
        });
        try writer.writeAll("\n");
        try formatter.write_indent(writer, .{ .level = formatter.statement_level });
        try writer.print("threads = [threading.Thread(target=operation) for _ in range({d})]\n", .{
            call.concurrency,
        });
        try formatter.write_indent(writer, .{ .level = formatter.statement_level });
        try writer.writeAll("for thread in threads:\n");
        try formatter.write_indent(writer, .{ .level = formatter.statement_level + 1 });
        try writer.writeAll("thread.start()\n");
        try formatter.write_indent(writer, .{ .level = formatter.statement_level });
        try writer.writeAll("for thread in threads:\n");
        try formatter.write_indent(writer, .{ .level = formatter.statement_level + 1 });
        try writer.writeAll("thread.join()\n");
    } else {
        try emit_operation(formatter, writer, call, .{
            .indent_level = formatter.statement_level,
            .prefix = options.prefix,
        });
    }
}

fn emit_operation(
    formatter: Formatter,
    writer: std.io.AnyWriter,
    call: ast.Call,
    options: struct {
        indent_level: u32,
        prefix: []const u8 = "",
    },
) !void {
    switch (call.name) {
        .close_client => {
            assert(options.prefix.len == 0);
            try formatter.write_indent(writer, .{ .level = options.indent_level });
            try writer.writeAll("client.close()\n");
        },
        .sleep_ms => {
            assert(options.prefix.len == 0);
            assert(call.arguments.len == 1);
            const ms = try render_expression(formatter, call.arguments[0]);
            try formatter.write_indent(writer, .{ .level = options.indent_level });
            try writer.print("time.sleep({s} / 1000)\n", .{ms});
        },
        .create_accounts, .create_transfers => {
            try formatter.write_indent(writer, .{ .level = options.indent_level });
            try writer.print("{s}client.{s}(\n", .{ options.prefix, @tagName(call.name) });
            try formatter.write_indent(writer, .{ .level = options.indent_level + 1 });
            try writer.writeAll("[\n");
            for (call.arguments) |argument| switch (argument) {
                .record => |record| try emit_record(formatter, writer, record, .{
                    .indent_level = options.indent_level + 2,
                    .suffix = ",",
                }),
                .reference => |reference| {
                    try formatter.write_indent(writer, .{ .level = options.indent_level + 2 });
                    try writer.print("{s},\n", .{reference});
                },
                else => unreachable,
            };
            try formatter.write_indent(writer, .{ .level = options.indent_level + 1 });
            try writer.writeAll("]\n");
            try formatter.write_indent(writer, .{ .level = options.indent_level });
            try writer.writeAll(")\n");
        },
        .lookup_accounts, .lookup_transfers => {
            try formatter.write_indent(writer, .{ .level = options.indent_level });
            try writer.print("{s}client.{s}([", .{ options.prefix, @tagName(call.name) });
            for (call.arguments, 0..) |argument, index| {
                if (index > 0) try writer.writeAll(", ");
                try writer.writeAll(try render_expression(formatter, argument));
            }
            try writer.writeAll("])\n");
        },
        .get_account_transfers, .get_account_balances, .query_accounts, .query_transfers => {
            assert(call.arguments.len == 1);
            try formatter.write_indent(writer, .{ .level = options.indent_level });
            try writer.print("{s}client.{s}(\n", .{ options.prefix, @tagName(call.name) });
            try emit_record(formatter, writer, call.arguments[0].record, .{
                .indent_level = options.indent_level + 1,
            });
            try formatter.write_indent(writer, .{ .level = options.indent_level });
            try writer.writeAll(")\n");
        },
    }
}

// `Account` and `Transfer` default every field, so only the fields a case names are written.
// `AccountFilter` and `QueryFilter` default none, so every field is written, unnamed ones as
// zero -- the same shape the hand-written tests use (`tests/test_basic.py:540`).
fn emit_record(
    formatter: Formatter,
    writer: std.io.AnyWriter,
    record: ast.Record,
    options: struct {
        indent_level: u32,
        prefix: []const u8 = "",
        suffix: []const u8 = "",
    },
) !void {
    try formatter.write_indent(writer, .{ .level = options.indent_level });
    try writer.print("{s}tb.{s}(\n", .{ options.prefix, @tagName(record.type) });
    switch (record.type) {
        .AccountFilter, .QueryFilter => {
            for (filter_fields(record.type)) |field_name| {
                const value = if (find_field(record, field_name)) |field|
                    try render_field_value(formatter, field)
                else if (std.mem.eql(u8, field_name, "flags"))
                    try std.fmt.allocPrint(formatter.arena, "tb.{s}.NONE", .{
                        @tagName(flags_type(record.type)),
                    })
                else
                    "0";
                try formatter.write_indent(writer, .{ .level = options.indent_level + 1 });
                try writer.print("{s}={s},\n", .{ field_name, value });
            }
        },
        else => {
            for (record.fields) |field| {
                const value = try render_field_value(formatter, field);
                try formatter.write_indent(writer, .{ .level = options.indent_level + 1 });
                try writer.print("{s}={s},\n", .{ field.name, value });
            }
        },
    }
    try formatter.write_indent(writer, .{ .level = options.indent_level });
    try writer.print("){s}\n", .{options.suffix});
}

fn emit_assertion(
    formatter: Formatter,
    writer: std.io.AnyWriter,
    assertion: ast.Assertion,
) !void {
    switch (assertion) {
        .equal => |equal| {
            try formatter.write_indent(writer, .{ .level = formatter.statement_level });
            try writer.print("assert len({s}) == {d}\n", .{ equal.actual, equal.expected.len });
            for (equal.expected, 0..) |record, index| {
                for (record.fields) |field| {
                    const value = try render_field_value(formatter, field);
                    try formatter.write_indent(writer, .{ .level = formatter.statement_level });
                    try writer.print("assert {s}[{d}].{s} == {s}\n", .{
                        equal.actual, index, field.name, value,
                    });
                }
            }
        },
        .empty => |actual| {
            try formatter.write_indent(writer, .{ .level = formatter.statement_level });
            try writer.print("assert {s} == []\n", .{actual});
        },
        .unique => |ids| {
            try formatter.write_indent(writer, .{ .level = formatter.statement_level });
            try writer.print("assert len(set({s})) == len({s})\n", .{ ids, ids });
        },
        .ascending => |ids| {
            try formatter.write_indent(writer, .{ .level = formatter.statement_level });
            try writer.print(
                "assert all({s}[i - 1] < {s}[i] for i in range(1, len({s})))\n",
                .{ ids, ids, ids },
            );
        },
        .equal_field => |comparison| {
            const value = try render_field_value(formatter, comparison.field);
            try formatter.write_indent(writer, .{ .level = formatter.statement_level });
            try writer.print("assert {s}.{s} == {s}\n", .{
                comparison.reference, comparison.field.name, value,
            });
        },
        .greater_than => |comparison| {
            const value = try render_field_value(formatter, comparison.field);
            try formatter.write_indent(writer, .{ .level = formatter.statement_level });
            try writer.print("assert {s}.{s} > {s}\n", .{
                comparison.reference, comparison.field.name, value,
            });
        },
        // The DSL carries no exception type, matching Ruby's `assert_raises(StandardError)`.
        .fail => |call| {
            try formatter.write_indent(writer, .{ .level = formatter.statement_level });
            try writer.writeAll("with pytest.raises(Exception):\n");
            try emit_operation(formatter, writer, call, .{
                .indent_level = formatter.statement_level + 1,
            });
        },
    }
}

// The Python dataclasses omit the `reserved` fields the Zig types carry, so the field lists are
// written out here rather than reflected from the API structs.
fn filter_fields(record_type: ast.Record.Type) []const []const u8 {
    return switch (record_type) {
        .AccountFilter => &.{
            "account_id",    "user_data_128", "user_data_64",
            "user_data_32",  "code",          "timestamp_min",
            "timestamp_max", "limit",         "flags",
        },
        .QueryFilter => &.{
            "user_data_128", "user_data_64",  "user_data_32",
            "ledger",        "code",          "timestamp_min",
            "timestamp_max", "limit",         "flags",
        },
        else => unreachable,
    };
}

fn flags_type(record_type: ast.Record.Type) ast.Record.Type {
    return switch (record_type) {
        .AccountFilter => .AccountFilterFlags,
        .QueryFilter => .QueryFilterFlags,
        else => unreachable,
    };
}

fn find_field(record: ast.Record, field_name: []const u8) ?ast.Field {
    for (record.fields) |field| {
        if (std.mem.eql(u8, field.name, field_name)) return field;
    }
    return null;
}

fn render_expression(
    formatter: Formatter,
    expression: ast.Expression,
) std.mem.Allocator.Error![]const u8 {
    switch (expression) {
        .generate_id => return "tb.id()",
        .generate_ids => |count| {
            return std.fmt.allocPrint(
                formatter.arena,
                "[tb.id() for _ in range({d})]",
                .{count},
            );
        },
        .call => unreachable, // Calls are emitted by emit_call/emit_operation.
        .record => |record| switch (record.type) {
            .U128 => {
                assert(record.fields.len == 1);
                return record.fields[0].value.integer;
            },
            // Flags can't be bound on their own (parser-rejected), and the remaining records
            // are never written by hand.
            .Account,
            .AccountBalance,
            .AccountFilter,
            .AccountFilterFlags,
            .AccountFlags,
            .CreateAccountResult,
            .CreateTransferResult,
            .QueryFilter,
            .QueryFilterFlags,
            .Transfer,
            .TransferFlags,
            => unreachable,
        },
        .integer => |text| return text,
        .boolean => |value| return if (value) "True" else "False",
        .enum_literal => unreachable, // Only valid as a record field, rendered there.
        .reference => |name| return name,
        .index => |index| {
            return std.fmt.allocPrint(formatter.arena, "{s}[{d}]", .{
                index.reference,
                index.index,
            });
        },
    }
}

fn render_flags(formatter: Formatter, record: ast.Record) ![]const u8 {
    var text = std.ArrayList(u8).init(formatter.arena);
    for (record.fields, 0..) |field, index| {
        assert(field.value == .boolean and field.value.boolean);
        if (index > 0) try text.appendSlice(" | ");
        try text.writer().print("tb.{s}.{s}", .{
            @tagName(record.type),
            try formatter.to_case(.UPPER_CASE, field.name),
        });
    }
    return text.items;
}

fn render_field_value(formatter: Formatter, field: ast.Field) ![]const u8 {
    switch (field.value) {
        .enum_literal => |literal| {
            return std.fmt.allocPrint(formatter.arena, "tb.{s}.{s}", .{
                field.type.enum_name,
                try formatter.to_case(.UPPER_CASE, literal),
            });
        },
        .record => |record| {
            assert(ast.Record.is_flags(record.type));
            return render_flags(formatter, record);
        },
        // Python's int is arbitrary precision, so every integer width renders as decimal text.
        .integer, .generate_id, .boolean, .reference, .index => {
            return render_expression(formatter, field.value);
        },
        .call, .generate_ids => unreachable,
    }
}
