///////////////////////////////////////////////////////
// This file was auto-generated by go_conformance.zig //
//              Do not manually modify.               //
///////////////////////////////////////////////////////

package tigerbeetle_go

import (
	"bytes"
	"fmt"
	"math/rand"
	"os"
	"os/exec"
	"runtime"
	"sync"
	"testing"
	"time"

	"github.com/tigerbeetle/tigerbeetle-go/assert"
)

func TestConformance(t *testing.T) {
	startConformanceServer(t)

	// Suite: generate_ids

	t.Run("generate_ids_generates_unique_ids", func(t *testing.T) {
		ids := make([]Uint128, 1000)
		for i := range ids {
			ids[i] = ID()
		}
		seen := make(map[string]struct{}, len(ids))
		for _, id := range ids {
			if _, ok := seen[id.String()]; ok {
				t.Fatal("duplicate id")
			}
			seen[id.String()] = struct{}{}
		}
	})

	t.Run("generate_ids_generates_monotonically_increasing_ids", func(t *testing.T) {
		ids := make([]Uint128, 100)
		for i := range ids {
			ids[i] = ID()
		}
		for i := 1; i < len(ids); i++ {
			if ids[i-1].BigInt().Cmp(ids[i].BigInt()) >= 0 {
				t.Fatal("ids are not ascending")
			}
		}
	})

	// Suite: create_accounts

	t.Run("create_accounts_creates_an_account", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		results, err := client.CreateAccounts([]Account{
			{
				ID:     ID(),
				Ledger: 1,
				Code:   1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, results, 1)
		assert.Equal(t, AccountCreated, results[0].Status)
	})

	t.Run("create_accounts_returns_exists_for_a_duplicate_account", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		account := Account{
			ID:     ID(),
			Ledger: 1,
			Code:   1,
		}
		_, err := client.CreateAccounts([]Account{
			account,
		})
		if err != nil {
			t.Fatal(err)
		}
		results, err := client.CreateAccounts([]Account{
			account,
		})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, results, 1)
		assert.Equal(t, AccountExists, results[0].Status)
	})

	t.Run("create_accounts_rejects_a_zero_id", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		results, err := client.CreateAccounts([]Account{
			{
				ID:     ToUint128(0),
				Ledger: 1,
				Code:   1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, results, 1)
		assert.Equal(t, AccountIDMustNotBeZero, results[0].Status)
	})

	t.Run("create_accounts_rejects_a_zero_ledger", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		results, err := client.CreateAccounts([]Account{
			{
				ID:     ID(),
				Ledger: 0,
				Code:   1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, results, 1)
		assert.Equal(t, AccountLedgerMustNotBeZero, results[0].Status)
	})

	t.Run("create_accounts_rejects_a_zero_code", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		results, err := client.CreateAccounts([]Account{
			{
				ID:     ID(),
				Ledger: 1,
				Code:   0,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, results, 1)
		assert.Equal(t, AccountCodeMustNotBeZero, results[0].Status)
	})

	t.Run("create_accounts_rejects_mutually_exclusive_flags", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		results, err := client.CreateAccounts([]Account{
			{
				ID:     ID(),
				Ledger: 1,
				Code:   1,
				Flags:  AccountFlags{DebitsMustNotExceedCredits: true, CreditsMustNotExceedDebits: true}.ToUint16(),
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, results, 1)
		assert.Equal(t, AccountFlagsAreMutuallyExclusive, results[0].Status)
	})

	// Suite: lookup_accounts

	t.Run("lookup_accounts_returns_an_existing_account", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		accountID := ID()
		_, err := client.CreateAccounts([]Account{
			{
				ID:     accountID,
				Ledger: 1,
				Code:   1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		accounts, err := client.LookupAccounts([]Uint128{accountID})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, accounts, 1)
		assert.Equal(t, accountID, accounts[0].ID)
		assert.Equal(t, 1, accounts[0].Ledger)
		assert.Equal(t, 1, accounts[0].Code)
	})

	t.Run("lookup_accounts_returns_no_accounts_for_a_missing_id", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		accounts, err := client.LookupAccounts([]Uint128{ID()})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, accounts, 0)
	})

	t.Run("lookup_accounts_returns_multiple_existing_accounts_in_one_batch", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		account1ID := ID()
		account2ID := ID()
		_, err := client.CreateAccounts([]Account{
			{
				ID:     account1ID,
				Ledger: 1,
				Code:   1,
			},
			{
				ID:     account2ID,
				Ledger: 2,
				Code:   2,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		accounts, err := client.LookupAccounts([]Uint128{account1ID, account2ID})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, accounts, 2)
		assert.Equal(t, account1ID, accounts[0].ID)
		assert.Equal(t, 1, accounts[0].Ledger)
		assert.Equal(t, account2ID, accounts[1].ID)
		assert.Equal(t, 2, accounts[1].Ledger)
	})

	t.Run("lookup_accounts_returns_only_the_existing_account_for_a_partial_match", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		existingID := ID()
		missingID := ID()
		_, err := client.CreateAccounts([]Account{
			{
				ID:     existingID,
				Ledger: 1,
				Code:   1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		accounts, err := client.LookupAccounts([]Uint128{existingID, missingID})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, accounts, 1)
		assert.Equal(t, existingID, accounts[0].ID)
	})

	t.Run("lookup_accounts_returns_no_accounts_for_an_empty_batch", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		accounts, err := client.LookupAccounts([]Uint128{})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, accounts, 0)
	})

	t.Run("lookup_accounts_round_trips_all_fields", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		accountID := ID()
		userData128 := ID()
		_, err := client.CreateAccounts([]Account{
			{
				ID:          accountID,
				Ledger:      7,
				Code:        42,
				UserData128: userData128,
				UserData64:  9999999999,
				UserData32:  12345,
				Flags:       AccountFlags{History: true}.ToUint16(),
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		accounts, err := client.LookupAccounts([]Uint128{accountID})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, accounts, 1)
		assert.Equal(t, accountID, accounts[0].ID)
		assert.Equal(t, 7, accounts[0].Ledger)
		assert.Equal(t, 42, accounts[0].Code)
		assert.Equal(t, userData128, accounts[0].UserData128)
		assert.Equal(t, 9999999999, accounts[0].UserData64)
		assert.Equal(t, 12345, accounts[0].UserData32)
		assert.Equal(t, AccountFlags{History: true}.ToUint16(), accounts[0].Flags)
		account := accounts[0]
		assert.Greater(t, account.Timestamp, uint64(0))
	})

	// Suite: create_transfers

	t.Run("create_transfers_creates_a_transfer", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		debitAccountID := ID()
		creditAccountID := ID()
		_, err := client.CreateAccounts([]Account{
			{
				ID:     debitAccountID,
				Ledger: 1,
				Code:   1,
			},
			{
				ID:     creditAccountID,
				Ledger: 1,
				Code:   1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		results, err := client.CreateTransfers([]Transfer{
			{
				ID:              ID(),
				DebitAccountID:  debitAccountID,
				CreditAccountID: creditAccountID,
				Amount:          ToUint128(100),
				Ledger:          1,
				Code:            1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, results, 1)
		assert.Equal(t, TransferCreated, results[0].Status)
	})

	t.Run("create_transfers_returns_exists_for_a_duplicate_transfer", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		debitAccountID := ID()
		creditAccountID := ID()
		_, err := client.CreateAccounts([]Account{
			{
				ID:     debitAccountID,
				Ledger: 1,
				Code:   1,
			},
			{
				ID:     creditAccountID,
				Ledger: 1,
				Code:   1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		transfer := Transfer{
			ID:              ID(),
			DebitAccountID:  debitAccountID,
			CreditAccountID: creditAccountID,
			Amount:          ToUint128(100),
			Ledger:          1,
			Code:            1,
		}
		_, err = client.CreateTransfers([]Transfer{
			transfer,
		})
		if err != nil {
			t.Fatal(err)
		}
		results, err := client.CreateTransfers([]Transfer{
			transfer,
		})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, results, 1)
		assert.Equal(t, TransferExists, results[0].Status)
	})

	t.Run("create_transfers_rejects_a_zero_id", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		debitAccountID := ID()
		creditAccountID := ID()
		_, err := client.CreateAccounts([]Account{
			{
				ID:     debitAccountID,
				Ledger: 1,
				Code:   1,
			},
			{
				ID:     creditAccountID,
				Ledger: 1,
				Code:   1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		results, err := client.CreateTransfers([]Transfer{
			{
				ID:              ToUint128(0),
				DebitAccountID:  debitAccountID,
				CreditAccountID: creditAccountID,
				Amount:          ToUint128(10),
				Ledger:          1,
				Code:            1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, results, 1)
		assert.Equal(t, TransferIDMustNotBeZero, results[0].Status)
	})

	t.Run("create_transfers_rejects_a_zero_debit_account_id", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		creditAccountID := ID()
		_, err := client.CreateAccounts([]Account{
			{
				ID:     creditAccountID,
				Ledger: 1,
				Code:   1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		results, err := client.CreateTransfers([]Transfer{
			{
				ID:              ID(),
				DebitAccountID:  ToUint128(0),
				CreditAccountID: creditAccountID,
				Amount:          ToUint128(10),
				Ledger:          1,
				Code:            1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, results, 1)
		assert.Equal(t, TransferDebitAccountIDMustNotBeZero, results[0].Status)
	})

	t.Run("create_transfers_rejects_a_zero_credit_account_id", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		debitAccountID := ID()
		_, err := client.CreateAccounts([]Account{
			{
				ID:     debitAccountID,
				Ledger: 1,
				Code:   1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		results, err := client.CreateTransfers([]Transfer{
			{
				ID:              ID(),
				DebitAccountID:  debitAccountID,
				CreditAccountID: ToUint128(0),
				Amount:          ToUint128(10),
				Ledger:          1,
				Code:            1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, results, 1)
		assert.Equal(t, TransferCreditAccountIDMustNotBeZero, results[0].Status)
	})

	t.Run("create_transfers_rejects_identical_debit_and_credit_accounts", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		accountID := ID()
		_, err := client.CreateAccounts([]Account{
			{
				ID:     accountID,
				Ledger: 1,
				Code:   1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		results, err := client.CreateTransfers([]Transfer{
			{
				ID:              ID(),
				DebitAccountID:  accountID,
				CreditAccountID: accountID,
				Amount:          ToUint128(10),
				Ledger:          1,
				Code:            1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, results, 1)
		assert.Equal(t, TransferAccountsMustBeDifferent, results[0].Status)
	})

	t.Run("create_transfers_rejects_a_zero_ledger", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		debitAccountID := ID()
		creditAccountID := ID()
		_, err := client.CreateAccounts([]Account{
			{
				ID:     debitAccountID,
				Ledger: 1,
				Code:   1,
			},
			{
				ID:     creditAccountID,
				Ledger: 1,
				Code:   1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		results, err := client.CreateTransfers([]Transfer{
			{
				ID:              ID(),
				DebitAccountID:  debitAccountID,
				CreditAccountID: creditAccountID,
				Amount:          ToUint128(10),
				Ledger:          0,
				Code:            1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, results, 1)
		assert.Equal(t, TransferLedgerMustNotBeZero, results[0].Status)
	})

	t.Run("create_transfers_rejects_a_zero_code", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		debitAccountID := ID()
		creditAccountID := ID()
		_, err := client.CreateAccounts([]Account{
			{
				ID:     debitAccountID,
				Ledger: 1,
				Code:   1,
			},
			{
				ID:     creditAccountID,
				Ledger: 1,
				Code:   1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		results, err := client.CreateTransfers([]Transfer{
			{
				ID:              ID(),
				DebitAccountID:  debitAccountID,
				CreditAccountID: creditAccountID,
				Amount:          ToUint128(10),
				Ledger:          1,
				Code:            0,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, results, 1)
		assert.Equal(t, TransferCodeMustNotBeZero, results[0].Status)
	})

	// Suite: lookup_transfers

	t.Run("lookup_transfers_returns_an_existing_transfer", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		transferID := ID()
		debitAccountID := ID()
		creditAccountID := ID()
		_, err := client.CreateAccounts([]Account{
			{
				ID:     debitAccountID,
				Ledger: 1,
				Code:   1,
			},
			{
				ID:     creditAccountID,
				Ledger: 1,
				Code:   1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		_, err = client.CreateTransfers([]Transfer{
			{
				ID:              transferID,
				DebitAccountID:  debitAccountID,
				CreditAccountID: creditAccountID,
				Amount:          ToUint128(42),
				Ledger:          1,
				Code:            1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		transfers, err := client.LookupTransfers([]Uint128{transferID})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, transfers, 1)
		assert.Equal(t, transferID, transfers[0].ID)
		assert.Equal(t, debitAccountID, transfers[0].DebitAccountID)
		assert.Equal(t, creditAccountID, transfers[0].CreditAccountID)
		assert.Equal(t, ToUint128(42), transfers[0].Amount)
	})

	t.Run("lookup_transfers_returns_no_transfers_for_a_missing_id", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		transfers, err := client.LookupTransfers([]Uint128{ID()})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, transfers, 0)
	})

	t.Run("lookup_transfers_returns_multiple_existing_transfers_in_one_batch", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		transfer1ID := ID()
		transfer2ID := ID()
		debitAccountID := ID()
		creditAccountID := ID()
		_, err := client.CreateAccounts([]Account{
			{
				ID:     debitAccountID,
				Ledger: 1,
				Code:   1,
			},
			{
				ID:     creditAccountID,
				Ledger: 1,
				Code:   1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		_, err = client.CreateTransfers([]Transfer{
			{
				ID:              transfer1ID,
				DebitAccountID:  debitAccountID,
				CreditAccountID: creditAccountID,
				Amount:          ToUint128(10),
				Ledger:          1,
				Code:            1,
			},
			{
				ID:              transfer2ID,
				DebitAccountID:  debitAccountID,
				CreditAccountID: creditAccountID,
				Amount:          ToUint128(20),
				Ledger:          1,
				Code:            1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		transfers, err := client.LookupTransfers([]Uint128{transfer1ID, transfer2ID})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, transfers, 2)
		assert.Equal(t, transfer1ID, transfers[0].ID)
		assert.Equal(t, ToUint128(10), transfers[0].Amount)
		assert.Equal(t, transfer2ID, transfers[1].ID)
		assert.Equal(t, ToUint128(20), transfers[1].Amount)
	})

	t.Run("lookup_transfers_returns_only_the_existing_transfer_for_a_partial_match", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		existingID := ID()
		missingID := ID()
		debitAccountID := ID()
		creditAccountID := ID()
		_, err := client.CreateAccounts([]Account{
			{
				ID:     debitAccountID,
				Ledger: 1,
				Code:   1,
			},
			{
				ID:     creditAccountID,
				Ledger: 1,
				Code:   1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		_, err = client.CreateTransfers([]Transfer{
			{
				ID:              existingID,
				DebitAccountID:  debitAccountID,
				CreditAccountID: creditAccountID,
				Amount:          ToUint128(5),
				Ledger:          1,
				Code:            1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		transfers, err := client.LookupTransfers([]Uint128{existingID, missingID})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, transfers, 1)
		assert.Equal(t, existingID, transfers[0].ID)
	})

	t.Run("lookup_transfers_returns_no_transfers_for_an_empty_batch", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		transfers, err := client.LookupTransfers([]Uint128{})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, transfers, 0)
	})

	t.Run("lookup_transfers_round_trips_all_fields", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		transferID := ID()
		debitAccountID := ID()
		creditAccountID := ID()
		userData128 := ID()
		_, err := client.CreateAccounts([]Account{
			{
				ID:     debitAccountID,
				Ledger: 1,
				Code:   1,
			},
			{
				ID:     creditAccountID,
				Ledger: 1,
				Code:   1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		_, err = client.CreateTransfers([]Transfer{
			{
				ID:              transferID,
				DebitAccountID:  debitAccountID,
				CreditAccountID: creditAccountID,
				Amount:          ToUint128(99),
				Ledger:          1,
				Code:            7,
				UserData128:     userData128,
				UserData64:      8888888888,
				UserData32:      54321,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		transfers, err := client.LookupTransfers([]Uint128{transferID})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, transfers, 1)
		assert.Equal(t, transferID, transfers[0].ID)
		assert.Equal(t, debitAccountID, transfers[0].DebitAccountID)
		assert.Equal(t, creditAccountID, transfers[0].CreditAccountID)
		assert.Equal(t, ToUint128(99), transfers[0].Amount)
		assert.Equal(t, 1, transfers[0].Ledger)
		assert.Equal(t, 7, transfers[0].Code)
		assert.Equal(t, userData128, transfers[0].UserData128)
		assert.Equal(t, 8888888888, transfers[0].UserData64)
		assert.Equal(t, 54321, transfers[0].UserData32)
		transfer := transfers[0]
		assert.Greater(t, transfer.Timestamp, uint64(0))
	})

	// Suite: get_account_transfers

	t.Run("get_account_transfers_returns_debit_and_credit_transfers_for_an_account", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		account1ID := ID()
		account2ID := ID()
		account3ID := ID()
		debitTransferID := ID()
		creditTransferID := ID()
		_, err := client.CreateAccounts([]Account{
			{
				ID:     account1ID,
				Ledger: 1,
				Code:   1,
			},
			{
				ID:     account2ID,
				Ledger: 1,
				Code:   1,
			},
			{
				ID:     account3ID,
				Ledger: 1,
				Code:   1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		_, err = client.CreateTransfers([]Transfer{
			{
				ID:              debitTransferID,
				DebitAccountID:  account1ID,
				CreditAccountID: account2ID,
				Amount:          ToUint128(10),
				Ledger:          1,
				Code:            1,
			},
			{
				ID:              creditTransferID,
				DebitAccountID:  account3ID,
				CreditAccountID: account1ID,
				Amount:          ToUint128(20),
				Ledger:          1,
				Code:            1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		transfers, err := client.GetAccountTransfers(AccountFilter{
			AccountID: account1ID,
			Limit:     10,
			Flags:     AccountFilterFlags{Debits: true, Credits: true}.ToUint32(),
		})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, transfers, 2)
		assert.Equal(t, debitTransferID, transfers[0].ID)
		assert.Equal(t, ToUint128(10), transfers[0].Amount)
		assert.Equal(t, creditTransferID, transfers[1].ID)
		assert.Equal(t, ToUint128(20), transfers[1].Amount)
	})

	t.Run("get_account_transfers_returns_only_debit_transfers_with_the_debits_flag", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		account1ID := ID()
		account2ID := ID()
		account3ID := ID()
		debitTransferID := ID()
		_, err := client.CreateAccounts([]Account{
			{
				ID:     account1ID,
				Ledger: 1,
				Code:   1,
			},
			{
				ID:     account2ID,
				Ledger: 1,
				Code:   1,
			},
			{
				ID:     account3ID,
				Ledger: 1,
				Code:   1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		_, err = client.CreateTransfers([]Transfer{
			{
				ID:              debitTransferID,
				DebitAccountID:  account1ID,
				CreditAccountID: account2ID,
				Amount:          ToUint128(10),
				Ledger:          1,
				Code:            1,
			},
			{
				ID:              ID(),
				DebitAccountID:  account3ID,
				CreditAccountID: account1ID,
				Amount:          ToUint128(20),
				Ledger:          1,
				Code:            1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		transfers, err := client.GetAccountTransfers(AccountFilter{
			AccountID: account1ID,
			Limit:     10,
			Flags:     AccountFilterFlags{Debits: true}.ToUint32(),
		})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, transfers, 1)
		assert.Equal(t, debitTransferID, transfers[0].ID)
		assert.Equal(t, ToUint128(10), transfers[0].Amount)
	})

	t.Run("get_account_transfers_returns_only_credit_transfers_with_the_credits_flag", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		account1ID := ID()
		account2ID := ID()
		account3ID := ID()
		creditTransferID := ID()
		_, err := client.CreateAccounts([]Account{
			{
				ID:     account1ID,
				Ledger: 1,
				Code:   1,
			},
			{
				ID:     account2ID,
				Ledger: 1,
				Code:   1,
			},
			{
				ID:     account3ID,
				Ledger: 1,
				Code:   1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		_, err = client.CreateTransfers([]Transfer{
			{
				ID:              ID(),
				DebitAccountID:  account1ID,
				CreditAccountID: account2ID,
				Amount:          ToUint128(10),
				Ledger:          1,
				Code:            1,
			},
			{
				ID:              creditTransferID,
				DebitAccountID:  account3ID,
				CreditAccountID: account1ID,
				Amount:          ToUint128(20),
				Ledger:          1,
				Code:            1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		transfers, err := client.GetAccountTransfers(AccountFilter{
			AccountID: account1ID,
			Limit:     10,
			Flags:     AccountFilterFlags{Credits: true}.ToUint32(),
		})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, transfers, 1)
		assert.Equal(t, creditTransferID, transfers[0].ID)
		assert.Equal(t, ToUint128(20), transfers[0].Amount)
	})

	t.Run("get_account_transfers_returns_no_transfers_for_an_unused_account", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		transfers, err := client.GetAccountTransfers(AccountFilter{
			AccountID: ID(),
			Limit:     10,
			Flags:     AccountFilterFlags{Debits: true, Credits: true}.ToUint32(),
		})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, transfers, 0)
	})

	// Suite: get_account_balances

	t.Run("get_account_balances_returns_a_balance_per_transfer_for_a_history_account", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		account1ID := ID()
		account2ID := ID()
		_, err := client.CreateAccounts([]Account{
			{
				ID:     account1ID,
				Ledger: 1,
				Code:   1,
				Flags:  AccountFlags{History: true}.ToUint16(),
			},
			{
				ID:     account2ID,
				Ledger: 1,
				Code:   1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		_, err = client.CreateTransfers([]Transfer{
			{
				ID:              ID(),
				DebitAccountID:  account1ID,
				CreditAccountID: account2ID,
				Amount:          ToUint128(10),
				Ledger:          1,
				Code:            1,
			},
			{
				ID:              ID(),
				DebitAccountID:  account2ID,
				CreditAccountID: account1ID,
				Amount:          ToUint128(20),
				Ledger:          1,
				Code:            1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		balances, err := client.GetAccountBalances(AccountFilter{
			AccountID: account1ID,
			Limit:     10,
			Flags:     AccountFilterFlags{Debits: true, Credits: true}.ToUint32(),
		})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, balances, 2)
		assert.Equal(t, ToUint128(10), balances[0].DebitsPosted)
		assert.Equal(t, ToUint128(0), balances[0].CreditsPosted)
		assert.Equal(t, ToUint128(10), balances[1].DebitsPosted)
		assert.Equal(t, ToUint128(20), balances[1].CreditsPosted)
	})

	t.Run("get_account_balances_returns_no_balances_without_the_history_flag", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		account1ID := ID()
		account2ID := ID()
		_, err := client.CreateAccounts([]Account{
			{
				ID:     account1ID,
				Ledger: 1,
				Code:   1,
			},
			{
				ID:     account2ID,
				Ledger: 1,
				Code:   1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		_, err = client.CreateTransfers([]Transfer{
			{
				ID:              ID(),
				DebitAccountID:  account1ID,
				CreditAccountID: account2ID,
				Amount:          ToUint128(10),
				Ledger:          1,
				Code:            1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		balances, err := client.GetAccountBalances(AccountFilter{
			AccountID: account1ID,
			Limit:     10,
			Flags:     AccountFilterFlags{Debits: true, Credits: true}.ToUint32(),
		})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, balances, 0)
	})

	// Suite: query_accounts

	t.Run("query_accounts_returns_accounts_matching_user_data", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		account1ID := ID()
		account2ID := ID()
		userData := ID()
		_, err := client.CreateAccounts([]Account{
			{
				ID:          account1ID,
				UserData128: userData,
				Ledger:      1,
				Code:        1,
			},
			{
				ID:          account2ID,
				UserData128: userData,
				Ledger:      1,
				Code:        1,
			},
			{
				ID:          ID(),
				UserData128: ID(),
				Ledger:      1,
				Code:        1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		accounts, err := client.QueryAccounts(QueryFilter{
			UserData128: userData,
			Limit:       10,
		})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, accounts, 2)
		assert.Equal(t, account1ID, accounts[0].ID)
		assert.Equal(t, userData, accounts[0].UserData128)
		assert.Equal(t, account2ID, accounts[1].ID)
		assert.Equal(t, userData, accounts[1].UserData128)
	})

	t.Run("query_accounts_returns_accounts_in_reverse_order_with_the_reversed_flag", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		account1ID := ID()
		account2ID := ID()
		userData := ID()
		_, err := client.CreateAccounts([]Account{
			{
				ID:          account1ID,
				UserData128: userData,
				Ledger:      1,
				Code:        1,
			},
			{
				ID:          account2ID,
				UserData128: userData,
				Ledger:      1,
				Code:        1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		accounts, err := client.QueryAccounts(QueryFilter{
			UserData128: userData,
			Limit:       10,
			Flags:       QueryFilterFlags{Reversed: true}.ToUint32(),
		})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, accounts, 2)
		assert.Equal(t, account2ID, accounts[0].ID)
		assert.Equal(t, account1ID, accounts[1].ID)
	})

	t.Run("query_accounts_returns_accounts_matching_ledger_and_code", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		accountID := ID()
		userData := ID()
		_, err := client.CreateAccounts([]Account{
			{
				ID:          accountID,
				UserData128: userData,
				Ledger:      7,
				Code:        42,
			},
			{
				ID:          ID(),
				UserData128: userData,
				Ledger:      7,
				Code:        43,
			},
			{
				ID:          ID(),
				UserData128: userData,
				Ledger:      8,
				Code:        42,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		accounts, err := client.QueryAccounts(QueryFilter{
			UserData128: userData,
			Ledger:      7,
			Code:        42,
			Limit:       10,
		})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, accounts, 1)
		assert.Equal(t, accountID, accounts[0].ID)
		assert.Equal(t, 7, accounts[0].Ledger)
		assert.Equal(t, 42, accounts[0].Code)
	})

	t.Run("query_accounts_returns_no_accounts_for_unused_user_data", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		accounts, err := client.QueryAccounts(QueryFilter{
			UserData128: ID(),
			Limit:       10,
		})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, accounts, 0)
	})

	// Suite: query_transfers

	t.Run("query_transfers_returns_transfers_matching_user_data", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		debitAccountID := ID()
		creditAccountID := ID()
		transfer1ID := ID()
		transfer2ID := ID()
		userData := ID()
		_, err := client.CreateAccounts([]Account{
			{
				ID:     debitAccountID,
				Ledger: 1,
				Code:   1,
			},
			{
				ID:     creditAccountID,
				Ledger: 1,
				Code:   1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		_, err = client.CreateTransfers([]Transfer{
			{
				ID:              transfer1ID,
				DebitAccountID:  debitAccountID,
				CreditAccountID: creditAccountID,
				Amount:          ToUint128(10),
				UserData128:     userData,
				Ledger:          1,
				Code:            1,
			},
			{
				ID:              transfer2ID,
				DebitAccountID:  debitAccountID,
				CreditAccountID: creditAccountID,
				Amount:          ToUint128(20),
				UserData128:     userData,
				Ledger:          1,
				Code:            1,
			},
			{
				ID:              ID(),
				DebitAccountID:  debitAccountID,
				CreditAccountID: creditAccountID,
				Amount:          ToUint128(30),
				UserData128:     ID(),
				Ledger:          1,
				Code:            1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		transfers, err := client.QueryTransfers(QueryFilter{
			UserData128: userData,
			Limit:       10,
		})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, transfers, 2)
		assert.Equal(t, transfer1ID, transfers[0].ID)
		assert.Equal(t, ToUint128(10), transfers[0].Amount)
		assert.Equal(t, userData, transfers[0].UserData128)
		assert.Equal(t, transfer2ID, transfers[1].ID)
		assert.Equal(t, ToUint128(20), transfers[1].Amount)
		assert.Equal(t, userData, transfers[1].UserData128)
	})

	t.Run("query_transfers_returns_transfers_in_reverse_order_with_the_reversed_flag", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		debitAccountID := ID()
		creditAccountID := ID()
		transfer1ID := ID()
		transfer2ID := ID()
		userData := ID()
		_, err := client.CreateAccounts([]Account{
			{
				ID:     debitAccountID,
				Ledger: 1,
				Code:   1,
			},
			{
				ID:     creditAccountID,
				Ledger: 1,
				Code:   1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		_, err = client.CreateTransfers([]Transfer{
			{
				ID:              transfer1ID,
				DebitAccountID:  debitAccountID,
				CreditAccountID: creditAccountID,
				Amount:          ToUint128(10),
				UserData128:     userData,
				Ledger:          1,
				Code:            1,
			},
			{
				ID:              transfer2ID,
				DebitAccountID:  debitAccountID,
				CreditAccountID: creditAccountID,
				Amount:          ToUint128(20),
				UserData128:     userData,
				Ledger:          1,
				Code:            1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		transfers, err := client.QueryTransfers(QueryFilter{
			UserData128: userData,
			Limit:       10,
			Flags:       QueryFilterFlags{Reversed: true}.ToUint32(),
		})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, transfers, 2)
		assert.Equal(t, transfer2ID, transfers[0].ID)
		assert.Equal(t, ToUint128(20), transfers[0].Amount)
		assert.Equal(t, transfer1ID, transfers[1].ID)
		assert.Equal(t, ToUint128(10), transfers[1].Amount)
	})

	t.Run("query_transfers_returns_transfers_matching_ledger_and_code", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		transferID := ID()
		userData := ID()
		ledger7DebitID := ID()
		ledger7CreditID := ID()
		ledger8DebitID := ID()
		ledger8CreditID := ID()
		_, err := client.CreateAccounts([]Account{
			{
				ID:     ledger7DebitID,
				Ledger: 7,
				Code:   1,
			},
			{
				ID:     ledger7CreditID,
				Ledger: 7,
				Code:   1,
			},
			{
				ID:     ledger8DebitID,
				Ledger: 8,
				Code:   1,
			},
			{
				ID:     ledger8CreditID,
				Ledger: 8,
				Code:   1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		_, err = client.CreateTransfers([]Transfer{
			{
				ID:              transferID,
				DebitAccountID:  ledger7DebitID,
				CreditAccountID: ledger7CreditID,
				Amount:          ToUint128(10),
				UserData128:     userData,
				Ledger:          7,
				Code:            42,
			},
			{
				ID:              ID(),
				DebitAccountID:  ledger7DebitID,
				CreditAccountID: ledger7CreditID,
				Amount:          ToUint128(20),
				UserData128:     userData,
				Ledger:          7,
				Code:            43,
			},
			{
				ID:              ID(),
				DebitAccountID:  ledger8DebitID,
				CreditAccountID: ledger8CreditID,
				Amount:          ToUint128(30),
				UserData128:     userData,
				Ledger:          8,
				Code:            42,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		transfers, err := client.QueryTransfers(QueryFilter{
			UserData128: userData,
			Ledger:      7,
			Code:        42,
			Limit:       10,
		})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, transfers, 1)
		assert.Equal(t, transferID, transfers[0].ID)
		assert.Equal(t, 7, transfers[0].Ledger)
		assert.Equal(t, 42, transfers[0].Code)
	})

	t.Run("query_transfers_fails_when_the_limit_is_too_large", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		_, err := client.QueryTransfers(QueryFilter{
			Limit: 10000,
		})
		if err == nil {
			t.Fatal("expected an error")
		}
	})

	t.Run("query_transfers_returns_no_transfers_for_unused_user_data", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		transfers, err := client.QueryTransfers(QueryFilter{
			UserData128: ID(),
			Limit:       10,
		})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, transfers, 0)
	})

	// Suite: two_phase_transfer

	t.Run("two_phase_transfer_creates_posts_voids_and_expires_two_phase_transfers", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		accountAID := ID()
		accountBID := ID()
		accountResults1, err := client.CreateAccounts([]Account{
			{
				ID:     accountAID,
				Ledger: 1,
				Code:   718,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		accountResult1 := accountResults1[0]
		assert.Equal(t, AccountCreated, accountResult1.Status)
		assert.Greater(t, accountResult1.Timestamp, uint64(0))
		accountResults2, err := client.CreateAccounts([]Account{
			{
				ID:     accountAID,
				Ledger: 1,
				Code:   718,
			},
			{
				ID:     accountBID,
				Ledger: 1,
				Code:   719,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		accountResult2 := accountResults2[0]
		accountResult3 := accountResults2[1]
		assert.Equal(t, AccountExists, accountResult2.Status)
		assert.Greater(t, accountResult2.Timestamp, uint64(0))
		assert.Equal(t, AccountCreated, accountResult3.Status)
		assert.Greater(t, accountResult3.Timestamp, uint64(0))
		transferResults1, err := client.CreateTransfers([]Transfer{
			{
				ID:              ID(),
				DebitAccountID:  accountBID,
				CreditAccountID: accountAID,
				Amount:          ToUint128(100),
				Ledger:          1,
				Code:            1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		transferResult1 := transferResults1[0]
		assert.Equal(t, TransferCreated, transferResult1.Status)
		assert.Greater(t, transferResult1.Timestamp, uint64(0))
		accounts1, err := client.LookupAccounts([]Uint128{accountAID, accountBID})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, accounts1, 2)
		assert.Equal(t, accountAID, accounts1[0].ID)
		assert.Equal(t, ToUint128(100), accounts1[0].CreditsPosted)
		assert.Equal(t, ToUint128(0), accounts1[0].CreditsPending)
		assert.Equal(t, ToUint128(0), accounts1[0].DebitsPosted)
		assert.Equal(t, ToUint128(0), accounts1[0].DebitsPending)
		assert.Equal(t, accountBID, accounts1[1].ID)
		assert.Equal(t, ToUint128(0), accounts1[1].CreditsPosted)
		assert.Equal(t, ToUint128(0), accounts1[1].CreditsPending)
		assert.Equal(t, ToUint128(100), accounts1[1].DebitsPosted)
		assert.Equal(t, ToUint128(0), accounts1[1].DebitsPending)
		transfer2ID := ID()
		transferResults2, err := client.CreateTransfers([]Transfer{
			{
				ID:              transfer2ID,
				DebitAccountID:  accountBID,
				CreditAccountID: accountAID,
				Amount:          ToUint128(50),
				Timeout:         2_000_000_000,
				Ledger:          1,
				Code:            1,
				Flags:           TransferFlags{Pending: true}.ToUint16(),
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		transferResult2 := transferResults2[0]
		assert.Equal(t, TransferCreated, transferResult2.Status)
		assert.Greater(t, transferResult2.Timestamp, uint64(0))
		accounts2, err := client.LookupAccounts([]Uint128{accountAID, accountBID})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, accounts2, 2)
		assert.Equal(t, accountAID, accounts2[0].ID)
		assert.Equal(t, ToUint128(100), accounts2[0].CreditsPosted)
		assert.Equal(t, ToUint128(50), accounts2[0].CreditsPending)
		assert.Equal(t, ToUint128(0), accounts2[0].DebitsPosted)
		assert.Equal(t, ToUint128(0), accounts2[0].DebitsPending)
		assert.Equal(t, accountBID, accounts2[1].ID)
		assert.Equal(t, ToUint128(0), accounts2[1].CreditsPosted)
		assert.Equal(t, ToUint128(0), accounts2[1].CreditsPending)
		assert.Equal(t, ToUint128(100), accounts2[1].DebitsPosted)
		assert.Equal(t, ToUint128(50), accounts2[1].DebitsPending)
		transfers1, err := client.LookupTransfers([]Uint128{transfer2ID})
		if err != nil {
			t.Fatal(err)
		}
		transferLookup1 := transfers1[0]
		assert.Len(t, transfers1, 1)
		assert.Equal(t, transfer2ID, transfers1[0].ID)
		assert.Equal(t, accountBID, transfers1[0].DebitAccountID)
		assert.Equal(t, accountAID, transfers1[0].CreditAccountID)
		assert.Equal(t, ToUint128(50), transfers1[0].Amount)
		assert.Equal(t, ToUint128(0), transfers1[0].UserData128)
		assert.Equal(t, 0, transfers1[0].UserData64)
		assert.Equal(t, 0, transfers1[0].UserData32)
		assert.Equal(t, 1, transfers1[0].Code)
		assert.Equal(t, TransferFlags{Pending: true}.ToUint16(), transfers1[0].Flags)
		assert.Greater(t, uint64(transferLookup1.Timeout), uint64(0))
		commitResults, err := client.CreateTransfers([]Transfer{
			{
				ID:        ID(),
				Amount:    BytesToUint128([16]byte{0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff}),
				PendingID: transfer2ID,
				Ledger:    1,
				Code:      1,
				Flags:     TransferFlags{PostPendingTransfer: true}.ToUint16(),
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		commitResult := commitResults[0]
		assert.Equal(t, TransferCreated, commitResult.Status)
		assert.Greater(t, commitResult.Timestamp, uint64(0))
		accounts3, err := client.LookupAccounts([]Uint128{accountAID, accountBID})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, accounts3, 2)
		assert.Equal(t, accountAID, accounts3[0].ID)
		assert.Equal(t, ToUint128(150), accounts3[0].CreditsPosted)
		assert.Equal(t, ToUint128(0), accounts3[0].CreditsPending)
		assert.Equal(t, ToUint128(0), accounts3[0].DebitsPosted)
		assert.Equal(t, ToUint128(0), accounts3[0].DebitsPending)
		assert.Equal(t, accountBID, accounts3[1].ID)
		assert.Equal(t, ToUint128(0), accounts3[1].CreditsPosted)
		assert.Equal(t, ToUint128(0), accounts3[1].CreditsPending)
		assert.Equal(t, ToUint128(150), accounts3[1].DebitsPosted)
		assert.Equal(t, ToUint128(0), accounts3[1].DebitsPending)
		transfer3ID := ID()
		transferResults3, err := client.CreateTransfers([]Transfer{
			{
				ID:              transfer3ID,
				DebitAccountID:  accountBID,
				CreditAccountID: accountAID,
				Amount:          ToUint128(50),
				Timeout:         1_000_000_000,
				Ledger:          1,
				Code:            1,
				Flags:           TransferFlags{Pending: true}.ToUint16(),
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		transferResult3 := transferResults3[0]
		assert.Equal(t, TransferCreated, transferResult3.Status)
		assert.Greater(t, transferResult3.Timestamp, uint64(0))
		rejectResults, err := client.CreateTransfers([]Transfer{
			{
				ID:        ID(),
				PendingID: transfer3ID,
				Ledger:    1,
				Code:      1,
				Flags:     TransferFlags{VoidPendingTransfer: true}.ToUint16(),
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		rejectResult := rejectResults[0]
		assert.Equal(t, TransferCreated, rejectResult.Status)
		assert.Greater(t, rejectResult.Timestamp, uint64(0))
		accounts4, err := client.LookupAccounts([]Uint128{accountAID, accountBID})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, accounts4, 2)
		assert.Equal(t, accountAID, accounts4[0].ID)
		assert.Equal(t, ToUint128(150), accounts4[0].CreditsPosted)
		assert.Equal(t, ToUint128(0), accounts4[0].CreditsPending)
		assert.Equal(t, ToUint128(0), accounts4[0].DebitsPosted)
		assert.Equal(t, ToUint128(0), accounts4[0].DebitsPending)
		assert.Equal(t, accountBID, accounts4[1].ID)
		assert.Equal(t, ToUint128(0), accounts4[1].CreditsPosted)
		assert.Equal(t, ToUint128(0), accounts4[1].CreditsPending)
		assert.Equal(t, ToUint128(150), accounts4[1].DebitsPosted)
		assert.Equal(t, ToUint128(0), accounts4[1].DebitsPending)
		transfer4ID := ID()
		transferResults4, err := client.CreateTransfers([]Transfer{
			{
				ID:              transfer4ID,
				DebitAccountID:  accountBID,
				CreditAccountID: accountAID,
				Amount:          ToUint128(50),
				Timeout:         1,
				Ledger:          1,
				Code:            1,
				Flags:           TransferFlags{Pending: true}.ToUint16(),
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		transferResult4 := transferResults4[0]
		assert.Equal(t, TransferCreated, transferResult4.Status)
		assert.Greater(t, transferResult4.Timestamp, uint64(0))
		accounts5, err := client.LookupAccounts([]Uint128{accountAID, accountBID})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, accounts5, 2)
		assert.Equal(t, accountAID, accounts5[0].ID)
		assert.Equal(t, ToUint128(150), accounts5[0].CreditsPosted)
		assert.Equal(t, ToUint128(50), accounts5[0].CreditsPending)
		assert.Equal(t, ToUint128(0), accounts5[0].DebitsPosted)
		assert.Equal(t, ToUint128(0), accounts5[0].DebitsPending)
		assert.Equal(t, accountBID, accounts5[1].ID)
		assert.Equal(t, ToUint128(0), accounts5[1].CreditsPosted)
		assert.Equal(t, ToUint128(0), accounts5[1].CreditsPending)
		assert.Equal(t, ToUint128(150), accounts5[1].DebitsPosted)
		assert.Equal(t, ToUint128(50), accounts5[1].DebitsPending)
		time.Sleep(1500 * time.Millisecond)
		accounts6, err := client.LookupAccounts([]Uint128{accountAID, accountBID})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, accounts6, 2)
		assert.Equal(t, accountAID, accounts6[0].ID)
		assert.Equal(t, ToUint128(150), accounts6[0].CreditsPosted)
		assert.Equal(t, ToUint128(0), accounts6[0].CreditsPending)
		assert.Equal(t, ToUint128(0), accounts6[0].DebitsPosted)
		assert.Equal(t, ToUint128(0), accounts6[0].DebitsPending)
		assert.Equal(t, accountBID, accounts6[1].ID)
		assert.Equal(t, ToUint128(0), accounts6[1].CreditsPosted)
		assert.Equal(t, ToUint128(0), accounts6[1].CreditsPending)
		assert.Equal(t, ToUint128(150), accounts6[1].DebitsPosted)
		assert.Equal(t, ToUint128(0), accounts6[1].DebitsPending)
		expiredResults, err := client.CreateTransfers([]Transfer{
			{
				ID:        ID(),
				PendingID: transfer4ID,
				Ledger:    1,
				Code:      1,
				Flags:     TransferFlags{VoidPendingTransfer: true}.ToUint16(),
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		expiredResult := expiredResults[0]
		assert.Equal(t, TransferPendingTransferExpired, expiredResult.Status)
	})

	// Suite: uint128_range

	t.Run("uint128_range_accepts_the_maximum_u128", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		uint128Max := BytesToUint128([16]byte{0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff})
		accounts, err := client.LookupAccounts([]Uint128{uint128Max})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, accounts, 0)
	})

	// Omitted: "rejects a u128 above the maximum"
	// Reason: requires unbounded integers

	// Omitted: "rejects a negative u128"
	// Reason: requires unbounded integers

	// Suite: create_transfers_concurrent

	t.Run("create_transfers_concurrent_applies_transfers_submitted_concurrently", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		debitAccountID := ID()
		creditAccountID := ID()
		_, err := client.CreateAccounts([]Account{
			{
				ID:     debitAccountID,
				Ledger: 1,
				Code:   1,
			},
			{
				ID:     creditAccountID,
				Ledger: 1,
				Code:   1,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		var wg sync.WaitGroup
		for i := 0; i < 100; i++ {
			wg.Add(1)
			go func() {
				defer wg.Done()
				_, err := client.CreateTransfers([]Transfer{
					{
						ID:              ID(),
						DebitAccountID:  debitAccountID,
						CreditAccountID: creditAccountID,
						Amount:          ToUint128(10),
						Ledger:          1,
						Code:            1,
					},
				})
				if err != nil {
					t.Error(err)
				}
			}()
		}
		wg.Wait()
		accounts, err := client.LookupAccounts([]Uint128{debitAccountID, creditAccountID})
		if err != nil {
			t.Fatal(err)
		}
		assert.Len(t, accounts, 2)
		assert.Equal(t, debitAccountID, accounts[0].ID)
		assert.Equal(t, ToUint128(1000), accounts[0].DebitsPosted)
		assert.Equal(t, ToUint128(0), accounts[0].CreditsPosted)
		assert.Equal(t, creditAccountID, accounts[1].ID)
		assert.Equal(t, ToUint128(0), accounts[1].DebitsPosted)
		assert.Equal(t, ToUint128(1000), accounts[1].CreditsPosted)
	})

	// Suite: close_client

	t.Run("close_client_fails_operations_after_close", func(t *testing.T) {
		client := newClient(t)
		defer client.Close()

		client.Close()
		_, err := client.LookupAccounts([]Uint128{ID()})
		if err == nil {
			t.Fatal("expected an error")
		}
	})
}

func startConformanceServer(t *testing.T) {
	var tigerbeetlePath string
	if runtime.GOOS == "windows" {
		tigerbeetlePath = "../../../tigerbeetle.exe"
	} else {
		tigerbeetlePath = "../../../tigerbeetle"
	}

	addressArg := "--addresses=" + TIGERBEETLE_PORT
	cacheSizeArg := "--cache-grid=256MiB"
	replicaArg := fmt.Sprintf("--replica=%d", TIGERBEETLE_REPLICA_ID)
	replicaCountArg := fmt.Sprintf("--replica-count=%d", TIGERBEETLE_REPLICA_COUNT)
	clusterArg := fmt.Sprintf("--cluster=%d", TIGERBEETLE_CLUSTER_ID)

	fileName := fmt.Sprintf("./%d_%d_%d.tigerbeetle", TIGERBEETLE_CLUSTER_ID, TIGERBEETLE_REPLICA_ID, rand.Int())
	t.Cleanup(func() {
		_ = os.Remove(fileName)
	})

	tbInit := exec.Command(tigerbeetlePath, "format", clusterArg, replicaArg, replicaCountArg, fileName)
	var tbErr bytes.Buffer
	tbInit.Stdout = &tbErr
	tbInit.Stderr = &tbErr
	if err := tbInit.Run(); err != nil {
		fmt.Println(fmt.Sprint(err) + ": " + tbErr.String())
		t.Fatal(err)
	}

	tbStart := exec.Command(tigerbeetlePath, "start", addressArg, cacheSizeArg, fileName)
	if testing.Verbose() {
		tbStart.Stderr = os.Stderr
	}
	if err := tbStart.Start(); err != nil {
		t.Fatal(err)
	}

	t.Cleanup(func() {
		if err := tbStart.Process.Kill(); err != nil {
			t.Fatal(err)
		}
	})
}

func newClient(t *testing.T) Client {
	client, err := NewClient(ToUint128(TIGERBEETLE_CLUSTER_ID),
		[]string{"127.0.0.1:" + TIGERBEETLE_PORT})
	if err != nil {
		t.Fatal(err)
	}

	return client
}
