const std = @import("std");
const assert = std.debug.assert;

const conformance = @import("conformance");

const ast = conformance.ast;
const Printer = conformance.Printer;

pub fn main() !void {
    var stdout = std.io.bufferedWriter(std.io.getStdOut().writer());
    const stdout_writer = stdout.writer();
    var memory: [Printer.default_memory_size]u8 = undefined;
    var printer = Printer.init(&memory, stdout_writer.any(), .{
        .indent_width = 1,
        .indent_char = '\t',
    });

    const tests = try conformance.parse(printer.arena());

    try emit(&printer, tests);
    try stdout.flush();
}

fn satisfies(requirement: ast.Case.Requirement) bool {
    return switch (requirement) {
        // `Uint128` is sixteen bytes wide, so a value above the maximum cannot be constructed.
        .requires_unbounded_integers => false,
        // `Amount` is a `Uint128`, so a fractional value cannot be constructed.
        .requires_fractional_amounts => false,
    };
}

fn emit(printer: *Printer, tests: ast.ConformanceTests) !void {
    try printer.write(
        \\////////////////////////////////////////////////////////
        \\// This file was auto-generated by go_conformance.zig //
        \\//              Do not manually modify.               //
        \\////////////////////////////////////////////////////////
        \\
        \\package tigerbeetle_go
        \\
        \\import (
        \\
    );
    printer.indent();
    try printer.write_indented("\"bufio\"");
    try printer.write_indented("\"bytes\"");
    try printer.write_indented("\"fmt\"");
    try printer.write_indented("\"math/rand\"");
    try printer.write_indented("\"os\"");
    try printer.write_indented("\"os/exec\"");
    try printer.write_indented("\"runtime\"");
    try printer.write_indented("\"strings\"");
    try printer.write_indented("\"sync\"");
    try printer.write_indented("\"testing\"");
    try printer.write_indented("\"time\"");
    try printer.write_empty_line();
    try printer.write_indented("\"github.com/tigerbeetle/tigerbeetle-go/assert\"");
    printer.dedent();
    try printer.write_indented(")");
    try printer.write_empty_line();
    try printer.write_indented("func TestConformance(t *testing.T) {");
    printer.indent();
    try printer.write_indented("port := startConformanceServer(t)");
    for (tests.suites) |suite| {
        try printer.write_empty_line();
        try printer.print_indented("// Suite: {s}", .{suite.name});
        for (suite.cases) |case| {
            try printer.write_empty_line();
            if (case.requirement) |requirement| {
                if (!satisfies(requirement)) {
                    try printer.write_omission(case);
                    continue;
                }
            }
            try printer.print_indented("t.Run(\"{s}_{s}\", func(t *testing.T) {{", .{
                suite.name,
                try printer.to_case_alloc(.snake_case, case.description),
            });
            printer.indent();
            try emit_case(printer, case);
            printer.dedent();
            try printer.write_indented("})");
        }
    }
    printer.dedent();
    try printer.write_indented("}");
    try emit_server(printer);
    try emit_new_client(printer);
}

fn emit_case(printer: *Printer, case: ast.Case) !void {
    var scope = Scope{ .printer = printer };
    // Go rejects an unused local, and a case of pure id generation never touches the client.
    if (case_uses_client(case)) {
        try printer.write_indented("client := newClient(t, port)");
        try printer.write_indented("defer client.Close()");
        try printer.write_empty_line();
    }
    for (case.steps) |step| try emit_step(&scope, step);
}

fn case_uses_client(case: ast.Case) bool {
    for (case.steps) |step| switch (step) {
        .call => |call| if (call.name != .sleep_ms) return true,
        .binding => |binding| if (binding.value == .call) return true,
        .assertion => |assertion| if (assertion == .fail) return true,
    };
    return false;
}

// Tracks what is already declared in the generated `t.Run` body, since Go rejects both a
// redeclared `err` and an unused one.
const Scope = struct {
    printer: *Printer,
    error_declared: bool = false,

    fn error_assign(scope: *Scope, binds_result: bool) []const u8 {
        defer scope.error_declared = true;
        return if (binds_result or !scope.error_declared) ":=" else "=";
    }
};

fn emit_step(scope: *Scope, step: ast.Step) !void {
    switch (step) {
        .binding => |binding| try emit_binding(scope, binding),
        .call => |call| try emit_call(scope, call, .{}),
        .assertion => |assertion| try emit_assertion(scope, assertion),
    }
}

fn emit_binding(scope: *Scope, binding: ast.Binding) !void {
    const printer = scope.printer;
    const name = try printer.to_case_alloc(.GOCamelCase, binding.name);
    switch (binding.value) {
        .generate_id => {
            try printer.print_indented("{s} := ID()", .{name});
        },
        .generate_ids => |count| {
            try printer.print_indented("{s} := make([]Uint128, {d})", .{ name, count });
            try printer.print_indented("for i := range {s} {{", .{name});
            printer.indent();
            try printer.print_indented("{s}[i] = ID()", .{name});
            printer.dedent();
            try printer.write_indented("}");
        },
        .index => |index| {
            const reference = try printer.to_case_alloc(.GOCamelCase, index.reference);
            try printer.print_indented("{s} := {s}[{d}]", .{ name, reference, index.index });
        },
        .field_access => |access| {
            const value = try render_field_access(printer, access);
            try printer.print_indented("{s} := {s}", .{ name, value });
        },
        .record => |record| switch (record.type) {
            .U128 => {
                assert(record.fields.len == 1);
                const value = try render_uint128(printer, record.fields[0].value.integer);
                try printer.print_indented("{s} := {s}", .{ name, value });
            },
            .Account, .Transfer => {
                const prefix = try printer.string_alloc("{s} := ", .{name});
                try emit_record(printer, record, .{ .prefix = prefix, .typed = true });
            },
            // Flags cannot be bound on their own, and result types are never written by hand.
            .AccountBalance,
            .AccountFilter,
            .AccountFilterFlags,
            .AccountFlags,
            .CreateAccountResult,
            .CreateTransferResult,
            .QueryFilter,
            .QueryFilterFlags,
            .TransferFlags,
            => unreachable,
        },
        .call => |call| try emit_call(scope, call, .{ .binding = name }),
        .integer, .boolean, .enum_literal, .reference, .increment, .decrement => unreachable,
    }
}

fn emit_call(
    scope: *Scope,
    call: ast.Call,
    options: struct {
        binding: ?[]const u8 = null,
        expect_error: bool = false,
    },
) !void {
    const printer = scope.printer;
    if (call.concurrency > 1) {
        assert(options.binding == null);
        try printer.write_indented("var wg sync.WaitGroup");
        try printer.print_indented("for i := 0; i < {d}; i++ {{", .{call.concurrency});
        printer.indent();
        try printer.write_indented("wg.Add(1)");
        try printer.write_indented("go func() {");
        printer.indent();
        try printer.write_indented("defer wg.Done()");

        var goroutine_scope = Scope{ .printer = printer };
        try emit_operation(&goroutine_scope, call, .{ .error_action = .goroutine });

        printer.dedent();
        try printer.write_indented("}()");
        printer.dedent();
        try printer.write_indented("}");
        try printer.write_indented("wg.Wait()");
        return;
    }

    try emit_operation(scope, call, .{
        .binding = options.binding,
        .error_action = if (options.expect_error) .expected else .fatal,
    });
}

const ErrorAction = enum { fatal, goroutine, expected };

fn emit_operation(
    scope: *Scope,
    call: ast.Call,
    options: struct {
        binding: ?[]const u8 = null,
        error_action: ErrorAction,
    },
) !void {
    const printer = scope.printer;
    switch (call.name) {
        .close_client => {
            assert(options.binding == null);
            try printer.write_indented("client.Close()");
            return;
        },
        .sleep_ms => {
            assert(options.binding == null);
            assert(call.arguments.len == 1);
            try printer.print_indented("time.Sleep({s} * time.Millisecond)", .{
                call.arguments[0].integer,
            });
            return;
        },
        else => {},
    }

    try printer.write_indent();
    try printer.print("{s}, err {s} client.{s}(", .{
        options.binding orelse "_",
        scope.error_assign(options.binding != null),
        go_operation_name(call.name),
    });

    switch (call.name) {
        .create_accounts, .create_transfers => {
            const record_type: ast.Record.Type =
                if (call.name == .create_accounts) .Account else .Transfer;
            if (call.arguments.len == 0) {
                // gofmt collapses an empty composite literal onto a single line.
                try printer.print("[]{s}{{}})\n", .{@tagName(record_type)});
            } else {
                try printer.print("[]{s}{{\n", .{@tagName(record_type)});
                printer.indent();
                for (call.arguments) |argument| switch (argument) {
                    .record => |record| try emit_record(printer, record, .{ .suffix = "," }),
                    .reference => |reference| {
                        try printer.print_indented("{s},", .{
                            try printer.to_case_alloc(.GOCamelCase, reference),
                        });
                    },
                    else => unreachable,
                };
                printer.dedent();
                try printer.write_indented("})");
            }
        },
        .lookup_accounts, .lookup_transfers => {
            try printer.write("[]Uint128{");
            for (call.arguments, 0..) |argument, index| {
                if (index > 0) try printer.write(", ");
                try printer.write(try render_id(printer, argument));
            }
            try printer.write("})\n");
        },
        .get_account_transfers, .get_account_balances, .query_accounts, .query_transfers => {
            assert(call.arguments.len == 1);
            const filter = call.arguments[0].record;
            try printer.print("{s}{{\n", .{@tagName(filter.type)});
            printer.indent();
            try emit_record_fields(printer, filter);
            printer.dedent();
            try printer.write_indented("})");
        },
        .close_client, .sleep_ms => unreachable,
    }

    switch (options.error_action) {
        .fatal => try emit_error_check(printer),
        .goroutine => {
            try printer.write_indented("if err != nil {");
            printer.indent();
            try printer.write_indented("t.Error(err)");
            printer.dedent();
            try printer.write_indented("}");
        },
        .expected => {
            try printer.write_indented("if err == nil {");
            printer.indent();
            try printer.write_indented("t.Fatal(\"expected an error\")");
            printer.dedent();
            try printer.write_indented("}");
        },
    }
}

fn emit_error_check(printer: *Printer) !void {
    try printer.write_indented("if err != nil {");
    printer.indent();
    try printer.write_indented("t.Fatal(err)");
    printer.dedent();
    try printer.write_indented("}");
}

fn emit_record(
    printer: *Printer,
    record: ast.Record,
    options: struct {
        prefix: []const u8 = "",
        suffix: []const u8 = "",
        typed: bool = false,
    },
) !void {
    try printer.write_indent();
    if (options.typed) {
        try printer.print("{s}{s}{{\n", .{ options.prefix, @tagName(record.type) });
    } else {
        try printer.print("{s}{{\n", .{options.prefix});
    }
    printer.indent();
    try emit_record_fields(printer, record);
    printer.dedent();
    try printer.print_indented("}}{s}", .{options.suffix});
}

// Pads field names so values line up, which is what gofmt does to a multi-line composite literal.
fn emit_record_fields(printer: *Printer, record: ast.Record) !void {
    var name_width: usize = 0;
    for (record.fields) |field| {
        const name = try printer.to_case_alloc(.GOPascalCase, field.field.name);
        name_width = @max(name_width, name.len);
    }
    for (record.fields) |field| {
        const name = try printer.to_case_alloc(.GOPascalCase, field.field.name);
        const value = try render_typed_value(printer, field.field, field.value);
        try printer.write_indent();
        try printer.print("{s}:", .{name});
        try printer.write_padding(name_width - name.len + 1);
        try printer.print("{s},\n", .{value});
    }
}

fn emit_assertion(scope: *Scope, assertion: ast.Assertion) !void {
    const printer = scope.printer;
    switch (assertion) {
        .equal => |equal| {
            const actual = try printer.to_case_alloc(.GOCamelCase, equal.actual);
            try printer.print_indented("assert.Len(t, {s}, {d})", .{ actual, equal.expected.len });
            for (equal.expected, 0..) |record, index| {
                for (record.fields) |field| {
                    const value = try render_typed_value(printer, field.field, field.value);
                    try printer.print_indented("assert.Equal(t, {s}, {s}[{d}].{s})", .{
                        value,
                        actual,
                        index,
                        try printer.to_case_alloc(.GOPascalCase, field.field.name),
                    });
                }
            }
        },
        .empty => |actual| {
            const name = try printer.to_case_alloc(.GOCamelCase, actual);
            try printer.print_indented("assert.Len(t, {s}, 0)", .{name});
        },
        .unique => |ids| {
            const name = try printer.to_case_alloc(.GOCamelCase, ids);
            try printer.print_indented("seen := make(map[string]struct{{}}, len({s}))", .{name});
            try printer.print_indented("for _, id := range {s} {{", .{name});
            printer.indent();
            try printer.write_indented("if _, ok := seen[id.String()]; ok {");
            printer.indent();
            try printer.write_indented("t.Fatal(\"duplicate id\")");
            printer.dedent();
            try printer.write_indented("}");
            try printer.write_indented("seen[id.String()] = struct{}{}");
            printer.dedent();
            try printer.write_indented("}");
        },
        .ascending => |ids| {
            const name = try printer.to_case_alloc(.GOCamelCase, ids);
            try printer.print_indented("for i := 1; i < len({s}); i++ {{", .{name});
            printer.indent();
            try printer.print_indented("if {s}[i-1].BigInt().Cmp({s}[i].BigInt()) >= 0 {{", .{
                name, name,
            });
            printer.indent();
            try printer.write_indented("t.Fatal(\"ids are not ascending\")");
            printer.dedent();
            try printer.write_indented("}");
            printer.dedent();
            try printer.write_indented("}");
        },
        .equal_field => |comparison| {
            const actual = try render_field_access(printer, comparison.actual);
            const value = switch (comparison.expected) {
                .expression => |expression| try render_typed_value(
                    printer,
                    comparison.actual.field,
                    expression,
                ),
                .field_reference => |field| try render_field_access(printer, field),
            };
            try printer.print_indented("assert.Equal(t, {s}, {s})", .{ value, actual });
        },
        .greater_than => |comparison| {
            // `assert.Greater` type-asserts both sides to `uint64` rather than converting.
            const bits = comparison.actual.field.type.int;
            if (bits > 64) @panic("assert_greater_than has no Go form for a u128 field");
            const reference = try render_field_access(printer, comparison.actual);
            const actual = if (bits == 64)
                reference
            else
                try printer.string_alloc("uint64({s})", .{reference});
            try printer.print_indented("assert.Greater(t, {s}, uint64({s}))", .{
                actual,
                comparison.expected.expression.integer,
            });
        },
        .fail => |call| try emit_call(scope, call, .{ .expect_error = true }),
    }
}

fn render_field_access(
    printer: *Printer,
    reference: ast.FieldReference,
) ![]const u8 {
    return printer.string_alloc("{s}.{s}", .{
        try printer.to_case_alloc(.GOCamelCase, reference.reference),
        try printer.to_case_alloc(.GOPascalCase, reference.field.name),
    });
}

fn render_arithmetic(
    printer: *Printer,
    arithmetic: ast.Expression.Arithmetic,
    operator: []const u8,
) ![]const u8 {
    return printer.string_alloc("{s} {s} {d}", .{
        try printer.to_case_alloc(.GOCamelCase, arithmetic.reference),
        operator,
        arithmetic.by,
    });
}

fn render_typed_value(
    printer: *Printer,
    field: ast.Field,
    value: ast.Expression,
) ![]const u8 {
    switch (value) {
        .enum_literal => |literal| {
            const enum_name = field.type.enum_name;
            return printer.string_alloc("{s}{s}", .{
                go_enum_prefix(enum_name),
                try printer.to_case_alloc(.GOPascalCase, literal),
            });
        },
        .record => |flags| {
            assert(ast.Record.is_flags(flags.type));
            var text = std.ArrayList(u8).init(printer.arena());
            try text.writer().print("{s}{{", .{@tagName(flags.type)});
            for (flags.fields, 0..) |flag, index| {
                assert(flag.value == .boolean and flag.value.boolean);
                if (index > 0) try text.appendSlice(", ");
                const name = try printer.to_case_alloc(.GOPascalCase, flag.field.name);
                try text.writer().print("{s}: true", .{name});
            }
            try text.writer().print("}}.ToUint{d}()", .{flags_bits(flags.type)});
            return text.items;
        },
        .integer => |text| {
            const bits = field.type.int;
            if (bits == 128) return render_uint128(printer, text);
            return text;
        },
        .generate_id => return "ID()",
        .reference => |name| return printer.to_case_alloc(.GOCamelCase, name),
        .index => |index| {
            return printer.string_alloc("{s}[{d}]", .{
                try printer.to_case_alloc(.GOCamelCase, index.reference),
                index.index,
            });
        },
        .boolean => |boolean| return if (boolean) "true" else "false",
        .field_access => |access| return render_field_access(printer, access),
        .increment => |arithmetic| return render_arithmetic(printer, arithmetic, "+"),
        .decrement => |arithmetic| return render_arithmetic(printer, arithmetic, "-"),
        .call, .generate_ids => unreachable,
    }
}

// Ids reach the client as `Uint128`, whatever shape they take in the corpus.
fn render_id(printer: *Printer, expression: ast.Expression) ![]const u8 {
    switch (expression) {
        .generate_id => return "ID()",
        .reference => |name| return printer.to_case_alloc(.GOCamelCase, name),
        .integer => |text| return render_uint128(printer, text),
        else => unreachable,
    }
}

fn render_uint128(printer: *Printer, text: []const u8) ![]const u8 {
    const value = std.fmt.parseInt(u128, text, 10) catch unreachable;
    if (value <= std.math.maxInt(u64)) {
        return printer.string_alloc("ToUint128({s})", .{text});
    }

    var bytes: [16]u8 = undefined;
    std.mem.writeInt(u128, &bytes, value, .little);
    var literal = std.ArrayList(u8).init(printer.arena());
    try literal.appendSlice("BytesToUint128([16]byte{");
    for (bytes, 0..) |byte, index| {
        if (index > 0) try literal.appendSlice(", ");
        try literal.writer().print("0x{x:0>2}", .{byte});
    }
    try literal.appendSlice("})");
    return literal.items;
}

fn go_operation_name(name: ast.Call.Name) []const u8 {
    return switch (name) {
        .create_accounts => "CreateAccounts",
        .create_transfers => "CreateTransfers",
        .lookup_accounts => "LookupAccounts",
        .lookup_transfers => "LookupTransfers",
        .get_account_transfers => "GetAccountTransfers",
        .get_account_balances => "GetAccountBalances",
        .query_accounts => "QueryAccounts",
        .query_transfers => "QueryTransfers",
        .close_client, .sleep_ms => unreachable,
    };
}

// Go names status members after the event, not after the status type: `CreateAccountStatus.created`
// is `AccountCreated`. Mirrors the prefixes in `go_bindings.zig`'s `type_mappings`.
fn go_enum_prefix(enum_name: []const u8) []const u8 {
    if (std.mem.eql(u8, enum_name, "CreateAccountStatus")) return "Account";
    if (std.mem.eql(u8, enum_name, "CreateTransferStatus")) return "Transfer";
    @panic("unmapped enum type");
}

fn flags_bits(flags_type: ast.Record.Type) u16 {
    return switch (flags_type) {
        .AccountFlags, .TransferFlags => 16,
        .AccountFilterFlags, .QueryFilterFlags => 32,
        else => unreachable,
    };
}

// A copy of `WithClient`'s server harness in `tb_client_test.go`, without the client, since the
// conformance suite builds one per case.
fn emit_server(printer: *Printer) !void {
    try printer.write_empty_line();
    try printer.write_indented("func startConformanceServer(t *testing.T) string {");
    printer.indent();
    try printer.write_indented("var tigerbeetlePath string");
    try printer.write_indented("if runtime.GOOS == \"windows\" {");
    printer.indent();
    try printer.write_indented("tigerbeetlePath = \"../../../tigerbeetle.exe\"");
    printer.dedent();
    try printer.write_indented("} else {");
    printer.indent();
    try printer.write_indented("tigerbeetlePath = \"../../../tigerbeetle\"");
    printer.dedent();
    try printer.write_indented("}");
    try printer.write_empty_line();
    try printer.write_indented(
        "replicaArg := fmt.Sprintf(\"--replica=%d\", TIGERBEETLE_REPLICA_ID)",
    );
    try printer.write_indented(
        "replicaCountArg := fmt.Sprintf(\"--replica-count=%d\", TIGERBEETLE_REPLICA_COUNT)",
    );
    try printer.write_indented(
        "clusterArg := fmt.Sprintf(\"--cluster=%d\", TIGERBEETLE_CLUSTER_ID)",
    );
    try printer.write_empty_line();
    try printer.write_indented(
        "fileName := fmt.Sprintf(\"./%d_%d_%d.tigerbeetle\", TIGERBEETLE_CLUSTER_ID, " ++
            "TIGERBEETLE_REPLICA_ID, rand.Int())",
    );
    try printer.write_indented("t.Cleanup(func() {");
    printer.indent();
    try printer.write_indented("_ = os.Remove(fileName)");
    printer.dedent();
    try printer.write_indented("})");
    try printer.write_empty_line();
    try printer.write_indented(
        "tbInit := exec.Command(tigerbeetlePath, \"format\", clusterArg, replicaArg, " ++
            "replicaCountArg, fileName)",
    );
    try printer.write_indented("var tbErr bytes.Buffer");
    try printer.write_indented("tbInit.Stdout = &tbErr");
    try printer.write_indented("tbInit.Stderr = &tbErr");
    try printer.write_indented("if err := tbInit.Run(); err != nil {");
    printer.indent();
    try printer.write_indented("fmt.Println(fmt.Sprint(err) + \": \" + tbErr.String())");
    try printer.write_indented("t.Fatal(err)");
    printer.dedent();
    try printer.write_indented("}");
    try printer.write_empty_line();
    try printer.write_indented("tbStart := exec.Command(tigerbeetlePath,");
    printer.indent();
    try printer.write_indented("\"start\",");
    try printer.write_indented("\"--development\",");
    try printer.write_indented("\"--addresses=0\",");
    try printer.write_indented("fileName)");
    printer.dedent();
    try printer.write_empty_line();
    try printer.write_indented("if testing.Verbose() {");
    printer.indent();
    try printer.write_indented("tbStart.Stderr = os.Stderr");
    printer.dedent();
    try printer.write_indented("}");
    try printer.write_empty_line();
    try printer.write_indented("// Stdin is not used,");
    try printer.write_indented(
        "// but when running with `--addresses=0`, the replica exits if stdin is closed.",
    );
    try printer.write_indented("stdin, err := tbStart.StdinPipe()");
    try printer.write_indented("if err != nil {");
    printer.indent();
    try printer.write_indented("t.Fatal(err)");
    printer.dedent();
    try printer.write_indented("}");
    try printer.write_indented("_ = stdin");
    try printer.write_empty_line();
    try printer.write_indented("// Stdout is used to read the assigned TCP port.");
    try printer.write_indented("stdout, err := tbStart.StdoutPipe()");
    try printer.write_indented("if err != nil {");
    printer.indent();
    try printer.write_indented("t.Fatal(err)");
    printer.dedent();
    try printer.write_indented("}");
    try printer.write_empty_line();
    try printer.write_indented("if err := tbStart.Start(); err != nil {");
    printer.indent();
    try printer.write_indented("t.Fatal(err)");
    printer.dedent();
    try printer.write_indented("}");
    try printer.write_indented("t.Cleanup(func() {");
    printer.indent();
    try printer.write_indented("if err := tbStart.Process.Kill(); err != nil {");
    printer.indent();
    try printer.write_indented("t.Fatal(err)");
    printer.dedent();
    try printer.write_indented("}");
    printer.dedent();
    try printer.write_indented("})");
    try printer.write_empty_line();
    try printer.write_indented("reader := bufio.NewReader(stdout)");
    try printer.write_indented("port, err := reader.ReadString('\\n')");
    try printer.write_indented("if err != nil {");
    printer.indent();
    try printer.write_indented("t.Fatal(err)");
    printer.dedent();
    try printer.write_indented("}");
    try printer.write_empty_line();
    try printer.write_indented("return strings.TrimSpace(port)");
    printer.dedent();
    try printer.write_indented("}");
}

fn emit_new_client(printer: *Printer) !void {
    try printer.write_empty_line();
    try printer.write_indented("func newClient(t *testing.T, port string) Client {");
    printer.indent();
    try printer.write_indented(
        "client, err := NewClient(ToUint128(TIGERBEETLE_CLUSTER_ID), []string{port})",
    );
    try printer.write_indented("if err != nil {");
    printer.indent();
    try printer.write_indented("t.Fatal(err)");
    printer.dedent();
    try printer.write_indented("}");
    try printer.write_empty_line();
    try printer.write_indented("return client");
    printer.dedent();
    try printer.write_indented("}");
}
