const std = @import("std");
const assert = std.debug.assert;

const conformance = @import("conformance");

const types = conformance.types;

const indent_width = 1; // Tabs.
const case_indent_level = 1; // func > t.Run
const statement_indent_level = case_indent_level + 1;

pub fn main() !void {
    var arena_instance = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena_instance.deinit();
    const arena = arena_instance.allocator();

    const tests = try conformance.parse(arena);

    var buffer = std.ArrayList(u8).init(arena);
    try emit(arena, buffer.writer().any(), tests);
    try std.io.getStdOut().writeAll(buffer.items);
}

// `Uint128` is sixteen bytes wide, so a value above the maximum cannot be constructed.
fn satisfies(requirement: types.Case.Requirement) bool {
    return switch (requirement) {
        .requires_unbounded_integers => false,
    };
}

fn emit(arena: std.mem.Allocator, writer: std.io.AnyWriter, tests: types.ConformanceTests) !void {
    try writer.writeAll(
        \\///////////////////////////////////////////////////////
        \\// This file was auto-generated by go_conformance.zig //
        \\//              Do not manually modify.               //
        \\///////////////////////////////////////////////////////
        \\
        \\package tigerbeetle_go
        \\
        \\import (
        \\
    );
    try writer.writeAll("\t\"bytes\"\n");
    try writer.writeAll("\t\"fmt\"\n");
    try writer.writeAll("\t\"math/rand\"\n");
    try writer.writeAll("\t\"os\"\n");
    try writer.writeAll("\t\"os/exec\"\n");
    try writer.writeAll("\t\"runtime\"\n");
    try writer.writeAll("\t\"sync\"\n");
    try writer.writeAll("\t\"testing\"\n");
    try writer.writeAll("\t\"time\"\n");
    try writer.writeAll("\n");
    try writer.writeAll("\t\"github.com/tigerbeetle/tigerbeetle-go/assert\"\n");
    try writer.writeAll(")\n");
    try writer.writeAll("\n");
    try writer.writeAll("func TestConformance(t *testing.T) {\n");
    try writer.writeAll("\tstartConformanceServer(t)\n");
    for (tests.suites) |suite| {
        try writer.writeAll("\n");
        try write_indent(writer, case_indent_level);
        try writer.print("// Suite: {s}\n", .{suite.name});
        for (suite.cases) |case| {
            try writer.writeAll("\n");
            if (case.requirement) |requirement| {
                if (!satisfies(requirement)) {
                    try emit_omission(writer, suite, case, requirement);
                    continue;
                }
            }
            try write_indent(writer, case_indent_level);
            try writer.print("t.Run(\"{s}_", .{suite.name});
            try emit_test_name(writer, case.description);
            try writer.writeAll("\", func(t *testing.T) {\n");
            try emit_case(arena, writer, case);
            try write_indent(writer, case_indent_level);
            try writer.writeAll("})\n");
        }
    }
    try writer.writeAll("}\n");
    try emit_server(writer);
    try emit_new_client(writer);
}

fn emit_case(arena: std.mem.Allocator, writer: std.io.AnyWriter, case: types.Case) !void {
    var scope = Scope{ .arena = arena };
    // Go rejects an unused local, and a case of pure id generation never touches the client.
    if (case_uses_client(case)) {
        try write_indent(writer, statement_indent_level);
        try writer.writeAll("client := newClient(t)\n");
        try write_indent(writer, statement_indent_level);
        try writer.writeAll("defer client.Close()\n");
        try writer.writeAll("\n");
    }
    for (case.steps) |step| try emit_step(writer, &scope, step);
}

fn case_uses_client(case: types.Case) bool {
    for (case.steps) |step| switch (step) {
        .call => |call| if (call.name != .sleep_ms) return true,
        .binding => |binding| if (binding.value == .call) return true,
        .assertion => |assertion| if (assertion == .fail) return true,
    };
    return false;
}

// Tracks what is already declared in the generated `t.Run` body, since Go rejects both a
// redeclared `err` and an unused one.
// TODO: Can we remoe this?
const Scope = struct {
    arena: std.mem.Allocator,
    error_declared: bool = false,

    fn error_assign(scope: *Scope, binds_result: bool) []const u8 {
        defer scope.error_declared = true;
        return if (binds_result or !scope.error_declared) ":=" else "=";
    }
};

fn emit_step(writer: std.io.AnyWriter, scope: *Scope, step: types.Step) !void {
    switch (step) {
        .binding => |binding| try emit_binding(writer, scope, binding),
        .call => |call| try emit_call(writer, scope, call, .{}),
        .assertion => |assertion| try emit_assertion(writer, scope, assertion),
    }
}

fn emit_binding(writer: std.io.AnyWriter, scope: *Scope, binding: types.Binding) !void {
    const name = try go_identifier(scope.arena, binding.name);
    switch (binding.value) {
        .generate_id => {
            try write_indent(writer, statement_indent_level);
            try writer.print("{s} := ID()\n", .{name});
        },
        .generate_ids => |count| {
            try write_indent(writer, statement_indent_level);
            try writer.print("{s} := make([]Uint128, {d})\n", .{ name, count });
            try write_indent(writer, statement_indent_level);
            try writer.print("for i := range {s} {{\n", .{name});
            try write_indent(writer, statement_indent_level + 1);
            try writer.print("{s}[i] = ID()\n", .{name});
            try write_indent(writer, statement_indent_level);
            try writer.writeAll("}\n");
        },
        .index => |index| {
            const reference = try go_identifier(scope.arena, index.reference);
            try write_indent(writer, statement_indent_level);
            try writer.print("{s} := {s}[{d}]\n", .{ name, reference, index.index });
        },
        .record => |record| switch (record.type) {
            .U128 => {
                assert(record.fields.len == 1);
                const value = try render_uint128(scope.arena, record.fields[0].value.integer);
                try write_indent(writer, statement_indent_level);
                try writer.print("{s} := {s}\n", .{ name, value });
            },
            .Account, .Transfer => {
                const prefix = try std.fmt.allocPrint(scope.arena, "{s} := ", .{name});
                try emit_record(scope.arena, writer, record, .{
                    .indent_level = statement_indent_level,
                    .prefix = prefix,
                    .typed = true,
                });
            },
            // Flags cannot be bound on their own, and result types are never written by hand.
            .AccountBalance,
            .AccountFilter,
            .AccountFilterFlags,
            .AccountFlags,
            .CreateAccountResult,
            .CreateTransferResult,
            .QueryFilter,
            .QueryFilterFlags,
            .TransferFlags,
            => unreachable,
        },
        .call => |call| try emit_call(writer, scope, call, .{ .binding = name }),
        .integer, .boolean, .enum_literal, .reference => unreachable,
    }
}

fn emit_call(
    writer: std.io.AnyWriter,
    scope: *Scope,
    call: types.Call,
    options: struct {
        binding: ?[]const u8 = null,
        expect_error: bool = false,
    },
) !void {
    if (call.concurrency > 1) {
        assert(options.binding == null);
        try write_indent(writer, statement_indent_level);
        try writer.writeAll("var wg sync.WaitGroup\n");
        try write_indent(writer, statement_indent_level);
        try writer.print("for i := 0; i < {d}; i++ {{\n", .{call.concurrency});
        try write_indent(writer, statement_indent_level + 1);
        try writer.writeAll("wg.Add(1)\n");
        try write_indent(writer, statement_indent_level + 1);
        try writer.writeAll("go func() {\n");
        try write_indent(writer, statement_indent_level + 2);
        try writer.writeAll("defer wg.Done()\n");

        var goroutine_scope = Scope{ .arena = scope.arena };
        try emit_operation(writer, &goroutine_scope, call, .{
            .indent_level = statement_indent_level + 2,
            .error_action = .goroutine,
        });

        try write_indent(writer, statement_indent_level + 1);
        try writer.writeAll("}()\n");
        try write_indent(writer, statement_indent_level);
        try writer.writeAll("}\n");
        try write_indent(writer, statement_indent_level);
        try writer.writeAll("wg.Wait()\n");
        return;
    }

    try emit_operation(writer, scope, call, .{
        .indent_level = statement_indent_level,
        .binding = options.binding,
        .error_action = if (options.expect_error) .expected else .fatal,
    });
}

const ErrorAction = enum { fatal, goroutine, expected };

fn emit_operation(
    writer: std.io.AnyWriter,
    scope: *Scope,
    call: types.Call,
    options: struct {
        indent_level: u32,
        binding: ?[]const u8 = null,
        error_action: ErrorAction,
    },
) !void {
    const arena = scope.arena;
    switch (call.name) {
        .close_client => {
            assert(options.binding == null);
            try write_indent(writer, options.indent_level);
            try writer.writeAll("client.Close()\n");
            return;
        },
        .sleep_ms => {
            assert(options.binding == null);
            assert(call.arguments.len == 1);
            try write_indent(writer, options.indent_level);
            try writer.print(
                "time.Sleep({s} * time.Millisecond)\n",
                .{call.arguments[0].integer},
            );
            return;
        },
        else => {},
    }

    try write_indent(writer, options.indent_level);
    try writer.print("{s}, err {s} client.{s}(", .{
        options.binding orelse "_",
        scope.error_assign(options.binding != null),
        go_operation_name(call.name),
    });

    switch (call.name) {
        .create_accounts, .create_transfers => {
            const record_type: types.Record.Type =
                if (call.name == .create_accounts) .Account else .Transfer;
            try writer.print("[]{s}{{\n", .{@tagName(record_type)});
            for (call.arguments) |argument| switch (argument) {
                .record => |record| try emit_record(arena, writer, record, .{
                    .indent_level = options.indent_level + 1,
                    .suffix = ",",
                }),
                .reference => |reference| {
                    try write_indent(writer, options.indent_level + 1);
                    try writer.print("{s},\n", .{try go_identifier(arena, reference)});
                },
                else => unreachable,
            };
            try write_indent(writer, options.indent_level);
            try writer.writeAll("})\n");
        },
        .lookup_accounts, .lookup_transfers => {
            try writer.writeAll("[]Uint128{");
            for (call.arguments, 0..) |argument, index| {
                if (index > 0) try writer.writeAll(", ");
                try writer.writeAll(try render_id(arena, argument));
            }
            try writer.writeAll("})\n");
        },
        .get_account_transfers, .get_account_balances, .query_accounts, .query_transfers => {
            assert(call.arguments.len == 1);
            const filter = call.arguments[0].record;
            try writer.print("{s}{{\n", .{@tagName(filter.type)});
            try emit_record_fields(arena, writer, filter, options.indent_level + 1);
            try write_indent(writer, options.indent_level);
            try writer.writeAll("})\n");
        },
        .close_client, .sleep_ms => unreachable,
    }

    switch (options.error_action) {
        .fatal => try emit_error_check(writer, options.indent_level),
        .goroutine => {
            try write_indent(writer, options.indent_level);
            try writer.writeAll("if err != nil {\n");
            try write_indent(writer, options.indent_level + 1);
            try writer.writeAll("t.Error(err)\n");
            try write_indent(writer, options.indent_level);
            try writer.writeAll("}\n");
        },
        .expected => {
            try write_indent(writer, options.indent_level);
            try writer.writeAll("if err == nil {\n");
            try write_indent(writer, options.indent_level + 1);
            try writer.writeAll("t.Fatal(\"expected an error\")\n");
            try write_indent(writer, options.indent_level);
            try writer.writeAll("}\n");
        },
    }
}

fn emit_error_check(writer: std.io.AnyWriter, indent_level: u32) !void {
    try write_indent(writer, indent_level);
    try writer.writeAll("if err != nil {\n");
    try write_indent(writer, indent_level + 1);
    try writer.writeAll("t.Fatal(err)\n");
    try write_indent(writer, indent_level);
    try writer.writeAll("}\n");
}

fn emit_record(
    arena: std.mem.Allocator,
    writer: std.io.AnyWriter,
    record: types.Record,
    options: struct {
        indent_level: u32,
        prefix: []const u8 = "",
        suffix: []const u8 = "",
        typed: bool = false,
    },
) !void {
    try write_indent(writer, options.indent_level);
    if (options.typed) {
        try writer.print("{s}{s}{{\n", .{ options.prefix, @tagName(record.type) });
    } else {
        try writer.print("{s}{{\n", .{options.prefix});
    }
    try emit_record_fields(arena, writer, record, options.indent_level + 1);
    try write_indent(writer, options.indent_level);
    try writer.print("}}{s}\n", .{options.suffix});
}

// Pads field names so values line up, which is what gofmt does to a multi-line composite literal.
fn emit_record_fields(
    arena: std.mem.Allocator,
    writer: std.io.AnyWriter,
    record: types.Record,
    indent_level: u32,
) !void {
    var name_width: usize = 0;
    for (record.fields) |field| {
        const name = try go_field_name(arena, field.name);
        name_width = @max(name_width, name.len);
    }
    for (record.fields) |field| {
        const name = try go_field_name(arena, field.name);
        const value = try render_field_value(arena, field);
        try write_indent(writer, indent_level);
        try writer.print("{s}:", .{name});
        try writer.writeByteNTimes(' ', name_width - name.len + 1);
        try writer.print("{s},\n", .{value});
    }
}

fn emit_assertion(writer: std.io.AnyWriter, scope: *Scope, assertion: types.Assertion) !void {
    const arena = scope.arena;
    switch (assertion) {
        .equal => |equal| {
            const actual = try go_identifier(arena, equal.actual);
            try write_indent(writer, statement_indent_level);
            try writer.print("assert.Len(t, {s}, {d})\n", .{ actual, equal.expected.len });
            for (equal.expected, 0..) |record, index| {
                for (record.fields) |field| {
                    const value = try render_field_value(arena, field);
                    try write_indent(writer, statement_indent_level);
                    try writer.print("assert.Equal(t, {s}, {s}[{d}].{s})\n", .{
                        value,
                        actual,
                        index,
                        try go_field_name(arena, field.name),
                    });
                }
            }
        },
        .empty => |actual| {
            try write_indent(writer, statement_indent_level);
            try writer.print("assert.Len(t, {s}, 0)\n", .{try go_identifier(arena, actual)});
        },
        .unique => |ids| {
            const name = try go_identifier(arena, ids);
            try write_indent(writer, statement_indent_level);
            try writer.print("seen := make(map[string]struct{{}}, len({s}))\n", .{name});
            try write_indent(writer, statement_indent_level);
            try writer.print("for _, id := range {s} {{\n", .{name});
            try write_indent(writer, statement_indent_level + 1);
            try writer.writeAll("if _, ok := seen[id.String()]; ok {\n");
            try write_indent(writer, statement_indent_level + 2);
            try writer.writeAll("t.Fatal(\"duplicate id\")\n");
            try write_indent(writer, statement_indent_level + 1);
            try writer.writeAll("}\n");
            try write_indent(writer, statement_indent_level + 1);
            try writer.writeAll("seen[id.String()] = struct{}{}\n");
            try write_indent(writer, statement_indent_level);
            try writer.writeAll("}\n");
        },
        .ascending => |ids| {
            const name = try go_identifier(arena, ids);
            try write_indent(writer, statement_indent_level);
            try writer.print("for i := 1; i < len({s}); i++ {{\n", .{name});
            try write_indent(writer, statement_indent_level + 1);
            try writer.print(
                "if {s}[i-1].BigInt().Cmp({s}[i].BigInt()) >= 0 {{\n",
                .{ name, name },
            );
            try write_indent(writer, statement_indent_level + 2);
            try writer.writeAll("t.Fatal(\"ids are not ascending\")\n");
            try write_indent(writer, statement_indent_level + 1);
            try writer.writeAll("}\n");
            try write_indent(writer, statement_indent_level);
            try writer.writeAll("}\n");
        },
        .equal_field => |comparison| {
            const actual = try render_field_reference(arena, comparison);
            const value = try render_field_value(arena, comparison.field);
            try write_indent(writer, statement_indent_level);
            try writer.print("assert.Equal(t, {s}, {s})\n", .{ value, actual });
        },
        .greater_than => |comparison| {
            // `assert.Greater` type-asserts both sides to `uint64` rather than converting.
            const bits = comparison.field.type.int;
            if (bits > 64) @panic("assert_greater_than has no Go form for a u128 field");
            const reference = try render_field_reference(arena, comparison);
            const actual = if (bits == 64)
                reference
            else
                try std.fmt.allocPrint(arena, "uint64({s})", .{reference});
            try write_indent(writer, statement_indent_level);
            try writer.print("assert.Greater(t, {s}, uint64({s}))\n", .{
                actual,
                comparison.field.value.integer,
            });
        },
        .fail => |call| try emit_call(writer, scope, call, .{ .expect_error = true }),
    }
}

fn render_field_reference(
    arena: std.mem.Allocator,
    comparison: types.Assertion.FieldComparison,
) ![]const u8 {
    return std.fmt.allocPrint(arena, "{s}.{s}", .{
        try go_identifier(arena, comparison.reference),
        try go_field_name(arena, comparison.field.name),
    });
}

fn render_field_value(arena: std.mem.Allocator, field: types.Field) ![]const u8 {
    switch (field.value) {
        .enum_literal => |literal| {
            const enum_name = field.type.enum_name;
            return std.fmt.allocPrint(arena, "{s}{s}", .{
                go_enum_prefix(enum_name),
                try go_pascal_case(arena, literal),
            });
        },
        .record => |flags| {
            assert(types.Record.is_flags(flags.type));
            var text = std.ArrayList(u8).init(arena);
            try text.writer().print("{s}{{", .{@tagName(flags.type)});
            for (flags.fields, 0..) |flag, index| {
                assert(flag.value == .boolean and flag.value.boolean);
                if (index > 0) try text.appendSlice(", ");
                try text.writer().print("{s}: true", .{try go_field_name(arena, flag.name)});
            }
            try text.writer().print("}}.ToUint{d}()", .{flags_bits(flags.type)});
            return text.items;
        },
        .integer => |text| {
            const bits = field.type.int;
            if (bits == 128) return render_uint128(arena, text);
            return text;
        },
        .generate_id => return "ID()",
        .reference => |name| return go_identifier(arena, name),
        .index => |index| {
            return std.fmt.allocPrint(arena, "{s}[{d}]", .{
                try go_identifier(arena, index.reference),
                index.index,
            });
        },
        .boolean => |value| return if (value) "true" else "false",
        .call, .generate_ids => unreachable,
    }
}

// Ids reach the client as `Uint128`, whatever shape they take in the corpus.
fn render_id(arena: std.mem.Allocator, expression: types.Expression) ![]const u8 {
    switch (expression) {
        .generate_id => return "ID()",
        .reference => |name| return go_identifier(arena, name),
        .integer => |text| return render_uint128(arena, text),
        else => unreachable,
    }
}

fn render_uint128(arena: std.mem.Allocator, text: []const u8) ![]const u8 {
    const value = std.fmt.parseInt(u128, text, 10) catch unreachable;
    if (value <= std.math.maxInt(u64)) {
        return std.fmt.allocPrint(arena, "ToUint128({s})", .{text});
    }

    var bytes: [16]u8 = undefined;
    std.mem.writeInt(u128, &bytes, value, .little);
    var literal = std.ArrayList(u8).init(arena);
    try literal.appendSlice("BytesToUint128([16]byte{");
    for (bytes, 0..) |byte, index| {
        if (index > 0) try literal.appendSlice(", ");
        try literal.writer().print("0x{x:0>2}", .{byte});
    }
    try literal.appendSlice("})");
    return literal.items;
}

fn go_operation_name(name: types.Call.Name) []const u8 {
    return switch (name) {
        .create_accounts => "CreateAccounts",
        .create_transfers => "CreateTransfers",
        .lookup_accounts => "LookupAccounts",
        .lookup_transfers => "LookupTransfers",
        .get_account_transfers => "GetAccountTransfers",
        .get_account_balances => "GetAccountBalances",
        .query_accounts => "QueryAccounts",
        .query_transfers => "QueryTransfers",
        .close_client, .sleep_ms => unreachable,
    };
}

// Go names status members after the event, not after the status type: `CreateAccountStatus.created`
// is `AccountCreated`. Mirrors the prefixes in `go_bindings.zig`'s `type_mappings`.
fn go_enum_prefix(enum_name: []const u8) []const u8 {
    if (std.mem.eql(u8, enum_name, "CreateAccountStatus")) return "Account";
    if (std.mem.eql(u8, enum_name, "CreateTransferStatus")) return "Transfer";
    @panic("unmapped enum type");
}

fn go_field_name(arena: std.mem.Allocator, name: []const u8) ![]const u8 {
    return go_pascal_case(arena, name);
}

// Go exports fields in PascalCase, with initialisms upper-cased throughout, as `go_bindings.zig`
// emits them.
fn go_pascal_case(arena: std.mem.Allocator, name: []const u8) ![]const u8 {
    var text = std.ArrayList(u8).init(arena);
    var words = std.mem.tokenizeScalar(u8, name, '_');
    while (words.next()) |word| {
        if (is_initialism(word)) {
            for (word) |char| try text.append(std.ascii.toUpper(char));
            continue;
        }
        try text.append(std.ascii.toUpper(word[0]));
        try text.appendSlice(word[1..]);
    }
    return text.items;
}

fn go_identifier(arena: std.mem.Allocator, name: []const u8) ![]const u8 {
    const pascal = try go_pascal_case(arena, name);
    var text = std.ArrayList(u8).init(arena);
    // An identifier opening with an initialism stays lower-case throughout it: `idFoo`, not
    // `iDFoo`.
    var words = std.mem.tokenizeScalar(u8, name, '_');
    const first = words.next().?;
    const lead = if (is_initialism(first)) first.len else 1;
    for (pascal[0..lead]) |char| try text.append(std.ascii.toLower(char));
    try text.appendSlice(pascal[lead..]);
    return text.items;
}

// https://github.com/golang/go/wiki/CodeReviewComments#initialisms, as `go_bindings.zig`
// applies it.
fn is_initialism(word: []const u8) bool {
    return std.ascii.eqlIgnoreCase(word, "id") or std.ascii.eqlIgnoreCase(word, "ok");
}

fn flags_bits(flags_type: types.Record.Type) u16 {
    return switch (flags_type) {
        .AccountFlags, .TransferFlags => 16,
        .AccountFilterFlags, .QueryFilterFlags => 32,
        else => unreachable,
    };
}

fn emit_omission(
    writer: std.io.AnyWriter,
    suite: types.Suite,
    case: types.Case,
    requirement: types.Case.Requirement,
) !void {
    try write_indent(writer, case_indent_level);
    try writer.print("// Omitted: {s}_", .{suite.name});
    try emit_test_name(writer, case.description);
    try writer.writeAll("\n");
    try write_indent(writer, case_indent_level);
    try writer.writeAll("// Reason: ");
    for (@tagName(requirement)) |char| {
        try writer.writeByte(if (char == '_') ' ' else char);
    }
    try writer.writeAll("\n");
}

// Collapses anything that isn't alphanumeric into a single underscore.
fn emit_test_name(writer: std.io.AnyWriter, description: []const u8) !void {
    var last_was_underscore = false;
    for (description) |char| {
        if (std.ascii.isAlphanumeric(char)) {
            try writer.writeByte(char);
            last_was_underscore = false;
        } else if (!last_was_underscore) {
            try writer.writeByte('_');
            last_was_underscore = true;
        }
    }
}

fn write_indent(writer: std.io.AnyWriter, indent_level: u32) !void {
    try writer.writeByteNTimes('\t', indent_level * indent_width);
}

// A copy of `WithClient`'s server harness in `tb_client_test.go`, without the client, since the
// conformance suite builds one per case.
fn emit_server(writer: std.io.AnyWriter) !void {
    try writer.writeAll("\n" ++
        "func startConformanceServer(t *testing.T) {\n" ++
        "\tvar tigerbeetlePath string\n" ++
        "\tif runtime.GOOS == \"windows\" {\n" ++
        "\t\ttigerbeetlePath = \"../../../tigerbeetle.exe\"\n" ++
        "\t} else {\n" ++
        "\t\ttigerbeetlePath = \"../../../tigerbeetle\"\n" ++
        "\t}\n" ++
        "\n" ++
        "\taddressArg := \"--addresses=\" + TIGERBEETLE_PORT\n" ++
        "\tcacheSizeArg := \"--cache-grid=256MiB\"\n" ++
        "\treplicaArg := fmt.Sprintf(\"--replica=%d\", TIGERBEETLE_REPLICA_ID)\n" ++
        "\treplicaCountArg := fmt.Sprintf(\"--replica-count=%d\", TIGERBEETLE_REPLICA_COUNT)\n" ++
        "\tclusterArg := fmt.Sprintf(\"--cluster=%d\", TIGERBEETLE_CLUSTER_ID)\n" ++
        "\n" ++
        "\tfileName := fmt.Sprintf(\"./%d_%d_%d.tigerbeetle\", TIGERBEETLE_CLUSTER_ID, " ++
        "TIGERBEETLE_REPLICA_ID, rand.Int())\n" ++
        "\tt.Cleanup(func() {\n" ++
        "\t\t_ = os.Remove(fileName)\n" ++
        "\t})\n" ++
        "\n" ++
        "\ttbInit := exec.Command(tigerbeetlePath, \"format\", clusterArg, replicaArg, " ++
        "replicaCountArg, fileName)\n" ++
        "\tvar tbErr bytes.Buffer\n" ++
        "\ttbInit.Stdout = &tbErr\n" ++
        "\ttbInit.Stderr = &tbErr\n" ++
        "\tif err := tbInit.Run(); err != nil {\n" ++
        "\t\tfmt.Println(fmt.Sprint(err) + \": \" + tbErr.String())\n" ++
        "\t\tt.Fatal(err)\n" ++
        "\t}\n" ++
        "\n" ++
        "\ttbStart := exec.Command(tigerbeetlePath, \"start\", addressArg, cacheSizeArg, " ++
        "fileName)\n" ++
        "\tif testing.Verbose() {\n" ++
        "\t\ttbStart.Stderr = os.Stderr\n" ++
        "\t}\n" ++
        "\tif err := tbStart.Start(); err != nil {\n" ++
        "\t\tt.Fatal(err)\n" ++
        "\t}\n" ++
        "\n" ++
        "\tt.Cleanup(func() {\n" ++
        "\t\tif err := tbStart.Process.Kill(); err != nil {\n" ++
        "\t\t\tt.Fatal(err)\n" ++
        "\t\t}\n" ++
        "\t})\n" ++
        "}\n");
}

fn emit_new_client(writer: std.io.AnyWriter) !void {
    try writer.writeAll("\n" ++
        "func newClient(t *testing.T) Client {\n" ++
        "\tclient, err := NewClient(ToUint128(TIGERBEETLE_CLUSTER_ID),\n" ++
        "\t\t[]string{\"127.0.0.1:\" + TIGERBEETLE_PORT})\n" ++
        "\tif err != nil {\n" ++
        "\t\tt.Fatal(err)\n" ++
        "\t}\n" ++
        "\n" ++
        "\treturn client\n" ++
        "}\n");
}
